### ISSUE TITLE
Support for reflection probes on ocean shader?

### ISSUE THREAD

**Issue by antigollos** [huwb/crest-oceanrender#107]
**Foreword:**
1st of all thanks for this amazing solution, which is by far the best I've seen! Crest was the reason I started to end up creating a triple-A tech test, where I put the best environment plugins into one common denominator, with the plan to create one day a game with it.

This is how I came so far.... 

https://vimeo.com/297553979

https://vimeo.com/297549976

![terraindisplace_11](https://user-images.githubusercontent.com/43841081/47621702-e517f880-dafb-11e8-985d-f2d32effe335.JPG)

![terraindisplace_12](https://user-images.githubusercontent.com/43841081/47621713-1db7d200-dafc-11e8-8243-8aa3b2dd15ab.JPG)
![terraindisplace_13](https://user-images.githubusercontent.com/43841081/47621714-1db7d200-dafc-11e8-9199-c021394123a4.JPG)

**ISSUE:** 

Would it be possible to add reflection probes to the shader? That would give an awesome look, when it comes to relfecting a whole island. I would create a specific very low reflection object for it.

**Comment by huwb** [comment]
Wow, that's nuts! <3 Very nice, thanks a lot for posting that, and please feel welcome to post your progress again in the future! 

The system reports dynamic planar reflections (assign ocean planar reflections script to camera, and enable "planar reflections" on ocean material). Would this do the trick?

Otherwise, while I haven't tried it myself, I'm told one can simply feed the output of a dynamic reflection probe straight into the cubemap input - see this post in issue #4 from @Midda-C :

https://github.com/huwb/crest-oceanrender/issues/4#issuecomment-387584688

**Comment by antigollos** [comment]
> Wow, that's nuts! <3 Very nice, thanks a lot for posting that, and please feel welcome to post your progress again in the future!

With pleasure! =) ayntime!

> Otherwise, while I haven't tried it myself, I'm told one can simply feed the output of a dynamic reflection probe straight into the cubemap input - see this post in issue #4 from @Midda-C :

Sadly, I am not a programmer, so I am not really able to follow the procedure xD :}
I also have troubles to get the buoyancy running! :/
As a non programmer I have to dive deeper, than I am able to xD

I have to try the 1st method you have mentioned! =) The second solution from Midda-C sounds much more interesting and performance wise. I think so...

**Comment by antigollos** [comment]
I went again thru and did managed to get the reflection probe working, but you were right, the planar reflections do work great! =) and woooow, now it illuminates correctly! And it has its dreamy look!  Thank you!

**Comment by huwb** [comment]
Screenshot or it didn't happen :).

Seriously though glad it worked

**Comment by antigollos** [comment]
> Screenshot or it didn't happen :).

Ha-Haaa! I am uploading an ultra sharp video **=)** - on youtube **:(** 

I did some tuning on the water and shader parameters - again - the whole time! It makes very addictive playing around with all the parameters of crest! And instead to make a simple screenshot, I start to play around with all the settings again xD - typically artist! :/ This tooked hours - till now *shakeshead*

video is up in a moment.....

**Comment by antigollos** [comment]
Here it is.... https://www.youtube.com/watch?v=iRdANlplxL8&feature=youtu.be

I forgot how efficient planar reflections can be! =) Thanks again!

**Comment by huwb** [comment]
Thats awesome! Thanks for posting. Can i ask how you got specular on the water so nice and sparkly?

**Comment by GeorgeDziov** [comment]
Looking neat indeed! I tried reflection too, unfortunately, I'm getting flickers on distant objects but only in reflection. Tried changing clipping plane on both ends but alas that doesn't work.

I'll try to demonstrate the bug once I restore my Unity installation, that darn Windows 10 update almost killed my machine  >:(

**Comment by antigollos** [comment]
`.... how you got specular on the water so nice and sparkly?`

Yea, I know what you mean. It's really a tricky way to achieve the right effect, since there are five interdependent parameters, that react almost as same way, from the visual perspective. Which makes it somehow confusing, even if the naming of the parameters make totally sense. Turn more than two of the sliders in the wrong direction - and the whole effect gets lost, and it gets hard to find back.

I marked you the parameters on the screenshot: The arrows I added on the sliders show in which direction you should go rather to achieve a more smaller/detailed and spread sparkle effect. I hope that helps =)

![ocean_shadersettings_marked2](https://user-images.githubusercontent.com/43841081/47679702-2cb68700-dbc5-11e8-9a73-5802d26b7a61.JPG)

**Comment by huwb** [comment]
Wow, thanks.. Next time I do a tweaking pass I'll give this a stab.
