### ISSUE TITLE
Reflection and multi display

### ISSUE THREAD

**Issue by ahardy2** [huwb/crest-oceanrender#108]
Hi,

We are seeing reflection rendered on wrong camera in multi display mode (VR + Screen for example) : 
reflection calculated for camera 1 is displayed on camera 2. I will grab a couple of screens when I have some time.

Is that something you experienced too ?

Cheers,

**Comment by huwb** [comment]
Thanks for reporting. I've not used such setups here. This feels like something we can fix. Screenshots would indeed be useful. Also are you using the Ocean Planar Reflection script?

**Comment by antigollos** [comment]
If I may point out, that this isn't a bug, rather more an extension. This is simply VR =) https://community.arm.com/graphics/b/blog/posts/combined-reflections-stereo-reflections-in-vr

**Comment by huwb** [comment]
I don't think i follow, what do you mean?

**Comment by ahardy2** [comment]
Hi all,

Sorry for the lack of updates, but I had limited time to work on this last week !
I did some tests using 2 cameras on 2 different display (So no VR in the process), and still have the same behavior : 
The reflection of camera 2 is displayed over camera 1.

Here are some shots.
Secondary Camera on display 2
![crest_reflection_display2](https://user-images.githubusercontent.com/44614423/48000131-e8674180-e104-11e8-946a-144ad83caafd.PNG)

You can see that the reflection are displayed correctly for the current point of view.

Now lets switch to the main camera on display 1
![crest_reflection_display1](https://user-images.githubusercontent.com/44614423/48000209-18aee000-e105-11e8-9c7f-3b15ea844e53.PNG)

We can see that the reflection displayed on this camera are the one computed for camera 2

If I disable the secondary camera I have the good reflection back on camera 1
![image](https://user-images.githubusercontent.com/44614423/48000305-5875c780-e105-11e8-8e47-b5825280fd43.png)

I tried to force the gameobjects/cameras created by the planar reflexion to be specific to each camera, but it did not changed anything.

Cheers,

**Comment by huwb** [comment]
Thanks for the info, it might take me a bit to get onto this but I'll post back later.

**Comment by huwb** [comment]
Finally got onto this. I was pretty oblivious to the concept of displays in unity. Now reflection textures are indexed by display.

To head off another issue I'm sure you're seeing - the ocean update is attached to **one** camera. It will look for the camera on the *Viewpoint* field of the *OceanRenderer* script, which if unassigned will init to whatever is tagged as *MainCamera*. If this camera is not currently rendering, the ocean will stop updating. I looked for a while for a way to tell which cameras were actively rendering but couldnt find anything, so gave up on this. So the main camera needs to be rendering for the ocean to update.

**Comment by huwb** [comment]
Incidentally i think i fixed the latter issue - the ocean update command buffer is now executed independently of the cameras so hopefully this is sorted too
