### ISSUE TITLE
Artifacts with Tall waves and Foam Bubbles

### ISSUE THREAD

**Issue by Midda-C** [huwb/crest-oceanrender#109]
Hey!  We've been noticing a weird artifact for a while now, and we thought it was something with our fog.  However, we just realised what we're seeing is actually being caused by the bubble foam.  Basically, when you look through a tall wave at a low angle (like from our gameplay view), you see this odd infinite plane stretching off into the distance.  I recorded a video demonstrating the issue (I set the bubble foam to be bright red to make it easier to see):

https://drive.google.com/open?id=1gATnANV2aGEeXzBCGCtQRmOxtgotIA4Q

I vaguely remember you making a change some time back to make the bubble foam have a sort of paralax offset or something.  Could that be related?

**Comment by huwb** [comment]
Yeah its exactly that. The parallax is done by dividing by the view y - this implicitly assumes that the normal vector is up, i.e. a flat horizontal surface.

	half bubbleFoamTexValue = tex2Dlod(_FoamTexture, float4(.74 * foamUVBubbles - .05*i_view.xz / i_view.y, 0., 5.)).r;

I think  i_view.xz needs to be the view vector projected onto the tangent frame at that surface pos, and i_view.y needs to be dot(i_view,normal) or something. I didnt do this to save the extra instructions (i thought it added "character" :)) but it sounds like you're finding it disturbing?

**Comment by huwb** [comment]
Sure, do you want to try it locally before we commit to it and make sure thats will work for you? You can kill the view component on that line - change the .05 to a 0. for example.

**Comment by Midda-C** [comment]
Thanks, just tried that out.  Yeah, that solves the issue with tall waves.  Either a toggle for the parrallax or even a slider to scale the effect would be a good, versatile solution. :)

**Comment by huwb** [comment]
Added now, seems to work for me!

**Comment by huwb** [comment]
@Midda-C found a fix that should only add one instruction and seems to work pretty well so maybe this is usable now?

I made a vid but google docs seems to be acting funky so not sure if you'll be able to access this or not:

https://drive.google.com/open?id=1p4CTVU6Cj_xTkpPGsAHhfQjFNz5RPzNo

**Comment by Midda-C** [comment]
Yeah video works fine.  Looks nice, I'll have a play with it and let you know!

Thanks! :D

**Comment by Midda-C** [comment]
Just tried this in our project.  It works well, happy to have the foam parallax back without any compromises!  Thanks for revisiting this! :D
