### ISSUE TITLE
[SUGGESTION] Simple Tint (for PR)

### ISSUE THREAD

**Issue by GeorgeDziov** [huwb/crest-oceanrender#112]
There is a myriad of options adding a tons of flexibility to Ocean shader already but Ikinda miss tint, mostly when using planar reflections.

Fresnel is closest but it starts hiding reflection from camera to horizon which while may be realistic is not always convenient.
I've encountered distant geometry flickering recently and tried masking it while leaving close reflections visible but, alas, couldn't do anything about it.

But aside from that tint could be handy design wise, say, if you need reflection and keep mpst details but still want background to be less intrusive.

**Comment by huwb** [comment]
I'm not sure i've understood - what would the tint do exactly? is it that you want to separately multiply different components of the shading (refract vs reflect)?

**Comment by huwb** [comment]
Hmm.. im still not really sure. Oh are you saying it should not be based on view angle, you just want one fresnel effect for the whole surface? I can easily point you to a line of code to hack if this is the case.

**Comment by GeorgeDziov** [comment]
I guess yes, can't say for sure, need to see that first. Sounds good though,

**Comment by huwb** [comment]
You can mess around with this in OceanReflection.hlsl, by removing R_theta and replacing it with some constant between 0 and 1, on this line:

	col = lerp(col, skyColour, R_theta);

If you set it to 1.0, it will take 100% sky colour.

I dont imagine that this is going to work out well, as fresnel is the major component of why water looks the way it does, and you'll probably lose a big part of the shape definition. But feel free to try it out :).

**Comment by GeorgeDziov** [comment]
Wellllll, having an option is always handy so thanks for giving one! ;)

**Comment by huwb** [comment]
Sure thing :)
