### ISSUE TITLE
Fast Caustics

### ISSUE THREAD

**Issue by GeorgeDziov** [huwb/crest-oceanrender#114]
https://www.youtube.com/watch?v=JGlLghRv158

It only happens in the beginning and lasts a couple seconds, then it goes back to normal.
It's caused by directional light with simple constant rotation script.

Not a big issue, can be easily worked around by fading in or starting above ocean but still thought it's worth posting.

Underwater Skirt branch, downloaded on 28.10.2018

**Comment by huwb** [comment]
Hey there,

I'm not sure if theres a fix to be made - I believe this is "realistic" even if it looks funky!

One option is you could fade in the caustics, there are controls over the depth at which caustics apply and how they're blurred..?

**Comment by GeorgeDziov** [comment]
I see, just seemed strange because light rotates constantly with same slow speed and caustics change irregularly. Also, you can notice caustics strecth weirdly on the left on the video. 

But if it's not broken, then there's no need in fixing I guess.

**Comment by huwb** [comment]
It projects the caustics along the light direction. If the angle of the light is 'shallow' then it could project down to something that moves fast over the surfaces, and that projection can get distorted as well.

Having said that it could of course be a bug, or im completely misunderstanding. You could play with the caustics code to figure out if a particular component of it is making it go nuts and then i might be able to help further.

**Comment by GeorgeDziov** [comment]
This may sound wrong but is there a way to set caustics just to one certain angle? I was thinking about turning off rotation script and set the light to one angle but if there's another way of doing this, that would help a lot! Not top priority thogh.

**Comment by huwb** [comment]
Yes, search for this line in the ApplyCaustics() function and used a hardcoded light direction instead of using i_lightDir.

	float2 surfacePosXZ = scenePos.xz + i_lightDir.xz * sceneDepth / (4.*i_lightDir.y);

This is not something I would push into crest unless i see more people requesting this kind of thing, so i'll leave you to decide if you want to make that code change locally or work around it in another way.

**Comment by GeorgeDziov** [comment]
Totally understandable! Still, thanks for leaving an option! I really like the way caustics behave in general, it's just I needed a workaround for that angle thing.
