### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by JJarvis89** [huwb/crest-oceanrender#115]
Hey,

Great work on everything so far! We are using Crest for a professional product and are wondering when you plan on publishing the next release since a lot of things have been added/changed since the last release! Obviously I could just clone the master branch, but I'm just wondering whether it would be better to just wait for something more official :) 

Thanks for the great work & best regards!

**Comment by huwb** [comment]
Thanks! Can i be nosey and ask which one? If not no worries :)

Yeah i was thinking the same thing this morning. I have a bad habit of making a release immediately after big feature drops and end up with buggy releases. So i'm going to let the collision system rebuild and the underwater stuff stew for a bit. Maybe in a week or two from now..

**Comment by huwb** [comment]
I'll close for now but will post when I make a release.

**Comment by JJarvis89** [comment]
Thanks for update! Regarding the game, I'm not allowed to say yet :D.

**Comment by huwb** [comment]
Published version 4 :)

https://github.com/huwb/crest-oceanrender/releases
