### ISSUE TITLE
Reflection Cam Sensitive Occlusion

### ISSUE THREAD

**Issue by GeorgeDziov** [huwb/crest-oceanrender#116]
https://youtu.be/C_7wvAB4UvI

Hate to say that but relfection cam hides objects too early. I also tested some primitive geometry in the demo scene, same result - if you look down, objects disappear.

I  tried turning occlusion culling off but same stuff happens.

**Comment by huwb** [comment]
Yep broken for me too! I could not figure out why this is the case (the reflection stuff in the Environment standard assets does not exhibit this behaviour despite having very similar code).

The camera preview in the scene view looks all good, it seems to be only the culling that is broken. I tried calling Camera.Render() from different functions such as Update() but it didnt make a difference.

In the end i may have stumbled upon a fix via trial and error - setting the culling matrix before calling Render() by adding a single line in oceanplanarreflection.cs. This seems to sort it but could you try adding this change as well?

            _camReflections.transform.eulerAngles = new Vector3(-euler.x, euler.y, euler.z);
            _camReflections.cullingMatrix = _camReflections.projectionMatrix * _camReflections.worldToCameraMatrix; // *NEW*
            _camReflections.Render();

**Comment by GeorgeDziov** [comment]
Works like a charm! Thanks for fix! :)

**Comment by huwb** [comment]
Great, pushed the fix now. Thanks!
