### ISSUE TITLE
Flat waterplane under ocean ( in a cave )

### ISSUE THREAD

**Issue by ibbybn** [huwb/crest-oceanrender#118]
Imagine you're diving underwater into a cave. Going up in the cave there's a transition to land where the waterlevel is under the oceanlevel. I basically created another oceanrenderer without skirt and already made a script disabling all the ocean tile meshrenderers too far from a certain point to create this transition water plane.

How can i get both sides of the "lake" to be transparent and shaded correctly. Tried all the shader options and can't find a way. There's always just one side transparent and the other solid depending on the underwater option in the shader.

The ocean itself uses the ocean underwater material and works from both sides correctly;

Also needed was changing the weight in the shapegerstnerbatched when approaching the lake to not get huge ocean waves. Perhaps it would be good to be able to assign this per ocean ?

For anyone wanting to make a lake above or below oceanlevel here's the tile disabler script ( add to ocean gameobject and assign lods var your lodcount ):

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class OceanToLake : MonoBehaviour {

	public Transform target;
	public float distance;
	public float tileDistance;
	private List<Transform> tiles;
	private List<MeshRenderer> rends;
	public int lods;
	IEnumerator Start () {
		tiles = new List<Transform> ();
		rends = new List<MeshRenderer> ();

		yield return new WaitForSeconds (5);

		for (int i = 0; i < lods; i++) {
			var childCount = transform.GetChild (i).childCount;
			for (int j = 0; j < childCount; j++) {
				if (transform.GetChild (i).GetChild (j).GetComponent<MeshRenderer> () != null) {
					tiles.Add (transform.GetChild (i).GetChild (j).transform);
					rends.Add (transform.GetChild (i).GetChild (j).GetComponent<MeshRenderer> ());
				}
			}
		}
	}

	void Update () {
		if (tiles.Count == 0) return;

		if (Vector3.Distance (transform.position, target.position) > distance) return;

		for (int i = 0; i < tiles.Count; i++) {
			if (Vector3.Distance (tiles[i].position, target.position) < tileDistance) {
				rends[i].enabled = true;
			} else {
				rends[i].enabled = false;
			}
		}
	}

}
```

**Comment by huwb** [comment]
Can you not use a single ocean, and change the sea level when you enter the cave?

**Comment by huwb** [comment]
Or use something like #95  to push the ocean surface above down to the level of the lake when you enter the cave

**Comment by ibbybn** [comment]
Hm haven't even thought of just moving it. Then again both ocean and cave transition are visible when looking up the entrance but I guess that's just a level building problem. Will have a look if it's possible in every level to create some tighter transition areas to move the ocean. I guess it's non trivial to make the shaders work in this situation?

**Comment by huwb** [comment]
Yeah the assumption of one single ocean is everywhere in crest, I'm impressed you were able to get that far. OceanRenderer.Instance is used everywhere for all kinds of things and points to a single instance.

It would be possible to change this but it would be a big rework, and you would pay a big cost for running everything twice.

**Comment by ibbybn** [comment]
Yes was also surprised this even works and since the only problem was really one side rendered solid I thought it might be a quick fix. Wouldn't want to start a big rework for my unusual case.
