### ISSUE TITLE
Help/Request: Auto-moving/sliding ocean

### ISSUE THREAD

**Issue by KjetilMV** [huwb/crest-oceanrender#119]
Hi

First time posting. I apologize in advance if this isn't by the book. 

I'm working on a VR project with alot of physics simulations. Since the user is standing still on a ship it would be ideal for us to just have to ocean move on itself, giving the illusion that the boat we're on is moving,  while the stage itself stays at transform zero.

I've tried doing something simple in the LateUpdatePosition() in OceanRenderer, but I've just succedded in moving the LOD, but not the ocean properly. 

Hope you can help / point me in the right direction.

Also: love the shader!

Thanks,

Kjetil

**Comment by huwb** [comment]
Interesting question.

I haven't really thought it through, but I reckon you want to do an offset in the wave shader. In oceangerstnerbatched, try offsetting the input world position xz and it should cause all the waves to shift accordingly..

**Comment by KjetilMV** [comment]
Thanks for the quick reply. Do you mean ShapeGerstnerBatched script or ShapeGerstnerBatch shader?

**Comment by huwb** [comment]
The shader.

**Comment by huwb** [comment]
Oh and if you use flow you can get a standing wake, and motion in the foam, and good stuff like that. If you look in the whirlpool scene you can see an example of rotating flow, you just need constant flow in one direction I guess.

**Comment by huwb** [comment]
Closing for now, if you run into specific problems let me know.
