### ISSUE TITLE
Moving the ocean doesn't update lod calculation height

### ISSUE THREAD

**Issue by ibbybn** [huwb/crest-oceanrender#120]
As discussed in the lake underwater issue I'm now moving the ocean down to get a lake in a cave but it's choosing a big scale for the ocean transform because I'm far from the initial ocean height with the camera.
For example ocean starts at height 15. Moving it down to -15. Then only if the camera is near 15 will it give LOD0. Can you point me to where this is set in the scripts?

-EDIT
I just saw the lod system is being refactored anyway. Maybe that's one more thing to consider?

-EDIT2
Also is there an elegant way to turn on and off the ocean when in an area where it's not visible?
I've tried turning off the gameobject but this throws alot of errors turning it on again. Best solution I've found is setting all the farclipvalues to 2 and taking out the meshrenderers. Is there something more elegant I'm not aware of?

**Comment by huwb** [comment]
Yeah you can find it in oceanrenderer, there is an update function for scale.

Refactor won't change this.

Turning off ocean object is probably desirable. If there are errors we should fix them, I can take a look after refactor.

**Comment by ibbybn** [comment]
Thx, turns out just setting minscale maxscale to 1 when moving the ocean is a better fix since i don't need the other lods in that case anyway.

Will have a look at the errors after the next updates and open another issue if I can't fix them myself.

Btw InitViewpoint never assigns _planarReflections if you assign the viewpoint transform in the editor stopping them from working this way. 1 line fix so I'll just drop it here. Aand closing.

**Comment by huwb** [comment]
Thanks for finding the bug in InitViewpoint, fixed in the referenced commit!
