### ISSUE TITLE
Only One Layer in Reflection

### ISSUE THREAD

**Issue by GeorgeDziov** [huwb/crest-oceanrender#121]
Recently noticed only "Default" layer appears in reflection because I'm using an additional layer in my project. I made a kinda dirty "fix" by entering `dest.cullingMask = src.cullingMask;` after line 137 in "PlanarReflection" script but I dunno if it's ok to do this, maybe there's some more elegant solution to this...

Anyway, for me this issue is already fixed but I thought it still needs your attention.

**Comment by huwb** [comment]
You should be able to configure which layers to reflect on the ocean planar reflection script.

**Comment by GeorgeDziov** [comment]
Took me long to answer, was trying to add code that allows to add all current layers into reflection on start but, nnnnnope not yet so I'm closing the issue but if I come up with something useful, I'll post that.
