### ISSUE TITLE
Change Planar Reflection Amount

### ISSUE THREAD

**Issue by gameanimation3d** [huwb/crest-oceanrender#122]
Hey,

is it possible or possible to implement a way to reduce the transperency of the PlanarReflection? 
Because the PlanarReflection is to intense but i don't wand to reduce the whole reflection in the shading.

Btw. thank you for creating and mainting this amazing ocean/fluid framework!

**Comment by gameanimation3d** [comment]
thank you very much for the answer

**Comment by huwb** [comment]
Sure!
