### ISSUE TITLE
Question: Enabling water in runtime

### ISSUE THREAD

**Issue by konstantin890** [huwb/crest-oceanrender#124]
Hi, I'm trying to load Crest water and OceanWaver (Shape Gastern Batcher) in runtime after I do stuff with the cameras. So I made a script that activates the Ocean gameobjects after doing some stuff and when there's an active camera in the scene, I enable both objects, first OceanRenderer and the SGB, after that there's no errors, but the water looks like this:
![image](https://user-images.githubusercontent.com/20709057/48645864-a20cbf00-e9ef-11e8-955d-f601f25ed204.png)

And when I go up it changes to this:
![image](https://user-images.githubusercontent.com/20709057/48645880-b2bd3500-e9ef-11e8-980e-8bccb7ffc9cc.png)

So my question is: Is this supported by Crest if so what am I doing wrong?

Thanks!

**Comment by konstantin890** [comment]
And also I don't know why when I set the ocean level (Y) to 50, it goes to like 150, but it's not visible in the hierarchy

**Comment by huwb** [comment]
Hi there, hm that's weird - im not sure what would cause that behaviour.

If i open up whats currently on the master branch (are you on latest?) and do exactly this, then it works fine for me:

* Open Crest-Examples/Scenes/main.unity
* In edit mode, disable the Ocean gameobject, the OceanWavesBatched gameobject, and the IslandDepthCache gameobject
* Press play to enter play mode, no ocean will be visible
* Activate the Ocean gameobject, flat water will be visible
* Activate the IslandDepthCache gameobject, this should render the sea floor depth and shallow water colours will appear
* Activate the OceanWavesBatched gameobject and the waves should appear

This works without errors for me. Does this work for you?

**Comment by konstantin890** [comment]
My Ocean gameobject holds the ocean renderer script in editor I disabled this gameobject, then in runtime after I setup the camera configuration, I enable the ocean gameobject and the water looks like this. I made some changes in the water material, maybe that could cause it? What about the sea level issue? I'll be able to send you a sample for testing tommorow.

**Comment by huwb** [comment]
Or could you retrace my steps exactly and confirm it does/doesn't work for you in the example content?

Material changes would not affect it andi have no idea why the sea level would do that.

**Comment by konstantin890** [comment]
Sorry for the very delayed response!
Seems like the issue doesn't appear now... Probably because of Unity update or updating Crest. 
Sorry for the inconvenience!
