### ISSUE TITLE
Planar Reflection Issue in combination Subsurface Scattering via Post FX

### ISSUE THREAD

**Issue by gameanimation3d** [huwb/crest-oceanrender#125]
Hey,

i am currently trying to get the Planar Reflection Feature working with the Subsurface Scattering Shader supplied by the Post FX v01 stack.
I already got it working with the Reflection Camera, by adding an Post FX Stack with the settings to the Camera. Only the Subsurface Scattering Feature is enabled.

The reflection of the SSS is correctly visible but if have the Post FX enabled the Reflection Camera renders an white area into the RenderTexture. Therefore an white blooming of the water happens and no Environment reflection happens.

Do you know what's the problem?
![planar_general](https://user-images.githubusercontent.com/44543590/48676053-8aedde80-eb61-11e8-9499-8c4cf6b07b57.JPG)
![planar_issue](https://user-images.githubusercontent.com/44543590/48676054-8aedde80-eb61-11e8-9b9d-c218bae23ea0.JPG)
![rendertexture issue](https://user-images.githubusercontent.com/44543590/48676067-c38db800-eb61-11e8-8f23-d41c66f3e273.JPG)
![rendertexture without postfx](https://user-images.githubusercontent.com/44543590/48676068-c38db800-eb61-11e8-9dfa-baddaa2eb4d2.JPG)

**Comment by huwb** [comment]
Err no thats not something i have experience with. You're saying that the duck has a SSS material applied and it appears white in the reflection?

One thing i copied from planar reflection code is the disabling of pixel lights - have you tried with this option turned off on the Ocean Planar Reflection script - _disablePixelLights ?

Another test would be to try the out of the box unity reflection script. It would at least indicate if i've messed something up. The script can be imported by importing the standard environment assets - Assets/Import Package/Environment.

**Comment by gameanimation3d** [comment]
Hey, thank you for the answer

Turning of _disablePixelLights worked perfect and solved the issue 👍

**Comment by huwb** [comment]
Wow ok then! :)

**Comment by gameanimation3d** [comment]
> 
> 
> Wow ok then! :)

Hey,
sorry i was a bit to fast. Turning of _disablePixelLights didn't worked the artifacts didn't changed. I forgot to see it fullframe and just saw a small game view. i was bit in a hurry and just wanted to answer you quickly.

Nevertheless your second answer using the unity planar reflection worked. No Blooming artifacts btw. whiting of th the rendertexture appeared.
![grafik](https://user-images.githubusercontent.com/44543590/48913862-fabddb00-ee79-11e8-955e-4c743595cf9c.png)
![grafik](https://user-images.githubusercontent.com/44543590/48913895-13c68c00-ee7a-11e8-8ea7-1a134e721049.png)

I added the Water4Advanced Prefab with the FX/Water Shader. Aswell i changed the rendering to Deferred which is needed for SSS. Further I attached the PostFX Stack to the ReflectionCamera
I hope this helps you :)

**Comment by gameanimation3d** [comment]
@huwb could you re-open the Issue? i can't do it

**Comment by huwb** [comment]
Oh sure

**Comment by huwb** [comment]
It's probably the deferred render path. Could you try messing with the planar reflection camera at runtime - set it to deferred and see if that fixes the problem? There should be a debug option to make this camera visible.

**Comment by gameanimation3d** [comment]
i set the reflection camera per script aswell at runtime to Deffered and disabled MSAA. Didn't helped.
When I unhide the environment e.g the wall the white in the rendertexture is reduced. The environment uses the stanard unity shader with baked light mapping. 
The reflection camera is under the ocean line could this results the problem?

**Comment by huwb** [comment]
Yeah if you could send me the project (if you could strip anything out please do so, just for convenience/data size) i'll try to take a look soon. Sorry i'm not able to be more helpful or offer proper support with this project, but ill do my best to lend a hand.

**Comment by gameanimation3d** [comment]
by comparing the planar reflection script with the unity reflection system i found the issue.
The Rendertexture was the issue. The depth buffer was set to 16bit Depth(no stencil) changing it to 24bit Depth(with Stencil) solved it. 
![temp2](https://user-images.githubusercontent.com/44543590/49014990-1a0e7e00-f182-11e8-811f-695b67c25416.jpg)
btw i reduced the reflection that why it is so suddle.

**Comment by huwb** [comment]
ah awesome! are changes required to crest - should i expose an option to enable stencil bits?

**Comment by huwb** [comment]
I added a Stencil option to the script which should sort it. thanks for tracking that down!

**Comment by gameanimation3d** [comment]
> 
> 
> I added a Stencil option to the script which should sort it. thanks for tracking that down!

Perfect
