### ISSUE TITLE
Planar reflections not affected by waves, distortion / refraction 

### ISSUE THREAD

**Issue by Draydak** [huwb/crest-oceanrender#126]
The planar reflections stay as if calm flat water, regardless of what you do with the wave settings. Sadly this leaves it looking not realistic and just wrong.

I'm definitely keeping my eye on this asset though as you are making great progress!

**Comment by Draydak** [comment]
The planar reflections stay as if calm flat water, regardless of what you do with the wave settings. Sadly this leaves it looking not realistic and just wrong.

I'm definitely keeping my eye on this asset though as you are making great progress!

**Comment by Draydak** [comment]
ah yea you hit the nail on the head. For my considered usage I probably won't be using large waves / choppy surface so it will look good enough.

I will probably have a look in the shader when I get motivated, I need to look into your code deeply as I was looking into the problem of waves and wakes some months ago before I took a break.

But I've just been enjoying your hard work and seeing what I could achieve with it, it's an impressive asset. I imagine It would benefit from being migrated to the new render pipeline but I've no idea how much work that involves.

If I sort anything out on the reflections I will feed it back to the project

**Comment by huwb** [comment]
Thanks @Draydak
