### ISSUE TITLE
Question: ocean increase visibilty to the ground - "clean water"

### ISSUE THREAD

**Issue by gameanimation3d** [huwb/crest-oceanrender#128]
Hey,

how can I make the "ocean" water more clear/clean. The visibilty through the water is a bit muddy/foggy currently as you can see on the frames. I want to see more of the ground of the bathtub. Do you have an Idea? If i disable scattering in the shader or change the parameters it doesn't help.
I hope you can help me.
Btw I am using the Crest as Realtime Fluid Simulation alternative instead of Houdini FLIP Solver/Maya BOSS.

![grafik](https://user-images.githubusercontent.com/44543590/48922000-d676f400-eea3-11e8-80da-6c5126329609.png)
![image_0169](https://user-images.githubusercontent.com/44543590/48922003-de369880-eea3-11e8-8bce-5658c1876eca.jpg)

**Comment by ibbybn** [comment]
In the OceanRenderer component double click the ocean material and under Transparency change the density vector. The lower the values the more transparent.

**Comment by gameanimation3d** [comment]
Hey,
Thank for you the advice. But i already set the transperency to 0.01 on all values.
But i wasn't aware its an vector. Might it be that need to change the vector direction to one which matches the cameras viewing angle onto the ocean plane?

**Comment by huwb** [comment]
Each density component is per colour channel (RGB). If you try the demo content you should be able to to make the ocean completely transparent - I don't have any ideas why its not working in your scene. It might be worth stripping back anything that might affect it, such as any post process stuff you might have turned on?

**Comment by huwb** [comment]
I can see the duck fairly clearly through the water, but not the bath tub? Is the bath using a transparent shader or something?

**Comment by gameanimation3d** [comment]
So i followed your advice and took the demo scene and copied the Ocean aswell as the camera over the to the scene and disabled everything else except the bathtub mesh.
The shader of the bathtub is a standard unity shader with rendering mode: opaque. 
After some debugging and disabling the the normal map i think this "issue" gets resulted as the reflections are so intensie in such a low angles camera position. Compared to higher camera position in the scene
![2](https://user-images.githubusercontent.com/44543590/48977587-882d4500-f09d-11e8-8b1d-c644e1b51487.JPG)
![2_5](https://user-images.githubusercontent.com/44543590/48977588-88c5db80-f09d-11e8-9562-cf1a42b70fb0.JPG)
![3](https://user-images.githubusercontent.com/44543590/48977589-88c5db80-f09d-11e8-8732-9b8a8edf3b78.JPG)
![4](https://user-images.githubusercontent.com/44543590/48977590-88c5db80-f09d-11e8-8a4e-db0ccee1c780.JPG)

I already exposed the IOR values from the OceanReflection.hlsl in the Shader to reduce the reflection amount #122 . But those values doesn't help as you can't really decrease the reflection. Changing the values results more in an increase sometimes only a farly limit of reduction happens.

Is there an other hardcoded value in the Shader where the reflection"overlay" amount can be adjusted?

**Comment by huwb** [comment]
Ohh ok :)

Usually the IORs and the _FresnelPower are the ones ive seen exposed, i guess you've already messed with these.

You could add another param that just multiplies down R_theta to just ramp down the amount of reflectance globally i guess, or if you want to go further you could do it based on camera distance or something.

**Comment by gameanimation3d** [comment]
Multiplying the R_theta gave me the great control to change reflection amount and dial it complety down.
Nevertheless i still get an "fog barrier" in the water and I disabled all three scatterings.
![grafik](https://user-images.githubusercontent.com/44543590/48978137-0e01be00-f0a7-11e8-8ff3-31f8b2b4678c.png)
 It seemed the colour is from the Diffuse Parameter/Scattering this seems to happen in the OceanEmission.hlsl
there is an // depth fog & caustics applied in line 190

How can i reduce this amount of Subsurface Scattering/depth or diffuse color?

**Comment by huwb** [comment]
I'm not sure what would be causing that.. Maybe try knocking out parts of the code to see if you can pinpoint what it is?

**Comment by gameanimation3d** [comment]
hey,
i was able to pinpoint it.
Its in OceanEmission.hlsl the _DepthFogDensity attribute.
i added in line 179 	_DepthFogDensity = _DepthFogDensity/10; to reduce the parameter.
This removed the corresponding fog effect.
But i don't know which particular command it is or if breaks other features
![temp](https://user-images.githubusercontent.com/44543590/50087817-8ae50b00-0201-11e9-81bf-60a4aaca7b91.PNG)

**Comment by huwb** [comment]
That should be equivalent to reducing the density by a factor of 10 on the material settings - this param is exposed to the user. You said you set it to 0.01 in a post above. Could you try reverting that change and setting it to 0.001 on the material.

**Comment by huwb** [comment]
Assuming fixed to keep issues ticking over. Let me know if im closing prematurely!

**Comment by gameanimation3d** [comment]
yes it is fixed, was my issue
