### ISSUE TITLE
Weird mountain silhouette not affected by waves

### ISSUE THREAD

**Issue by hayes87** [huwb/crest-oceanrender#130]
Hey, in the main scene, theres a weird artifact when looking up to the mountains from underneath the waves. The silhouette of the mountains that doesnt seems to affected by the waves.

![image](https://user-images.githubusercontent.com/13965390/48969946-172e5480-efed-11e8-82ce-468142534f46.png)

**Comment by huwb** [comment]
Hey, yeah thats an issue with the refraction. I think similar issues will occur in a different but related scenario - a foreground object in front of the surface, which can produce ghosting around the object silhouette, highlighted here:

![image](https://user-images.githubusercontent.com/939901/48972780-1cf65b00-f02a-11e8-8523-be1436e55c2f.png)

*OceanEmission()* does a couple of samples from the scene colours/depths and uses a heuristic to decide which sample to take, but i dont think the code has aged very well and is overdue for some TLC and maybe a rewrite.

I'm not able to work on this immediately but i'll post if i do. Thought i'd give some context in case someone else can pick it up.

**Comment by huwb** [comment]
I have given the code some much needed TLC and simplified it, and addressed both of the images shown above. Let me know if you still see issues. Thanks for reporting!
