### ISSUE TITLE
Question: moving the ocean

### ISSUE THREAD

**Issue by Sickname** [huwb/crest-oceanrender#131]
Hi

I'm working with large distances and to work around the floating-point precision limitations I am using this script http://wiki.unity3d.com/index.php/Floating_Origin to translate all objects in the scene so the camera stays near the scene's origin. The problem is that the Ocean does not move the same way and it is clearly visible from the waves when these translations happen.

So my question is what can I do to make this translation seamlessly with the Ocean. Any help will be appreciated. 

Thanks in advance.

**Comment by huwb** [comment]
One thing to try might be to make that floating origin script do its thing before the ocean updates. So go to the Scrip Execution Order and make add floating origin and give it something like -200 as an order index. 

Another thing to try would be to make this script move only a particular transform, and move everything you want moved under that transform. So make a world root and then this script only moves the world root. That would mean the script does not have to do a FindObjectsOfType(typeof(Transform)) call which is a pretty nasty thing to do at runtime.

**Comment by Sickname** [comment]
I tried changing the execution order but it didn't work. Also the thing is that if I move the ocean's mesh the shader is rendering the waves on the exact same spot so it makes no difference if I move the ocean gameobject or not. Sorry If I explained it poorly.

**Comment by huwb** [comment]
Oh. Yeah.. this will probably take a significant amount of engineering to get working.

If you're game, there are two things that occur to me as first steps. Firstly i think worldPos_wt needs to somehow be compensated for whatever relative shift has been applied. I'm not sure what the exact operation is, or what kind of precision problems you'll encounter (probably the exact ones you're trying to avoid using that script..!?). The second thing is that _renderDataPrevFrame probably needs to be shifted (and maybe _renderData too). And anything else in the system that caches positions.

Oh and also collision readback requests - these store renderdata structs and probably need correction applied to the positions that they store, i guess?

**Comment by huwb** [comment]
Closing but if you run into particular issues you can post them and i'll give any thoughts i might have.

**Comment by huwb** [comment]
Similar question posted in #150
