### ISSUE TITLE
BoatAlignNormal + Loading scene issue

### ISSUE THREAD

**Issue by ibbybn** [huwb/crest-oceanrender#134]
I'm using most of the code from BoatAlignNormal to get the height for some objects in my project but when loading a savegame of the same level you're already in I get NativeArray has been deallocated errors.
I've been able to reproduce that error in your boat example scene also both using UnityEngine.SceneManagement.SceneManager.LoadScene() and LoadSceneAsync().

I also had problems putting that script on a singleton then jumping to a scene without an ocean and back. Now i got the script only in the ocean scenes which got rid of the errors til I've tested the savegame system again.

EDIT: Forgot to add I'm on 2018.3.0b12 with burst / jobs / incremental compiler packages on the latest if it makes a difference.

3 errors:

InvalidOperationException: The NativeArray has been deallocated, it is not allowed to access it
Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle.CheckReadAndThrowNoEarlyOut (Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle handle) <0x545ce3c0 + 0x00052> in <2c3378a40e82477495a26e1d6b0df577>:0
Unity.Collections.NativeArray`1[T].CheckElementReadAccess (System.Int32 index) (at C:/buildslave/unity/build/Runtime/Export/NativeArray/NativeArray.cs:117)
Unity.Collections.NativeArray`1[T].get_Item (System.Int32 index) (at C:/buildslave/unity/build/Runtime/Export/NativeArray/NativeArray.cs:138)
Crest.GPUReadbackBase`1+ReadbackData[LodDataType].InterpolateARGB16 (UnityEngine.Vector3& i_worldPos, UnityEngine.Vector3& o_displacement) (at Assets/Crest/Scripts/GPUReadback/GPUReadbackBase.cs:384)
Crest.GPUReadbackDisps.SampleDisplacement (UnityEngine.Vector3& i_worldPos, UnityEngine.Vector3& o_displacement, System.Single minSpatialLength) (at Assets/Crest/Scripts/GPUReadback/GPUReadbackDisps.cs:100)
Crest.GPUReadbackDisps.GetPositionDisplacedToPosition (UnityEngine.Vector3& in__displacedWorldPos, System.Single minSpatialLength) (at Assets/Crest/Scripts/GPUReadback/GPUReadbackDisps.cs:189)
Crest.GPUReadbackDisps.SampleHeight (UnityEngine.Vector3& i_worldPos, System.Single& height, System.Single minSpatialLength) (at Assets/Crest/Scripts/GPUReadback/GPUReadbackDisps.cs:164)
Crest.CollProviderCache.SampleHeight (UnityEngine.Vector3& i_worldPos, System.Single& height, System.Single minSpatialLength) (at Assets/Crest/Scripts/Collision/CollProviderCache.cs:99)
LerpCam.Update () (at Assets/Crest-Examples/BoatDev/Scripts/LerpCam.cs:14)

InvalidOperationException: The NativeArray has been deallocated, it is not allowed to access it
Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle.CheckReadAndThrowNoEarlyOut (Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle handle) <0x545ce3c0 + 0x00052> in <2c3378a40e82477495a26e1d6b0df577>:0
Unity.Collections.NativeArray`1[T].CheckElementReadAccess (System.Int32 index) (at C:/buildslave/unity/build/Runtime/Export/NativeArray/NativeArray.cs:117)
Unity.Collections.NativeArray`1[T].get_Item (System.Int32 index) (at C:/buildslave/unity/build/Runtime/Export/NativeArray/NativeArray.cs:138)
Crest.GPUReadbackBase`1+ReadbackData[LodDataType].InterpolateARGB16 (UnityEngine.Vector3& i_worldPos, UnityEngine.Vector3& o_displacement) (at Assets/Crest/Scripts/GPUReadback/GPUReadbackBase.cs:384)
Crest.GPUReadbackDisps.SampleDisplacement (UnityEngine.Vector3& i_worldPos, UnityEngine.Vector3& o_displacement, System.Single minSpatialLength) (at Assets/Crest/Scripts/GPUReadback/GPUReadbackDisps.cs:100)
Crest.GPUReadbackDisps.ComputeUndisplacedPosition (UnityEngine.Vector3& i_worldPos, UnityEngine.Vector3& undisplacedWorldPos, System.Single minSpatialLength) (at Assets/Crest/Scripts/GPUReadback/GPUReadbackDisps.cs:58)
Crest.CollProviderCache.ComputeUndisplacedPosition (UnityEngine.Vector3& i_worldPos, UnityEngine.Vector3& undisplacedWorldPos, System.Single minSpatialLength) (at Assets/Crest/Scripts/Collision/CollProviderCache.cs:75)
BoatAlignNormal.FixedUpdate () (at Assets/Crest-Examples/BoatDev/Scripts/BoatAlignNormal.cs:76)
-------------------------
InvalidOperationException: The NativeArray has been deallocated, it is not allowed to access it
Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle.CheckReadAndThrowNoEarlyOut (Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle handle) <0x545ce3c0 + 0x00052> in <2c3378a40e82477495a26e1d6b0df577>:0
Unity.Collections.NativeArray`1[T].CheckElementReadAccess (System.Int32 index) (at C:/buildslave/unity/build/Runtime/Export/NativeArray/NativeArray.cs:117)
Unity.Collections.NativeArray`1[T].get_Item (System.Int32 index) (at C:/buildslave/unity/build/Runtime/Export/NativeArray/NativeArray.cs:138)
Crest.GPUReadbackBase`1+ReadbackData[LodDataType].InterpolateARGB16 (UnityEngine.Vector3& i_worldPos, UnityEngine.Vector3& o_displacement) (at Assets/Crest/Scripts/GPUReadback/GPUReadbackBase.cs:384)
Crest.GPUReadbackDisps.SampleDisplacement (UnityEngine.Vector3& i_worldPos, UnityEngine.Vector3& o_displacement, System.Single minSpatialLength) (at Assets/Crest/Scripts/GPUReadback/GPUReadbackDisps.cs:100)
Crest.GPUReadbackDisps.GetPositionDisplacedToPosition (UnityEngine.Vector3& in__displacedWorldPos, System.Single minSpatialLength) (at Assets/Crest/Scripts/GPUReadback/GPUReadbackDisps.cs:189)
Crest.GPUReadbackDisps.SampleHeight (UnityEngine.Vector3& i_worldPos, System.Single& height, System.Single minSpatialLength) (at Assets/Crest/Scripts/GPUReadback/GPUReadbackDisps.cs:164)
Crest.CollProviderCache.SampleHeight (UnityEngine.Vector3& i_worldPos, System.Single& height, System.Single minSpatialLength) (at Assets/Crest/Scripts/Collision/CollProviderCache.cs:99)
Crest.OceanRenderer.LateUpdateViewerHeight () (at Assets/Crest/Scripts/OceanRenderer.cs:213)
Crest.OceanRenderer.LateUpdate () (at Assets/Crest/Scripts/OceanRenderer.cs:167)

**Comment by ibbybn** [comment]
Actually you get the same errors by just disabling the ocean gameobject in the boat example scene.
Still happens even if you disable all the boatalignnormal gameobjects beforehand though so not sure how to avoid this without code changes.

**Comment by ibbybn** [comment]
Actually was pretty simple, I just moved the GPUReadbackDisps.Start() into an Init() method and use OnEnable/Disable like so:

      private void Init () {
            base.Start ();

            if (enabled == false) {
                return;
            }

            Debug.Assert (_instance == null);
            _instance = this;

            _settingsProvider = _lodComponent.Settings as SimSettingsAnimatedWaves;
        }
        private void OnEnable () {
            Init ();
        }
        private void OnDisable () {
            _instance = null;
        }

Still getting some of those Renderdata validation failed for 7 frames but then they stop.

**Comment by huwb** [comment]
Thanks a bunch @ibbybn , really useful info. I will respond when I've had a chance to investigate. I thought i had tried reloading levels (bound to the R key in OceanDebugGUI if you have that enabled) and didnt see this, but its possible i neglected to try this. I'll also try the other repro step you mentioned.

**Comment by huwb** [comment]
So i implemented something very similar to you - instead of re-initing on enable, i flush on disable because i dont want the stale data hanging around anyway, and it seems to work.

I also fixed the validation errors so they should go away now as well.

Thanks for reporting that and making it easy for me to repro!
