### ISSUE TITLE
No waves/wakes in build

### ISSUE THREAD

**Issue by Nimuecrypto** [huwb/crest-oceanrender#138]
Just a heads up... I am using Unity 2019.1.0a10  and rendering of waves/wakes no longer works in build.  Everything still works fine in the editor.  

Just to make sure I wasn't going crazy or had done something stupid, I also tested this with a fresh download of the most recent Crest release and ran the 'three boats' scene.

I have not tested this with an older Unity version so it's likely this is specific to the 2019 alpha and not something you need to worry about.  I just thought I'd report it anyway just in case.

![waveswakesbuild](https://user-images.githubusercontent.com/6428158/49589842-6d2dc100-f938-11e8-94c2-7dc978a5c233.png)

**Comment by Nimuecrypto** [comment]
Thanks for the compliment.  I suffer from delusions of inferiority so it's always nice to hear people say nice things.

Your hack worked.  I commented out the if/endif lines for the features I needed in the ShapeCombine shader and waves are working in builds again.  Thank you.

**Comment by huwb** [comment]
Fixed by the reference commit above.
