### ISSUE TITLE
Underwater shader fails when viewed from directly below.

### ISSUE THREAD

**Issue by Nimuecrypto** [huwb/crest-oceanrender#139]
Two posts in one day... this is a new record for me :)

I am having the issue in the the title - the underwater effect shader fails completely when viewed from beneath it at steep angles.  just from playing around it looks like it occurs at all angles between about 85 and 90 degrees.

![shaderfailure](https://user-images.githubusercontent.com/6428158/49601463-e4248300-f953-11e8-8ff0-abea57a77cea.png)

**Comment by huwb** [comment]
Thanks, looks like a bug. I'll let you know when i get around to looking at it. It might help give me a leg up if you could give me the camera transform (screenshot of the transform component of the cam would work) and perhaps the submarine transform as well. That's usually enough to repro these things.

**Comment by Nimuecrypto** [comment]
Sorry it took me so long, I've been busy this weekend.

Anyway that's easy enough.  In the video below the sub is at 0,0,0 and rotation 0,0,0.    Engines are off, so the only sub motion should be from surface interactions (my own buoyancy calculations combined with a modified version of your "align to normal" stuff).     

I have the orbit camera enabled and set as the viewpoint in the Ocean script.  The underwater curtain and meniscus objects are enabled on the orbit camera.  The first person camera is disabled, as are the underwater objects attached to it.

Here is the result:   https://www.youtube.com/watch?v=djyrnhfJKp0&feature=youtu.be

**Comment by huwb** [comment]
@Nimuecrypto the commit reference above should fix this. It's not perfect but should work "enough".
