### ISSUE TITLE
Dynamic Sea doesnt work on switch (still)

### ISSUE THREAD

**Issue by dizzy2003** [huwb/crest-oceanrender#144]
Grabbed latest from main after the fix went in
PC Stand Lone works fine

On switch the whole ocean moves up and down as a flat plane.

Will let you know when i get more info

![image](https://user-images.githubusercontent.com/15023384/49781317-fb051400-fd5d-11e8-9f9f-3c846e6f5266.png)

**Comment by huwb** [comment]
Huh!!

That looks like the kind of shenanigans that would happen if the lod sampling data was not set on the GPU for whatever reason - the values set in LodDataMgr.BindData() . Without these the ocean geometry may sample a single point in the texture (top image) or produce nans and not render at all (bottom image).

I'm not sure why this would not bind though (its clearly working for some things as shown in the buffers in the second image). Are there any errors or warnings in the log?

One way to investigate would be to run a GPU debugger to check the UVs used to sample the lod data textures. I typically use renderdoc after enabling the debugging pragma in ocean.shader. Have no idea what debugging looks like on switch!

**Comment by huwb** [comment]
Hi there, any news on this? Just checking if this is still open.

**Comment by dizzy2003** [comment]
I havent checked since. the original report, will get round to doing some
tests at some point soon..

**Comment by huwb** [comment]
I noticed while reproing #165 , that when the sample displacement code is throwing exceptions every frame it looks very similar to the above, so def worth checking the log.

**Comment by dizzy2003** [comment]
Spent today looking into this.

It seems like the Animated Waves/Gerstner Batch  shader is getting weird UV co ords for some reason (uv is 1,1 for every pixel)

to determine this I changed the Frag to do this

					float x = (i.uv.x)*6.0f;
					x = (int)x;
					x /= 6;

					return half4(x, 0, 0, 1);

Which should produce 6 nice bands of red and does on PC, but on switch its solid red.
Using the gpu debug tools I was able to debug the quad draw and could see the uv value coming in as 1,1 for any pixel I chose to debug.

But, the same debugger lets me see the quad mesh and its vertex attributes and through that view the uv's looked correct.

So something very weird is going on..  I poked about with the vertex shader for a bit changing which texcord was used for uv in the varyings struct, changing where the uv is set etc, nothing had any effect.

I was able to debug the vertex shader too and the code seemed to step through correctly except the uvs always read in as 1,1

**Comment by huwb** [comment]
Ha, sounds like a fun one.

I read the code for a while but did not have many ideas TBH.

I guess the last resort is assuming a bug with unity or the switch shader toolchain. It occurs to me that there is a color attribute being read and thats likely (1,1) by default. One quick test might be to just remove the color from the input struct. Maybe switch gets confused when there is no color attribute bound.

Anotehr test would be to study the disassembly for the vertex shader and make sure the layout matches the vertex layout. Its been a while since I've done this but if you stare at it long enough you should be able to see the input layout section at the top and it might be recognizable if something is wrong here.

**Comment by dizzy2003** [comment]
Removing Color fixed it, my guess is that its because the color type is half which doesnt make a lot of sense (being 1 component), 

changing it to half4  fixed it so the color comes through properly and the ocean system is working now.

looking nice :)

![image](https://user-images.githubusercontent.com/15023384/51355768-d726b200-1b03-11e9-8e49-d36cb4930abb.png)

**Comment by huwb** [comment]
I reckon you're right - i changed it to a half4 and pushed. Thats great, thanks!
