### ISSUE TITLE
Compatibility issues with 2018.3.0f2

### ISSUE THREAD

**Issue by konstantin890** [huwb/crest-oceanrender#146]
I'm using the latest version of Unity (2018.3.0f2) and Crest and I get the following error:
`InvalidOperationException: Cannot access the data as it is not available
UnityEngine.Rendering.AsyncGPUReadbackRequest.GetData[T] (System.Int32 layer) (at C:/buildslave/unity/build/Runtime/Export/AsyncGPUReadback.bindings.cs:26)
Crest.GPUReadbackBase`1[LodDataType].ProcessArrivedRequests (Crest.GPUReadbackBase`1+PerLodData[LodDataType] lodData) (at Assets/Scenes/Water/Crest/Scripts/GPUReadback/GPUReadbackBase.cs:263)
Crest.GPUReadbackBase`1[LodDataType].ProcessRequestsInternal (System.Boolean runningFromUpdate) (at Assets/Scenes/Water/Crest/Scripts/GPUReadback/GPUReadbackBase.cs:165)
Crest.GPUReadbackBase`1[LodDataType].Update () (at Assets/Scenes/Water/Crest/Scripts/GPUReadback/GPUReadbackBase.cs:83)`
The water seems to render normally, but this error is spammed between 5 sec. or so. The error didn't appear in 2018.2.x

**Comment by huwb** [comment]
Well thats novel :). I could not repro here, but after looking at the code and docs there was case where errors could slip through, so i fixed that up in the above referenced commit. Also upgraded the project. Could you give it a try on latest? Thanks for reporting.

**Comment by konstantin890** [comment]
I will check if it works in a few hours. Thanks for the fast response!

**Comment by konstantin890** [comment]
I confirm that the issue is fixed now with your fix. Thank you for fixing this that fast!
