### ISSUE TITLE
Small update to readme

### ISSUE THREAD

**Issue by simonduf** [huwb/crest-oceanrender#148]
Hi!

I want to say that the result is incredible!

I just want to point out the small difficulties that I encountered importing the project when following the instructions of the readme:

- There is a setup regarding the layers that is missing from the "setup" section. I added  a "Terrain" layer and it worked. The error message was clear, but I am not sure if there is any dependency of details missing

- I tried Unity 2018.2, 2017.3 before trying with 2018.3 where everything worked. The errors were minors and could be fixed but it would be nice for 

- There is a missing script on the camera in the example scene

I am aiming to test in VR on Monday, but so far I am really impressed!

Thank you very much!

**Comment by huwb** [comment]
Thanks @simonduf! Does the commit referenced above do the trick?

The prereqs section addresses all of the above points, hopefully this is a good solution.

**Comment by simonduf** [comment]
Yes it does! I missed the version number in the header.
I try to always give the feedback on "first time user issues" because I can only do it once!

You are doing that only in your free time?

**Comment by huwb** [comment]
I know what you mean :) please keep any improvement feedback like that coming.

I've heard good things about how the underwater looks in VR. Hope i will witness this myself one day :). Crest has been changing at a pretty high velocity lately and i havent been testing in VR so let me know if it works or not..

So far yes. It started as an R&D playground and then some nice people started using it for their projects and giving me improvement suggestions and it all kinda snowballed..
