### ISSUE TITLE
Caustics dont show above water in  unity 2018.3

### ISSUE THREAD

**Issue by VizzzU** [huwb/crest-oceanrender#149]
I have managed to make them work using your last commit before the cleanup 2 days ago . (using the old oceanEmission shader after the cleanup 21 days ago )

**Comment by huwb** [comment]
D'oh - thats my bad, sorry! Fixed on latest on master. Thanks for reporting 👍

**Comment by VizzzU** [comment]
Regarding how amazing your work is , it is a drop of water in the ocean ! Fantastic job , great support ,  and billions of thanks to share it with us , it would take me 10 lives to approach the half of your results .
Thanks a lot , keep hard work .

**Comment by huwb** [comment]
Thanks @VizzzU - that's very kind!
