### ISSUE TITLE
Black Sea In Reflection Probe

### ISSUE THREAD

**Issue by GeorgeDziov** [huwb/crest-oceanrender#15]
I really hate posting issues but I just noticed ocean is black in objects with PBR materials. It's no biggie for me but I thought I must notify developer about this. I also tried changing ocean material properties but alas no luck.

![2018-05-22 18 23 54](https://user-images.githubusercontent.com/15368122/40376065-144ac67e-5df6-11e8-9099-0d609bfa008f.png)

EDIT: Zero fesnel kinda fixes the ocean but it's zero fresnel so... nope, scratch that.

**Comment by huwb** [comment]
Thanks for notifying me of this. Thats quite a bug!

I can repro this on my end as well. I'm pretty sure its to do with the fact that I'm using _LightColor0 directly in the shader, which seems to be not ok for reflection probes. I have another issue also related to lighting so I can look at both at the same time. I'll post back when i have news. Thanks for raising!

**Comment by huwb** [comment]
It looks like Dizzy & Midda found the issue while looking into another bug. It looks fine to me now! Closing but let me know if you still have issues. Thanks!

**Comment by GeorgeDziov** [comment]
That's insane, thanks a ton! Works like Swiss Clock!
