### ISSUE TITLE
Foam Visibility Distance and threshold?

### ISSUE THREAD

**Issue by superjayman** [huwb/crest-oceanrender#153]
Is there a way to extend the visibility distance of foam?, seem to cut out too early, also I can't see a foam threshold, I like to generate more foam when ocean is relatively calm, at the moment there is no control. Cheers.

**Comment by huwb** [comment]
The foam should extend as far as your lods. If you jack up the wave sims you should see foam appear.

There are settings for the foam sim, i'll point you to the docs and you can tell me if they make sense or not :) https://github.com/huwb/crest-oceanrender/blob/master/TECHNOLOGY.md
