### ISSUE TITLE
Shoreline fade? Taming Controls?

### ISSUE THREAD

**Issue by superjayman** [huwb/crest-oceanrender#159]
Is there any controls to Fade the shoreline?, seems to cutoff too sharply. Also, is it possible to control how tame (Calm) the water is in shallow areas?(eg. I want bigger waves in deeper ocean, calm near the shallow) Cheers..

**Comment by huwb** [comment]
I've added a param for controlling how much waves are attenuated in shallow water - its in the animated wave settings. I've added notes in the Animated Waves section of the docs: https://github.com/huwb/crest-oceanrender/blob/master/TECHNOLOGY.md

The foam fade very close to the shore is configurable on the ocean material using the *Shoreline Foam Min Depth* parameter.
