### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by baranpirincal** [huwb/crest-oceanrender#16]
Hey! I can contribute on your project in field of graphic. If you need a logo design we can talk about design  decisions and I can put here my first experiments. I can show my portfolio if you interested. My main aim is make my portfolio better with supporting open source projects. I am waiting your feedback, have a nice day!

**Comment by huwb** [comment]
Your support would be fantastic! A logo would make a huge difference <3. Thanks for reaching out! I really like your portfolio on Behance btw - impressive work.

How should we proceed? And would you prefer email communication or here? I'm happy with either.

**Comment by baranpirincal** [comment]
@huwb Doesn't matter for me. We can move on in here.

Do you have an any idea or request about design decisions? For example; Do you want me to use letters of "CREST" on design or only "C" letter? Or is it must contain drawing and shape?

**Comment by huwb** [comment]
Cool, sounds good.

I'm not sure about just using C vs CREST. My initial feeling is the whole word I think.

I like the idea of some kind of drawing/shape. I think a text+image combination could work well. It might be useful if the image could be used separately and be recognizable - ideally something that could go to an icon form..? However if you had any ideas for text-only.

General personal preference - I usually vote for simplicity/minimalism. These are hugely core to crest, I spent 90% of the dev time so far rewriting/refactoring to simplify and optimise and make the system more elegant. 

Key elements of crest - expressive shape and motion control, dynamic simulation, quality at all levels (from code to final render), 100% smooth level of detail, high performance.

Final thought - you might be interested in skimming through the siggraph course notes, if you haven't already. i dont think theres anything of direct use but it might give a feeling for some of the tech parts that make up crest. http://advances.realtimerendering.com/s2017/Ocean_SIGGRAPH17_Final.pptx . just thought i'd mention it in case its useful.

Hope that was not too little/too much :)? Let me know!

**Comment by baranpirincal** [comment]
@huwb Hey, firstly you're welcome. Sorry for delay, I was too busy last week. I read all of the informations you gave, also I examined your presentation about the project. I will make my first experiments as soon as possible, have a nice day!

**Comment by baranpirincal** [comment]
@huwb Hey again, I just made my first experiment but it is not finished. I will change something, I just want to take feedback from you. Is this style fine with you or not? I hope you like it, have a nice day! :)

- I made every line smooth as you did on project and I wanted to show sea and beach - I am totally open any suggestion or idea from you! :)

![crest](https://user-images.githubusercontent.com/37786733/41066991-a05f7054-69ec-11e8-994f-37f925c6727d.jpg)

**Comment by huwb** [comment]
Wow - thats fantastic. I love the style! Making the lines smooth is a great idea and is a meaningful connection to crest. Crest has not featured a beach up until now, but i've needed a good excuse to add one so I'm all for it!

I don't have a huge amount of ideas, but I'll give you a couple of crude thoughts about what you've posted above. If you decide to move away from this style or these elements, thats fine too, ignore my notes in that case!

1. Out of the different layouts, I think I like the layout which you used for the tests with the text - sun in top left.
2. I think I like the white lines rather than darker lines (as in the middle row, left side). I spent a fair bit of time recently working on light reflecting off waves, light passing through waves, and foam on top of waves ( [recent screenshot link](https://user-images.githubusercontent.com/939901/41068500-a72efa2c-69e1-11e8-87f6-f7007dcc0282.png) ), so the lighter lines resonate with me.

Thanks Baran :)

**Comment by Midda-C** [comment]
For what it's worth, I agree with @huwb regarding the lighter coloured lines on the second row. :)

**Comment by baranpirincal** [comment]
@huwb @Midda-C 

Hey again;

I finished all arrangements and created pull-request.

I uploaded high quality .PNG and editable .SVG versions of logo design. (logo-mark&logo-type)

I hope you like it! :)

![crest first page](https://user-images.githubusercontent.com/37786733/41079089-e2b2a412-6a28-11e8-8686-e2ad90ff8282.jpg)

Best Regards

Baran Pirinçal

**Comment by huwb** [comment]
Yep i think that looks awesome, thanks Baran! I'll absorb the pull request and sort out the bits over the next couple of days or on the weekend. I'll post back when done.

**Comment by baranpirincal** [comment]
@huwb 

You're welcome.

I am very happy that you are satisfied!

**Comment by huwb** [comment]
I added the logo to the readme. I spent a bunch of time juggling words/headings/images, trying to reduce conflicting elements. I settled on this eventually: https://github.com/huwb/crest-oceanrender/blob/master/README.md . If you have any feedback let me know.

Otherwise, thanks again!

**Comment by huwb** [comment]
@baranpirincal 
in 1728555033a0faaccff0fe2ac039c0105f24495f i added support for rendering alpha on the water surface for gameplay/FX reasons and such, also makes for interesting branding opportunities :)

![image](https://user-images.githubusercontent.com/939901/41582829-8f583e50-739a-11e8-9e70-a737978844b3.png)

**Comment by baranpirincal** [comment]
@huwb

You made it! It looks so cool! :) 

Really , I am so interested in with rendering softwares but I did not try to do something yet. If I go through  in future , definitely crest will be on my mind. It looks so smooth and realistic. I will use it for making mock-up design at the first chance :)

**Comment by huwb** [comment]
That would be fantastic. If there's anything i can do to support you, let me know!
