### ISSUE TITLE
Wave Fx do not work due to the addition of  _samplingData 

### ISSUE THREAD

**Issue by VizzzU** [huwb/crest-oceanrender#161]
After the addition of _samplingData's parameter in oceanRenderer.cs the wave peak fx do not work anymore cause it miss the value in oceanTrackSurface.cs

I also would like to know what would be your approach to trigger particles on collision with the ocean plane , relative to the celerity of the object or to its weight . Forex a rock falling in water or a boat bouncing on waves .
And lastely i would like to know if you plan to merge the river branch with the master one .

Regards , and thanx again for your amazing work . And again sorry for my english .

VizzzU

**Comment by huwb** [comment]
Hi there!

1:  Ok ill take a look thanks.

2: I think a good approach would be to add particle emitter points and measure relative difference in velocity of the boat vs the water surface. I think this would also work for cliffs/shorelines etc. But i havent tried this. I don't know any public references/reading material for this but its worth googling around (and feel free to post back if you find something you can share).

3: Rivers - it needs more work. The fundamental problem is that the ocean depths are measured relative to a fixed sea level and can not currently account for the river bed being at arbitrary heights. I couldnt think of a very easy way to solve this, it probably needs not just the sea floor depth but also a water height depth that is sea level by default but can go above/below for rivers. In general I think rivers are quite a cool direction, but i dont have immediate plans to pick it up. If it does move forward i'll try to remember to tag you into any update commits.

**Comment by VizzzU** [comment]
Wow , amazing response time ! I have bought some assets wich are very less supported , THANKS A BILLION . 
So i will share my experiments about splashes as soon as i will obtain suitable results with this and with the wave fx . Tweaking a bit your waveFx code and adding some visual particle effects really enhance the look of the wave peak . ^^
For the rivers i just struggle to merge the moving caustics part when you are underwater or under river (miss the _flow parameter) . Visually i have obtained good results (cheated) by connecting your river to a cascade build with an out of the box river system (R.A.M) . Lot of foam , splashes and bubble "et voila " ! They have a method to merge rivers with flat planes but i am still trying to understand it . 

We are not all smart as you !

Kindests regards .

**Comment by holdingjason** [comment]
Hey @VizzzU are you using the wave peak fx branch?  Also this is something we keep trying to work on but get pulled into other things so would love to be kept in the loop on how it goes.

**Comment by holdingjason** [comment]
@VizzzU  I guess is what your doing related to this thread.

https://github.com/huwb/crest-oceanrender/issues/93

**Comment by VizzzU** [comment]
Hi holdingjason .
 Yes i am using the wave peak branch in combination with the master's one . My goal for now is to trigger realistic particles on collision , on wave top , on shore , etc ... 
With the lasts working versions i have managed to get some good results using animated sprite sheets and tweaking a bit the parameters & the scripts .
I think that lot of peoples are interested by this kind of features , i will share some pics & experiments when i will be satisfied with the results .
Feel free to do it too or to discuss about the better solutions !

**Comment by holdingjason** [comment]
@VizzzU Will do and thanks for playing with this.  I agree it will be very useful for everyone.

**Comment by VizzzU** [comment]
@holdingjason , i have found tons off usefull things reading those papers .
https://www.jstage.jst.go.jp/article/ipsjjip/25/0/25_486/_pdf
http://matthias-mueller-fischer.ch/publications/hfFluid.pdf

For now my guesses are  that there are only two possible particle effect : a splash (vertical) or a breaking wave (horizontal) and that the particle emitter should be a rectangular plane  triggered  on top of the waves when the  values are changing quickly .

**Comment by huwb** [comment]
Thanks for the posts.

In the commit referenced above i merged in latest from master to feature/wave-peak-fx and did a few fixes.

Keep us posted with updates @VizzzU!
