### ISSUE TITLE
Providing SimSettingsAnimatedWaves asset will throw errors in the next loaded level

### ISSUE THREAD

**Issue by michaellievens** [huwb/crest-oceanrender#165]
Hi,

If you create a **SimSettingsAnimatedWaves** in your asset folder and link it to your **OceanRenderer** _Simulation Parameters_ then each time you hit R to reload one of your example the reloaded scene will throw errors : 

> InvalidOperationException: The NativeArray has been deallocated, it is not allowed to access it

I know this scriptable object is created at runtime so you don't need to provide one. I'm just used to provide and personalize each visible references in the editor just in case I need to update packages or remove examples.

So I don't know if this is the expected behavior and should be rather provided by code or anything but if it can prevent others from looking for a solution : _**all the better**_ 😃 

_Sorry if it was already mentioned or documented, I searched but didn't find anything related._

By the way, crest is very impressive ! 
« Félicitation » and thank you for open sourcing it 👍

**Comment by huwb** [comment]
Thanks for reporting! Should be sorted in the above commit.
