### ISSUE TITLE
Underwater view disapears when camera 'x' angle > 54

### ISSUE THREAD

**Issue by VizzzU** [huwb/crest-oceanrender#167]
Hello !

I've just noticed that the underwater effect "disapears" if you are underwater and if you look below you with an x angle > 54. 
Maybe my bad , IDK , i try to investigate . 

Cheers . Hope i could help soon !

Keep hard work ^^ , your ocean is amazingly beautifull . Vizzzu

**Comment by huwb** [comment]
Thanks, when i next get some time ill take a look at this and the other open underwater issue.

**Comment by huwb** [comment]
Hopefully the commit referenced above fixes this. Thanks for reporting!

**Comment by VizzzU** [comment]
wow you are a f**** genius . Or a bot .
I am still struggle to understand how everything works !
Billion of thanks , every fix points us to another part of your code . It is a fantastic way to learn .

**Comment by ibbybn** [comment]
Works here. :) Also had the same issue looking up at that angle and that's also fixed it seems. Thx!
