### ISSUE TITLE
BoatProbes broken in build

### ISSUE THREAD

**Issue by Spirtix** [huwb/crest-oceanrender#170]
When using BoatProbes from example content the boat disappears as soon as it touches water surface. The issue is only present in build, it works fine in Editor.

**Comment by Draydak** [comment]
I was just doing a test build myself and was starting to wonder what was going on and debug the situation
But if I'm not alone... looks like boat probes is culprit as only boats are not showing
just need to find out why now

**Comment by huwb** [comment]
Thanks guys. It would be interesting if the player log has exceptions in it - for example if a calculation is trying to assign NaN to a transform that would probably make everything blow up, but it would report an exception to the log.

**Comment by Draydak** [comment]
I'm probably missing something obvious but
I have done a debug build of the "threeBoats" scene, linked it to the profiler and run it
Just seeing the 3 "boatAlignNormal" and neither of the two boats using probes.
No errors popping up, I also switched logging to Full before running this
Is there something else I need to switch on to see the possible NaN's or am I just looking in wrong place?
Or maybe they are not happening?

**Comment by Draydak** [comment]
yea it's a problem with the "boatProbes" script
but I'm just not seeing any errors... or any boats that have it attached when not run in editor

**Comment by Spirtix** [comment]
When you drop a boat from height, it will fall until it hits the water and then disappear, so the boat is definitely in the scene.

**Comment by huwb** [comment]
You got it - nice one. I don't have access to my computer right now but when I do I'll get the fix pushed and will report back

**Comment by Spirtix** [comment]
It is used only here: 
`RB.AddForceAtPosition(archimedesForceMagnitude * distance * Vector3.up * point._weight * _forceMultiplier / _totalWeight, transformedPoint);`
When in player the variable _totalWeight is not calculated, so it makes the whole line null.
Just call the method in Start and keep if UNITY_EDITOR in FixedUpdate. I guess it requires some performance to recalculate it every frame and it's not needed in player.

I can make a pull request.

**Comment by Draydak** [comment]
dropped it into start and yea that's working perfectly!

**Comment by huwb** [comment]
Pushed, thanks for reporting and then diagnosing the issue :).
