### ISSUE TITLE
Boat with individual rigidbodys as children

### ISSUE THREAD

**Issue by NielsOsnabrugge** [huwb/crest-oceanrender#171]
Hi there, 
I am not sure whether this is an actual bug or something wrong in my scene but whenever i put kinematic rigidbodies on the boat the "Boat align normal" component makes the ship rotate in all kinds of weird directions 

I uploaded a gif below for some more clarification
![x9t7jlsh6a](https://user-images.githubusercontent.com/25740928/51185998-d9f18f00-18d8-11e9-8930-8b9eee548270.gif)

Whenever i remove the rigidbodies from the ships children everything works perfectly

**Comment by NielsOsnabrugge** [comment]
why didn't i think of that.... Instead of moving them all around in the hopes they dont collide i could have simply let them ignore eachother. Thx alot srsly!

**Comment by holdingjason** [comment]
Not a problem.  Took me awhile to figure that stuff out as well so glad I could help.

**Comment by NielsOsnabrugge** [comment]
issue has been fixed and can be closed.

Thx again for your help
