### ISSUE TITLE
Planar Reflections Broken?

### ISSUE THREAD

**Issue by superjayman** [huwb/crest-oceanrender#172]
In the latest master, planar reflections no longer distort with the waves? they look like slapped on the screen.  You can test it with main crest example just enable planar reflections, now changing wave height does not make any difference on the reflections at all. 

p.s. This was working perfectly from a build a few weeks ago. I can provide screen shots if you like. Not sure what could have changed.

**Comment by huwb** [comment]
Thanks for reporting @superjayman .

@moosichu i did a quick bisect and it seems it was introduced with this 039699bcb31e51d99445bfebaafd7c7fcd67ff34, do you mind giving me a hand figuring out what the regression is and fixing it?

I had a quick look at the code and although there are changes to PlanarReflection() they dont look like culprits to me so maybe it is something outside?

To test with planar reflections assign the OceanPlanarReflections script to the camera and enabling Planar Reflection on the material. You will get warnings if something is not set up correctly.

**Comment by moosichu** [comment]
ok, I will have a look

**Comment by superjayman** [comment]
just wondering any progress on this? Cheers

**Comment by moosichu** [comment]
@superjayman See PR #174

**Comment by superjayman** [comment]
Thanks that works, why is the fix not part of the master branch? Cheers again

**Comment by moosichu** [comment]
Now it is @superjayman 😀
