### ISSUE TITLE
Camera Looking Straight Down Above Water Issue?

### ISSUE THREAD

**Issue by superjayman** [huwb/crest-oceanrender#178]
I have noticed when the you look straight down (I'm testing in VR) and Camera is above the water, there is a strange masking issue with objects on the water where the caustics show thru on them. Not sure what's causing it. Any Ideas?

**Comment by huwb** [comment]
Hm its hard to say. Is it possible to get a screenshot?

**Comment by superjayman** [comment]
Sorry been really busy, will put screenshot today, it's hard to tell what's causing it but it's very annoying in VR when you look straight down.

**Comment by huwb** [comment]
I'll close due to inactivity, but if you do manage to get a screenshot or video i'll reopen.

There is another issue related to looking at water in vr - #206 - but I believe that one is a LWRP-specific issue.
