### ISSUE TITLE
Low Lod Counts cause weird waves

### ISSUE THREAD

**Issue by dizzy2003** [huwb/crest-oceanrender#179]
![image](https://user-images.githubusercontent.com/15023384/51963355-0566a300-24af-11e9-9d37-84b569e6d0c9.png)

You can see the lines across the textures, this was with lod count set to 4
as you raise the camera (in the main test scene) the waves go correct then go wrong again

**Comment by huwb** [comment]
Thanks for reporting this. Was a good old fashion array index out of bounds in the gerstner shader due to an error in the code.
