### ISSUE TITLE
Question on underwater surface and skirt settings.

### ISSUE THREAD

**Issue by holdingjason** [huwb/crest-oceanrender#182]
Update.  Found the answers I think here.  This is what happens when you wait to long to implement something, your forget all former discussions.  Guess you can close this if this is still all correct.

https://github.com/huwb/crest-oceanrender/pull/110

Here is a shot where you can see the issue.  Want to have a nice seamless blend off in the distance between the underwater skirt and the ocean surface.  So the question is should I be doing what I am doing in image #2 to fix the issue or is there a better different etc way to do this?  thanks

image #1
![image](https://user-images.githubusercontent.com/42001313/52180104-edd13800-2796-11e9-8348-14b5dbe583b9.png)

image #2
Here is what it looks like if I turn off Shadowing under Scattering and also Directional Scattering.

![image](https://user-images.githubusercontent.com/42001313/52180123-16f1c880-2797-11e9-84b1-5094ba55d6ab.png)

**Comment by holdingjason** [comment]
Oh and changing these values during runtime is not being picked up.  My guess is they are cached.  I think there is a way to tell the ocean renderer shader to update so need to look at that.

**Comment by huwb** [comment]
Theres a checkbox for copying params from ocean material to curtain material, it's on the under water effect script, it's probably on by default so the parameter changes won't get picked up.

Its probably a bug with one of those features that you called out above, but I don't know off the top of my head. I'll take a look next time I'm working on it.

**Comment by holdingjason** [comment]
hmm yeah seeing i did have  copy params each frame on as well and was getting above so yeah must not be working correct.  I will dig into it.

**Comment by holdingjason** [comment]
Yeah something is up.  Scattering and Direcitonal scattering are both not copying over all the effects correctly so that you get color differences that kill the blending.

**Comment by holdingjason** [comment]
So here is a shot of what I want.  I can get this but only if I manually disable (before runtime) Sub Surface Scattering and Shadows.  Anytime I leave those on I cannot get the blending to happen, the colors or some settings do not come over to the skirt completely.

![ocean skirt](https://user-images.githubusercontent.com/42001313/52183158-e2dbcf00-27b9-11e9-9f0f-5c8c64e6c87b.gif)

**Comment by holdingjason** [comment]
Ok so the issue is really with the shadow diffuse colour under shadowing.  That effects how the underwater surface shows up and if its set to a color that is fairly different then the diffuse and or directional scattering colors then the surface will show up harshly causing it to stand out.  Turning off shadowing while underwater using DisableKeyword fixes that.  Not sure if this is an issue or not guess it depends on if we want to normally keep shadows on underwater.  My guess is its not really an issue since I am not sure what would "match" up here.   Perhaps its just an incompatibilty with underwater and we should turn off the shadow diffuce colour while underwater or something.

oceanRenderer.OceanMaterial.DisableKeyword("_SHADOWS_ON");

**Comment by holdingjason** [comment]
Ok some more info as well.  Seems no matter what I cannot get a perfect match without tweaking the following.

Basically turn off shadows as stated.  Then depending on the color of diffuse you must also mess with  directional scattering color and base multiplier.   Each time you change one you have to mess with the other until you get a nice blend.  My guess is the transparent values also come into play here as well so perhaps its not an issue just something that you have to mess with depending on your specific settings.

I can pass along my current values if that is helpful.

**Comment by huwb** [comment]
I'll let you know when I get the headspace to five into this. Apologies for delays, I have a bunch going on in and out of work atm.

**Comment by holdingjason** [comment]
@huwb No sweat.  Easy enough to work around at this point.

**Comment by MojaveMoore** [comment]
I'm working with something similar in my game, but I'm incorporating Map magic as well. My only issue is no underwater fog.

**Comment by holdingjason** [comment]
@MojaveMoore Well not sure I fully understand perhaps but I think the idea is that the skirt works as your underwater fog and you let that more or less handle it.  I added some additional fog on top of that (unity normal fog) and that makes a nice blending for further out objects.  But basically fog is not suppose to be needed in this scenario.  @huwb sorry if I got that wrong.

**Comment by huwb** [comment]
Thats correct @holdingjason 

This is finally very close to the top of my list - hope to get this sorted soon.

**Comment by huwb** [comment]
I'm pleased to report i fixed two issues that broke continuity in shading between the surface and the curtain. @holdingjason if you get a chance could you please try disabling your workaround and trying with the latest? Thanks!

**Comment by holdingjason** [comment]
Sure will.  Getting the changes and will try them out.

**Comment by holdingjason** [comment]
It is better but not perfect yet.  So if I turn off all 4 options this is what I see.

![image](https://user-images.githubusercontent.com/42001313/54872396-6e1c1e80-4d80-11e9-830e-6efd77437582.png)

**Comment by huwb** [comment]
This is resolved, thanks a bunch @holdingjason

**Comment by holdingjason** [comment]
Great job.
