### ISSUE TITLE
Support for Unity Package Manager

### ISSUE THREAD

**Issue by JJarvis89** [huwb/crest-oceanrender#184]
I'm not sure whether this has been requested yet. It would be great if you could add support for Unity Package Manager. Similar to: https://github.com/mob-sakai/SoftMaskForUGUI/tree/upm#install

**Comment by huwb** [comment]
Oh thats cool - didnt realise it could link to git like that, nice.

Thanks for the info/suggestion and I'll report back if i get onto this, may not be in the very short term though.

**Comment by huwb** [comment]
The problems that make this difficult for me are nontechnical - i'm making a LWRP version to put on the store and the store still uses unitypackages (for now), and i dont want to have completely different structures for different versions. Also i hear the new packages don't play nicely with Unity Collab currently and there's probably other things that need to mature.

In any case I will likely move stuff to the package manager when the asset store moves over to it properly. I'll post here with any update.
