### ISSUE TITLE
Whirlpool Doesn't exist when built

### ISSUE THREAD

**Issue by LiamColeE** [huwb/crest-oceanrender#185]
When i build my project the Whirlpool no longer exists in the scene. let me know what information would be helpful.
Thanks,
LiamColeE

**Comment by LiamColeE** [comment]
i didn't get much sleep last night and totally forgot to check the error logs form the build. i'm gonna go look at everything and make sure it didn't tell me why int there. ill comment any findings i have

**Comment by LiamColeE** [comment]
had some weird errors with HDRP, fixed them and still have the same issue. not sure whats happening. it dissapears on the example scene too.

**Comment by huwb** [comment]
Thanks for reporting, some shaders were not in 'Resources' folders so they werent included in standalone builds by default. Should be fixed on latest on master.
