### ISSUE TITLE
Water decal projection with waves?

### ISSUE THREAD

**Issue by StickeydM** [huwb/crest-oceanrender#186]
Hello. I'm trying to project texture on water to achieve stylized look like here:
![green city nw](https://user-images.githubusercontent.com/12021941/52510327-2ee8a280-2c04-11e9-8664-4bbf1905331e.jpg)
The problem is, to achieve these "artist strokes" feel I need to use texture which is projected on top of the water surface. RenderAlphaOnSurface does a similar thing, but the problem with it is if I make texture less transparent the water looks more transparent. I'm not super experienced with graphics so don't know how to explain it properly, but it just doesn't work with water material properly. It overrides it. 

Ultimate Water System allows such kind of water projection. With it I can achieve something like this: https://gyazo.com/86f93ee53ef44cc05500b1de675100ff
Here's what I achieve with crest with the same texture:
https://gyazo.com/16d1f78051c87931e85d743b6b552b6e

Ultimate Water System really lacks other great features you have like dynamic waves with proper physics. We want to use them. UWS has dynamic waves but they are not interacting physically with objects and that's a problem which Crest doesn't have. UWS also is deprecated so hard to continue working with it.

Is there a way to achieve this kind of visual look with Crest? Or at least would it be possible to even develop water projection for it? Super important for the project and possibly our choice of water system depends on it.

Thank you in advance

**Comment by huwb** [comment]
That looks awesome.

RenderAlphaOnSurface does indeed do a similar thing. Maybe you are looking for different blending modes - your result looks perhaps like multiply blend.

I've just pushed params to the material which allow you to experiment with different blend settings. You can achieve multiply blending with these settings:

![image](https://user-images.githubusercontent.com/939901/52532467-aa8a4280-2d1d-11e9-9f57-4f8caa15db60.png)

**Comment by StickeydM** [comment]
That's much better! Still some problems though

https://gyazo.com/6827cd45823923399d494183867a7d3f

Water projection makes the island change the color as well. Would it be possible to make it so it doesn't impact island? Same about foam. It looks a bit blue/green. Any way to make it look white like it should be?

**Comment by huwb** [comment]
Hm the island is a problem with how the depth offset is applied to keep it above the water (would also be a problem with projectors, to some extent). This offset can be played around with in OceanSurfaceAlpha.shader (search Offset).

From what you're saying you want it to affect only the base colour of the ocean. You could try multiplying the result of ScatterColour() (the colour of light scattered out of the water volume towards the viewer) with your own texture that you could sample there.

If you want to achieve something super stylized like that you'll want to roll up your sleeves and go deep in the (shader) code and do a lot of experimentation. It sounds like you're at the beginning of your journey with graphics, i'd recommend following tutorials to get comfortable with shader coding and you probably want to do some toon shading stuff or similar as that may be useful.

I'm not able to provide general dev services as this is currently a hobby thing, and my hobby time is decreasing over time. However I do my best to stay on top of bugs, and can provide hints/pointers here and there if i have them. I'm mentioning this upfront as it sounds like you're still settling on an ocean system - if you need one with a guaranteed level of support crest may not be the best choice.

**Comment by StickeydM** [comment]
It still seems that your water system is much better choice for me than Ultimate Water System. I actually have two options, this one and UWS and UWS doesn't have support at all. It has its own problems as well. I'm not a shader programmer but I have a friend who can help me with that, so maybe I should ask him. He doesn't have much time though. 

Would it be possible for you to estimate at least approximately how much work should be done with shader to approach stylization like I need? I have to understand if the time my friend has will be enough... I can show you some more concepts we have, if you need. We have it on our Instagram page - https://www.instagram.com/heartstep_studios/

Also, if you could, could you provide a hint where to dig to make my texture also working with dynamic waves? The problem I'm facing with whirlpool now is that the texture is apllied on top of it, it doesn't actually taking in account that the whirlpool is bending

Here it is without texture - https://gyazo.com/d699a979d5102b3d60ff62102dccb00a

And here it is with texture - https://gyazo.com/2a44a0ca6ed2cfa8afd8ee966af5b4ba

The whirlpool and its bending is almost not seen because the texture is applied on top of it like there is no bending. It doesn't bend the texture, if you could say so.

I understand that you have not much time, but really your system is the hope that I was looking for. We facing problems with our old system as well because it's super hard to stylize foam here and there are various bugs we can't fix. I can ask guy a bit more experienced to help with shaders but he still will need some hints here and there. Would it be okay for you? 

Thank you.

**Comment by StickeydM** [comment]
Also, if you could, could you provide a hint where to dig to make my texture also working with dynamic waves? The problem I'm facing with whirlpool now is that the texture is apllied on top of it, it doesn't actually taking in account that the whirlpool is bending

Here it is without texture - https://gyazo.com/d699a979d5102b3d60ff62102dccb00a

And here it is with texture - https://gyazo.com/2a44a0ca6ed2cfa8afd8ee966af5b4ba

The whirlpool and its bending is almost not seen because the texture is applied on top of it like there is no bending. It doesn't bend the texture, if you could say so.

As I understand texture doesn't work on waves naturally as well. It just places itself on top of everything. The thing in UWS is that it works even on waves. Any way to fix it?

I'm starting to suspect that this problem appears because of mesh. We actually tried to stylize SUIMONO before with the same method, but developer said that the problem with mesh water is that the projection is flat. And in Ultimate Water System water is done as image effects, there is no mesh there. Any chances to overcome that, if that's so?

In UWS it looks like this https://gyazo.com/380307a1374b0186632193538136b634

If there are no chances to overcome this I will probably consider staying on UWS.

**Comment by huwb** [comment]
Its hard to estimate when the approach is not yet known. Maybe you can get pretty far by multiplying in a texture like you've done. Perhaps this texture could be animated over time and this might give a good effect. I don't have ideas for similar work to draw from but ill think about it (Oskar Stålberg's work comes to mind as soft & stylized and is probably worth checking out, but its not really the same stuff. Oh alex evans' siggraph talk about dreams might be an interesting reference in painterly rendering styles.). I don't know how to estimate in this circumstance. Perhaps between 2 weeks and 3 months for something working, up to 1 year to do really deep work and match reference closely, but these are just complete guesses based on extremely incomplete information. i recommend talking it through with your friend and figuring out a solution together.

yes i can provide hints for specific questions or problems. i'll typically give a pointer where to look in teh code. for example:

if you sample your stylized texture in the ocean shader in ScatterColour as suggested above, you could also apply flow to it, which will give the horizontal motion thats used on whirlpools, which i believe will give you the 'bend' you're looking for. search the shader code for 'flow'.

from there i'll need you guys to take over - i assume you are happy to search the shader code, experiment with ocean material features and look how they are implemented, read through the code yourself and potentially experiment turning bits of code on and off to see the effect.

i don't know what approach you should use, but i've given hints about how you might begin experimenting, and you'll need to do the experimentation. if you speak to your friend and come up with a technical plan that you guys believe in and want to send it to me, i should be able to put time aside to read it and give feedback. sorry i can't help more!

**Comment by huwb** [comment]
random idea occurred to me - maybe you should render the ocean as a load of paint strokes - render each stroke as separate geometry, and sample the water at the center of each stroke to give the stroke colour. you could do this by writing a new version of ocean.shader with a bunch of modifications to work for individual strokes (i dont know what they would be without trying it).

you could perhaps align the stroke to the flow, which made me think about this: https://www.youtube.com/watch?v=Bm9YvhBUmc4

**Comment by StickeydM** [comment]
Interesting! Thanks for your interest, help and ideas

Your idea about rendering the ocean as a load of paint strokes seems even harder than texture but will consider it for sure

About bending. You said it's possible to achieve horizontal bending by applying flow to sample texture, but what about vertical? Can we achieve something like this(from UWS)
![bending](https://user-images.githubusercontent.com/12021941/52542965-e53bbb80-2dad-11e9-90cc-5a0f8405aff0.png)

I use displacement with negative amplitude(it's possible to do the same with your whirlpool actually) and the texture bends itself to this high wave. Would your method with flow make that possible as well?

**Comment by huwb** [comment]
The answer to all of the above should be yes, but you'll need to experiment and try it out to know for sure.

**Comment by huwb** [comment]
Saw a tweet from heartstep and thought of this. Did you end up going with crest in the end or sticking with what you had? Just curious.

**Comment by StickeydM** [comment]
I ended up sticking with UWS. I couldn't find a way to apply texture properly like in UWS. The sad thing is that I'm thinking to switch to SRP for supporting VFX Graph, but I can't do it on UWS. And it's deprecated so no support from developers.

Thinking about switching to crest again.. Is there any chance I can achieve something like I achieved on UWS with crest?
