### ISSUE TITLE
foam LOD / Distance

### ISSUE THREAD

**Issue by julled** [huwb/crest-oceanrender#187]
Hey there! i am quite new to unity so please dont blame me if i might have overseen some basic things...
I try to use your oceanrenderer to discover boats cruising through the sea from high altitudes from a plane. To recognize the boats more easy,  the foam from the back of the boats should be visible for the observer. 

I got problems to add foam which is visible from these high altitudes. i was checking the manual (https://github.com/huwb/crest-oceanrender/blob/master/TECHNOLOGY.md) but i cant get the parameter to controll the dissapearing of the foam over the distance to the ocean. I was trying to use different Detail/LOD settings at the ocean object but i did not have success yet.
Or is there a unity feature i need to use to controll it? Like telling the texture to not decrease in resolution or a general unity feature.
I think #153 is refering to the same thing.
Or is my usage not possible as the LOD at higher altitudes always will be the lowest one, which will not render the foam anymore?
cheers

**Comment by huwb** [comment]
Yeah high altitudes sound challenging (interesting use case though). At high altitudes the sims will be low res and it will be hard to get nice sharp choppy wakes that will generate foam.

You can limit how low the lod resolutions will go by limiting the *Max Scale* on the ocean renderer script, but it will probably look weird if you do, and not really help.

Instead of relying on the foam to be generated from choppy water you can deposit foam yourself. This will probably take some experimentation to get right. Theres an example in the *whirlpool.unity* example scene, see the gameobject named *DepositFoamTex*. You could add some pattern of foam into the foam sim to get something visible which fades to the dynamic sim when you get closer, perhaps.

**Comment by huwb** [comment]
Actually maybe it's worth trying to force the wakes+foam to work at high altitudes. See if you can edit the dynamic waves and foam settings to make it work at high altitudes. If that works then you could interpolate to these settings based on camera height.

I would:

* Raise camera to elevated height
* Confirm that dynamic waves are still being generated (the example content has a debug GUI to visualise this)
* Jack up the displacement in dynamic waves settings to make more chopper
* Jack up the coverage in the foam settings to add more foam

**Comment by julled** [comment]
Hey @huwb thanks for your reply, i very appreciate it!

The _Max Scale_ option didnt change that much in the scene as far as i can see.
Yes i read about the _DepositFoamTex_ script before but i think it would take lots of work to make it look realistic by coding it from hand this way.  
I would prefer to somehow force the existing very good looking foam/wake simulation to appear at higher altitudes.

>     * Confirm that dynamic waves are still being generated (the example content has a debug GUI to visualise this)
As i increase the elevation the foam dissapears in the GUI and the world, and i dont know where to start in the scripts to force a specific LOD by elevation. :\

Here is my project so far, if you are interested:
https://github.com/searchwingCV/DroneUnitySim

**Comment by huwb** [comment]
I think an approach is to apply brute force which is what I'm suggesting above - turn the settings up to 11/10 and see if you can get foamy wakes at altitude.

**Comment by huwb** [comment]
I generally close issues that are inactive for > 4 weeks to keep issues moving (but ill still get notifications if you post). I'm interested to try this stuff myself and improve how well the sim works at a large height, but my list is long enough that i dont know when i'll get onto it. I'll post back in teh future if i do look at this.
