### ISSUE TITLE
Is there a way to setup the ocean render in a HDRP project?

### ISSUE THREAD

**Issue by Apasal14** [huwb/crest-oceanrender#188]
Hi,

I'm working in Unity 2019.1.0a9 with HDRP version 5.0.0. I have a beach in my scene and i want to add the ocean render to it. When I import the newest release the custom shaders turn all pink. Is there a way to convert the shaders to use HDRP? Honestly, my skills in shader programming aren't that great, but I understand the basics of how a shader works. Any tips or ideas of what might help? :-) I would be so awesome if it can work for a version of HDRP.

Thank you in advance!

**Comment by huwb** [comment]
Hey, no it doesn't currently work in hdrp, but it's something I'm looking at.

Issue #49 is a catch all for SRP requests and news. I hope to post an update there soon.
