### ISSUE TITLE
trying to find a clean way to change the ocean material/all sim settings at runtime

### ISSUE THREAD

**Issue by dizzy2003** [huwb/crest-oceanrender#189]
I tried forcing a disable on all LodDataMgr

Destroying the oceanrenderer object 

Instantiating new OceanRenderer with new material/settings

enabling all LodDataMgr's

But get a bunch of null references in LateUpdate of various systems, like theres few object under the camera that need fixup etc.

Wondering if theres an official way I should be doing this..

BTW I tried using OceanBuilder.GenerateMesh but that lost all animated waves (ocean was flat) and produced about 100 null ref exceptions

**Comment by huwb** [comment]
Um changing the ocean material settings should work. Programmatically the ocean chunk renderer script sets some params. Uses MPBs to prevent instances. Is this what you're after?

Sim settings is roughly similar - you should be able to change them at runtime fairly directly by writing to the scriptable objects. Or you should be able to switch them out at runtime although admittedly I haven't tried this.

Are these the things you're trying to do and they're not working?

**Comment by dizzy2003** [comment]
Sorry for the slow reply.

I'm not trying to change the setting on a shared material, I want to change the ocean material to a whole new material. (which requires changing all the mesh renderers created at runtime, and I would assume binding all the data thats set up for animated waves unless it sets the shader vars on the ocean material every frame)   <Pretty sure I did try setting the Material on all the renderMesh's for the ocena quad lods>
 
I havent tried switching the scriptable object on say the ShapeGerstnerBatched, just deleting or disabling an old one and creating a new one. (theres setting outside of the scriptable object that also change)

**Comment by huwb** [comment]
Oh switching the material. I think I've assumed this would work but didn't try. Maybe it's the material property blocks getting stale.

I'm interested but can't give a timeline when if be likely to look at this as my bandwidth is limited ATM

**Comment by huwb** [comment]
Finally got onto this. I tried a few things but in the end went simple and dumb - the material and settings are all driven by the values on the OceanRenderer script. Now if you change them it should take the new values.

Additionally you can delete the Ocean while the game is running and it should be graceful. However the ocean still needs to be active when the other scripts initialise, for e.g. the gerstner script, due to the way ocean input data is registered.
