### ISSUE TITLE
Black ocean from certain viewpoints

### ISSUE THREAD

**Issue by Midda-C** [huwb/crest-oceanrender#19]
This is an odd one, and it's been happening since we first brought Crest into our project.  I haven't mentioned it because I thought it was related to the old version of the Unity Post Processing stack we were using, but it turns out that isn't the case.

Basically, the ocean will occasionally go completely black, with powerful bloom around the edges (which is why I thought it was the Post Processing stack).  However, it seems to be view dependent, in that if you move the camera to another location, it will pop back to normal.  I've attached some screenshots.

[Example 1](https://user-images.githubusercontent.com/37893722/40599380-384fe236-6290-11e8-8917-b82981d35a26.png)

[Example 2 ('Add Directional Light' disabled)](https://user-images.githubusercontent.com/37893722/40599387-45606810-6290-11e8-8afd-5a235177c736.png)

[Example 3 ('Add Directional Light' + 'Sub-Surface Scattering' disabled)](https://user-images.githubusercontent.com/37893722/40599400-5be45588-6290-11e8-8464-01b1bde5503b.png)

Since it makes the bloom go crazy, I wonder if it's some value that isn't being clamped?  We're using deferred rendering and have HDR enabled.  I'm not exactly sure what other info to give you, but I'll let you know if I can isolate the issue further.  We're using what is currently the latest data on GitHub.

**Comment by huwb** [comment]
Thanks Midda! Thats pretty severe! I have not seen that behaviour before. I tried a few things here to find repro steps but did not get too far.

On clamping, i yesterday found a couple of unclamped bugs which caused bright fireflies and triggered bloom. You said you have latest but thought I'd mention it a I pushed it 12hrs ago. 26a2d7b8d2d5c76bf6d3f4e04049a89551850d69 . This issue looks more severe though.

I assume this is happening in editor - let me know if not though.

Thanks for trying the debug flags. Could you try disable transparency? I've added another debug flag "Debug Disable Multiply by LightColor0" - with this flag, everything involved in computing the ocean colour is disabled.

I've also added another debug flag "Debug Disable Shape Textures" - this will stop it from touching the shape textures, which i suspect are messed up for some reason.

Along that line of thought, it could be useful to enable the debug GUI and see the shape textures. Its not in the core crest files by default (but maybe it should be..) but its in the example content here: https://github.com/huwb/crest-oceanrender/blob/master/src/unity/Assets/Crest-Examples/Scripts/OceanDebugGUI.cs

All of the above would be interesting to see, but there is a more powerful debugging tool which will give me a complete view of the render and should direct me straight to the problem - a renderdoc capture. this would capture some data used in the frame (geometry, textures), so you may not want to post it online. if you are up for going down that route, the steps are:

* install renderdoc (freely available)
* uncomment this line in Ocean.shader for maximum debuggage:  // #pragma enable_d3d11_debug_symbols
* in the Game view dropdown menu, select Load Renderdoc
* press play and repro the issue, then click the little Renderdoc icon at the top of the Game view (see tooltip)
* renderdoc should open. right click the capture thumbnail that should appear and select save, and email it to me.

thanks!

**Comment by Midda-C** [comment]
Emailed that through.  Let me know if I can do anything else to help track this down!

**Comment by Midda-C** [comment]
Our world is lit by a directional light, but we do have other lights in the world (e.g. campfires have point lights on them).

So I just tested this by disabling the objects in my scene that have point lights on them, and yep, the issue disappeared.

I grabbed latest, and it mostly addresses the issue, but I can now see that when the point light sources are in view, the ocean tiles seem to be tinted by the point light colour, even though they are quite far away.  It usually affects all the ocean tiles in view, but at some viewpoints, you can see a sharp line where a few tiles remain unaffected by the point lights.

**Comment by dizzy2003** [comment]
I think I fixed it. (Havent tried your latest changes though)

you need to change the tag to "LightMode"="ForwardBase"

with LightMode=always as you have now unity thinks its not doing any
lighting in the shader so isnt setting the _WorldSpaceLightPos0 value, so
its set to whatever value for what was drawn previously, so if it was a
forwardAdd shader or something then its value might be a point light
position.

**Comment by huwb** [comment]
Nice find!! This actually fixes #15 as well in one fell swoop. It looks great to me here so I pushed it.

I kept the previous change i did, which at least would support one big point light in the world. Regarding supporting multiple lights, I would consider it in-scope but I'm not geared up to comment on what it would take/if its possible etc. Do you have requirement for this, such as local lights at night time or such?

Thanks a bunch!

**Comment by dizzy2003** [comment]
To support point lights you do the same shader again with a tag of
forwardadd, now you calc the lighting uisng the point light info, and
output a pixel that is added to the result from forwardBase.

I will do it at  some point if you dont beat me to it.

The mesh is rendererd multiple times depending on how many lights overlap
it. thats the downside of using forward over deferred. Fortunately your
method of building the wave heights as a separate texture is a big win here
not having to recalc the vert heights.
