### ISSUE TITLE
Synchronised Time Provider, Different Waves?

### ISSUE THREAD

**Issue by darrencperry** [huwb/crest-oceanrender#191]
With the exact same CurrentTime from my class that extends TimeProviderBase, I'm getting very different waves, here are the two AnimWave visualisations, am I missing something? I'm just using the Crest > Materials > Ocean material. This is on two networked PCs but the same happens on the same PC...

I've seen #75 and #88 but haven't seen anything to suggest having the exact same time wouldn't produce the same waves?

![image](https://user-images.githubusercontent.com/370601/53011452-49a6ec80-3438-11e9-86f4-0a85b7c483ad.png)

![image](https://user-images.githubusercontent.com/370601/53011472-59becc00-3438-11e9-9a9c-000be09bc7eb.png)

**Comment by huwb** [comment]
Oh my. Apologies for this. The wave phases were moved to another part of the code and were no longer deterministic. Now it seems to work for me, let me know if this resolves it.

**Comment by darrencperry** [comment]
Totally resolved thanks for the swift fix!
