### ISSUE TITLE
Attenuation In Shallows not working in personal project

### ISSUE THREAD

**Issue by fikoljuky** [huwb/crest-oceanrender#194]
Hey. I tried this water solution in a clean project and everything was working great. Great work btw.
When I opened in my own project the attenuation In Shallows doesn't work at all, so the waves don't lower when near terrain. I tested it in the example scene in both projects. Do you maybe have an idea where the problem could be? 

I figured that when I move the island in the working project the wave height lowers only on the original position of the island. Is it possible that the island position has to be baked somehow for the wave height to work correctly?

**Comment by fikoljuky** [comment]
I figured out the solution to the problem. I had to adjust the size of the OceanDepthCache gameObject.

**Comment by huwb** [comment]
Glad to hear it, cheers
