### ISSUE TITLE
Weird shadow 

### ISSUE THREAD

**Issue by fikoljuky** [huwb/crest-oceanrender#195]
I'm having issues with some type of shadow being generated in my scene. The shadow doesn't appear in the example scene. I'm attaching the picture so you can see what I mean. 

![shadow](https://user-images.githubusercontent.com/29865680/53555410-253ac680-3b42-11e9-844d-c8150756c4a7.png)

It seems to fade out when the camera is looking directly at the water. The same artifact can sometimes appear once you are exiting the water. 

The cast shadow option is disabled on the Mesh renderers for all the object.

**Comment by fikoljuky** [comment]
Managed to fix it by using Deferred rendering. But I would like to know if it's possible to use it in forward rendering mode without the shadows.

**Comment by huwb** [comment]
I'm not sure where that shape is coming from. I've not seen that before. Is it coming from the ocean system do you think? You could disable the ocean game object and see if it disappears?

**Comment by fikoljuky** [comment]
Yeah, it's from the ocean game object. I already tried that. It looks like a shadow, but it seems not to be affected by lighting in any way.

**Comment by huwb** [comment]
It looks maybe like water covering sand rather than shadow, but it's hard to tell from the above. I'm not sure why it would give such a straight edge if it is the water line.

Sorry I can't help more. Let me know if you get to the bottom of it. Maybe others have seen something similar and can jump in here? I'll leave the issue open.

**Comment by huwb** [comment]
As discussed offline, I'll close for now as you're not encountering this in deferred rendering. If you get back on the forward renderer  and encounter this again let me know and I'll reopen.

**Comment by fikoljuky** [comment]
Ok. Cool.

Thanks for the heads up!
