### ISSUE TITLE
Stylised Fresnel

### ISSUE THREAD

**Issue by Midda-C** [huwb/crest-oceanrender#196]
Hi Huw!

So I just had an idea pop into my head regarding a simple way to stylise the look of Crest for less realistic games.  It's already usable as-is (our game isn't realistically styled and Crest looks great), but I was thinking of ways it could be tweaked further.

What came to mind was something similar to how we light some of our characters and props in game, which is remapping the light intensity using a simple ramp lookup texture.  For example:

![image](https://user-images.githubusercontent.com/37893722/53782318-8276b380-3f58-11e9-904f-840bdb727cda.png)

So the above texture introduces a basic sort of cel-shaded look to our characters.  I'm sure you're familiar with this approach.  I was wondering if a similar sort of approach might be possible with the fresnel intensity?  For example:

![image](https://user-images.githubusercontent.com/37893722/53782440-fc0ea180-3f58-11e9-8600-cc4df9a6f44f.png)

So rather than the fresnel gradually fading away, it'd have distinct steps.  That is, it wouldn't be changing the actual colours being reflected in the fresnel, just modifying the falloff.  I'm imagining it might be possible to use this to give an effect somwhat similar to the water in Super Mario Sunshine (though obviously they achieved this is a much different way).

What are your thoughts?

**Comment by huwb** [comment]
Hey thanks for this, yeah sounds like a good idea to me, would be interesting to see the result. I'll post back when i have a chance to try it.

**Comment by huwb** [comment]
I pushed a test into a branch. Commit referenced above. It worked, but its quite subtle outside of very extreme settings, and needs to be tweaked with a project in mind.

An example:

Ramp:

![image](https://user-images.githubusercontent.com/939901/55278365-3b83a000-5303-11e9-8e2d-d26684e07028.png)

Image:

![image](https://user-images.githubusercontent.com/939901/55278361-345c9200-5303-11e9-8c1d-36270eda279b.png)

The touch of white gives very strong reflection at grazing angles, then the gray area adds "some reflection" in the midground, while the foreground is kept completely transparent.

It could be cleaned up and made merge-able into master, but I'd like to see someone put this to use before adding more code, so I might park it here for now. Let me know what you think!
