### ISSUE TITLE
This GfxDevice does not support asynchronous readback

### ISSUE THREAD

**Issue by cman122887** [huwb/crest-oceanrender#199]
My guess is that this is because I'm using Linux Unity, but on Play my game window does not show the ocean being rendered and I get this in the debugger.

`This GfxDevice does not support asynchronous readback
UnityEngine.Rendering.AsyncGPUReadback:Request(Texture, Int32, Action1)
Crest.GPUReadbackBase1:EnqueueReadbackRequest(RenderTexture, RenderData, Single) (at Assets/Crest/Scripts/GPUReadback/GPUReadbackBase.cs:200)
Crest.GPUReadbackBase1:ProcessRequestsInternal(Boolean) (at Assets/Crest/Scripts/GPUReadback/GPUReadbackBase.cs:168)
Crest.GPUReadbackBase1:Update() (at Assets/Crest/Scripts/GPUReadback/GPUReadbackBase.cs:86)
`
I am however able to see the ocean in the scene window when in game mode.
Was just curious if anyone has had this issue an know if theres a fix/workaround to see the ocean in the game window.

Thanks!

**Comment by huwb** [comment]
Oh interested. Which GPU are you using?

You could try creating an asset of type Crest/Animated Wave Settings by right clicking in the project view, set the collision source to None or CPU, assign this asset to the OceanRenderer script to apply it. This should stop it trying to do GPU readback. The downside is this will either disable physics if you set it to None, or if you use CPU it will be limited to open ocean waves (collision wont work properly in shallow water).

**Comment by Midda-C** [comment]
I just gave this a try too.  I got the same error (I'm using a Vega 64), but it's fine if I switch the editor to Vulkan instead of OpenGL.

I do get this in Vulkan, though:

```
SetTextures: missing texture ID 755
UnityEngine.Graphics:ExecuteCommandBuffer()
Crest.BuildCommandBuffer:LateUpdate() (at Assets/Crest/Scripts/BuildCommandBuffer.cs:74)
```

7 of those errors (I assume one for each LOD?).  Everything looks like it's working, though.

**Comment by huwb** [comment]
Thanks @Midda-C . That 755 i guess is the parameter ID for one of the textures. This is generated at runtime. Could I please get a the log from a run with a Debug.log statement added to LodTransform.cs shown below: 

    public static void CreateParamIDs(ref int[] ids, string prefix)
    {
        int count = 2;
        ids = new int[count];
        for (int i = 0; i < count; i++)
        {
            ids[i] = Shader.PropertyToID(string.Format("{0}{1}", prefix, i));
            Debug.Log("Texture ID: " + string.Format("{0}{1}", prefix, i) + " = " + ids[i]);
        }
    }

**Comment by cman122887** [comment]
I'm using a GTX 1050. I'll switch to CPU and see if I can use it in limited capacity. I tried switching player settings explicitly to both OpenGLCore and Vulkan but had the issue with both. Maybe I changed the settings wrong. Thanks for the tips and looking into it!


On Sun, Mar 17, 2019, 7:39 AM Huw Bowles <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks @Midda-C<https://github.com/Midda-C> . That 755 i guess is the parameter ID for one of the textures. This is generated at runtime. Could I please get a the log from a run with a Debug.log statement added to LodTransform.cs shown below:

public static void CreateParamIDs(ref int[] ids, string prefix)
{
    int count = 2;
    ids = new int[count];
    for (int i = 0; i < count; i++)
    {
        ids[i] = Shader.PropertyToID(string.Format("{0}{1}", prefix, i));
        Debug.Log("Texture ID: " + string.Format("{0}{1}", prefix, i) + " = " + ids[i]);
    }
}

**Comment by Midda-C** [comment]
No worries, here's my editor log.  Took me a moment to find where it hides on Linux. :P

[Editor.log](https://github.com/huwb/crest-oceanrender/files/2977104/Editor.log)

**Comment by huwb** [comment]
I could also get the errors running with Vulkan enabled on windows.

I seem to have narrowed it down to where it does the foam update. It seems to generate errors when it samples the previous frame's foam values.

It seems to only generate the errors once. Everything renders fine and if i look at a renderdoc everything looks ok. Those texture IDs that it reports have numbers larger than any of my texture samplers. There errors seem to get generated precisely once and theres no errors in renderdoc.

I found a way to interrogate what some of these names are - by calling Material.GetTexture() with the IDs. I get nonsense results when i call this on the foam update material:

619: LoResAO2
621: HiResAO
1736: <noninit>
1781: <noninit>

This doesnt really make it clearer. I would however expect that low texture ID's in the 600s would be engine textures (the crest texture IDs start from 800-900). 

I don't really get what any of this means tbh - its tempting to say its a bug in the vulkan backend where stuff wasnt initialised properly, but it all goes away if i knock out the foam sim...

It would be interesting to know if enabling the foam sim after startup also makes the error. Right now its not posssible to turn the foam sim on halfway through but that would be a desirable feature that i could potentially add. Besides that i'll think about other ideas.

**Comment by sguiheux** [comment]
Hi, I got this error when executing code in webgl

```
This GfxDevice does not support asynchronous readback
 
(Filename: ./Runtime/GfxDevice/GfxDevice.cpp Line: 1625)
```
It should works with WebGL or not ?

I tried the answer of @huwb with an new Crest/Animated Wave Settings asset, choosing CPU or None but i got the same error.

**Comment by sguiheux** [comment]
I succeed creating an SimSettingsFlow  and disable "Readback Data"
But when I compile for desktop all is ok
When I compile for WebGL there are no waves :(

**Comment by huwb** [comment]
Hi sorry i've not replied before now. Could you please file a new issue. The issue tempalte will ask for version and screenshot and log and all that jazz. One more thing - I pushed changes in the last week or two that change how the rendering works a bit, could you get latest if you don't already have it. Thanks!

**Comment by moosichu** [comment]
For the record, I now have everything working fine on Linux using Vulkan (except shadows), which is now my primary development platform (which should help prevent things from regressing).

This is as-of Unity 2018.4.

**Comment by huwb** [comment]
We're no longer supporting OpenGL. Its possible/probable that crest can work on opengl with a few fixes, but we are deprioritising supporting this platform.

**Comment by moosichu** [comment]
#280 makes Vulkan the default API on Linux.

**Comment by cman122887** [comment]
Thanks All! Y'all are awesome
