### ISSUE TITLE
missing a shader include I think on build causing this issue.

### ISSUE THREAD

**Issue by holdingjason** [huwb/crest-oceanrender#202]
Ok everything works fine in the editor but after a build seeing this issue.

So looks fine here.  I change these values when the camera goes under the water so I am sure it is related to that but as I said works fine in the editor play but not after a build.  So was thinking a shader problem of some sort ie missing or some value that cant be changed after the build?  Not sure but hoping you would know off the top of your head.

        oceanRenderer.OceanMaterial.SetVector("_DepthFogDensity", DepthFogDensity);
        oceanRenderer.OceanMaterial.SetFloat("_RefractiveIndexOfAir", ReflectiveIndexofAir);
        oceanRenderer.OceanMaterial.SetFloat("_RefractiveIndexOfWater", ReflectiveIndexOfWater);
        oceanRenderer.OceanMaterial.DisableKeyword("_SHADOWS_ON");

![image](https://user-images.githubusercontent.com/42001313/54855466-a99ce700-4cb3-11e9-9dc7-ebc7e95edb9a.png)

Drop under the water a bit.

![image](https://user-images.githubusercontent.com/42001313/54855505-d3560e00-4cb3-11e9-8ea5-28b2c540d572.png)

And fully under.

![image](https://user-images.githubusercontent.com/42001313/54855519-e832a180-4cb3-11e9-96e8-47e93661e5cd.png)

**Comment by huwb** [comment]
Apologies for this :(, some include paths recently rotted. My bad for not making a standalone build after this change. Let me know if the referenced commit resolves it on your end.

**Comment by holdingjason** [comment]
Will do.  Let you know in a few.

**Comment by holdingjason** [comment]
So does not look like this fixed my issue at least not only doing this.  Doing a new build to test again.

**Comment by holdingjason** [comment]
Ok that did not work.  Do you know if I am suppose to include anything in project settings or should the includes above just take care of this.  Going to try removing those four lines here and see if it has something to do with that.

    oceanRenderer.OceanMaterial.SetVector("_DepthFogDensity", DepthFogDensity);
    oceanRenderer.OceanMaterial.SetFloat("_RefractiveIndexOfAir", ReflectiveIndexofAir);
    oceanRenderer.OceanMaterial.SetFloat("_RefractiveIndexOfWater", ReflectiveIndexOfWater);
    oceanRenderer.OceanMaterial.DisableKeyword("_SHADOWS_ON");

**Comment by holdingjason** [comment]
Ok yes one of those (my guess its the shodow disable) causes the issue.  Modifying it on the fly like that seems to cause the problem.  Not sure how to resolve that exactly?  Thoughts...

BTW are you on discord.  Would love to have you join us on our development discord site.  

https://discord.gg/QtUafGf

**Comment by holdingjason** [comment]
Believe we might be missing this #pragma multi_compile __ FOO_ON

**Comment by huwb** [comment]
Ah ok good find. It might be the thing where the shader is not available in standalone, because it hasnt been built. Unity doesnt know in advance that you'll use the version of the shader with _SHADOWS_ON, so it doesnt package it.

Ok that pragma might force it to make both variants.

Are you doing that DisableKeyword() call to work around the other issue where the surface looks crap underwater? I'm on the fence about adding a multi compile to support this, or just fixing the core problem.

**Comment by holdingjason** [comment]
That is correct.  I am doing that as a hack for the underwater surface issue.
