### ISSUE TITLE
Azure Sky Fog Issues with new shader changes.

### ISSUE THREAD

**Issue by holdingjason** [huwb/crest-oceanrender#203]
Just pulled latest to test that other issues and trying to add back in Azure sky fog with the new shader and getting this error now.

	// Azure Fog: Compute fog projection uv. //
				o.projPos = ComputeScreenPos(o.positionCS);
				COMPUTE_EYEDEPTH(o.projPos.z);

Error
Shader error in 'Crest/Ocean': undeclared identifier 'v' at Cove/temp.hlsl(174) (on d3d11)

Compiling Vertex program with UNITY_PASS_FORWARDBASE
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_RGBM_ENCODING

**Comment by holdingjason** [comment]
I think the issue is related to going from  
	float4 vertex : POSITION;

to 
		float3 positionOS : POSITION;

So went from a float4 to a float3?

**Comment by huwb** [comment]
Sigh looks like COMPUTE_EYEDEPTH is hardcoded to expect the vert shader input to be called 'v' :).

I changed it to 'input' to match srp shader coding standards. I suppose i will change it back to v given this is a unity macro

**Comment by holdingjason** [comment]
Uggg that is really annoying.

**Comment by holdingjason** [comment]
Well will comment out the fog stuff for now and just test to see if we fixed the other issue of the build.

**Comment by huwb** [comment]
Yes also what you said, ill change that as well.

**Comment by huwb** [comment]
Could you please try what i just pushed, hopefully its good now..

**Comment by holdingjason** [comment]
sure one sec.  BTW not sure that other issue is resolved still seeing the issue underwater.  Lets resolve this one and then I will check that one again.

**Comment by holdingjason** [comment]
Ok this worked thanks.  Now checking the other so will jump over to the other one.
