### ISSUE TITLE
Can't get AzureSky & Enviro fog t show since the update.

### ISSUE THREAD

**Issue by VizzzU** [huwb/crest-oceanrender#204]
Not reaélly an issue , and not really sure how to explain .

Since a recent update in your shader i ve got trouble to use COMPUTE_EYEDEPTH to calculate the screen position . It is throwing an error about "v who is undeclared"  but i am not using v ...

To be clear , in order to have fog showing correctly on the ocean ( it was discussed before in a previous thread  ) you have to set the world position (provided in the shader) , the screen position and the depth . Can i use the screen pos & depth calculations already presents in the shader ?

With the old crest's versions you were using the word"vertex" but now it is "positionCS" and "positionOS". I know that the issue is here but i am unable to make it work cause i am fairly new to shader coding .
Any explaination about this change or tip would be welcome . Sorry for the newb questions .

Was thinking about sharing some pictures after updating crest and no fog ^^ .But a "v " error .

Feel free to ask me more details if it can help .

Amazin work !!!!!

**Comment by huwb** [comment]
Hi @VizzzU , sorry you ran into this. It was also reported in #203 and is
hopefully already fixed on latest, could you please get latest?

I had to rearrange the project files, the unity project now lives under
crest\, I'd be curious if that causes you hassle?

Also noteworthy - i've added a comment to the ocean shader pointing to
where azure should be added. if you put it at the end of the Frag shader it
will double apply over unity fog (if you have it enabled), and it will also
double apply over underwater fog, which is not correct. If you look in my
version of the shader for 'Azure' thats where it shoudl go.

**Comment by VizzzU** [comment]
will have a try right now and tell you if everything works fine . 
Hope to share pics for the gitPage this afternoon .

thx for the amazing support .

**Comment by VizzzU** [comment]
My bad , this issue was commented 2 days ago , i am sorry .
