### ISSUE TITLE
FeedVelocityToExtrude strange code

### ISSUE THREAD

**Issue by ShadowTeolog** [huwb/crest-oceanrender#211]
I found this code, and not understand what happen here
var disp = _boat != null ? _boat.DisplacementToBoat : Vector3.zero;
transform.position = transform.parent.TransformPoint(_localOffset) - disp + _velocityPositionOffset * _boat.RB.velocity;
1. Code is check if boat not null but failed on next line if boat is null because _boat.RB
2. Here rigid body VELOCITY appending to POSITION without Time.DeltaTime? This mast move this interaction object forward depending on velocity?

I currently try this one 
var disp = _boat?.DisplacementToBoat ?? Vector3.zero;
var velocity = _boat?.RB?.velocity ?? Vector3.zero;
transform.position = transform.parent.TransformPoint(_localOffset) - disp + velocityPositionOffset *velocity*Time.deltaTime;

**Comment by huwb** [comment]
Thanks

You're right on the null check, i'll do what you did, or move it up in the code.

When applying forces to the water surface in the dynamic sim, it takes a while for the water to change shape and for the ripples to develop. The offset is indeed intended to be an a factor applied to velocity.

I think the factor as i have it has delta time baked into it, and what you've done makes it use the current delta time. However this is a prediction - it predicts how far forward to affect the dynamic waves - I think it depends only on the dynamic state - pos and vel. The prediction should not changed based on current framerate / deltatime.

**Comment by ShadowTeolog** [comment]
Also need +1 null check for boat, several lines down. Resharper helps ;)
I understand about prediction, You move object to 0.2 seconds forward by velocity and up/down depending on displacement, right? I was little confused by variable name

**Comment by huwb** [comment]
Sure thanks.

Yeah - it first does subtracts displacement. This converts from world space to a point on the ocean surface, in the local space of the LOD. Because the ocean waves displace the surface horizontally, these two things are not the same.

Then its moved forwards in time by e.g. 0.2s as you say.
