### ISSUE TITLE
Move GPU computations to compute shaders where suitable

### ISSUE THREAD

**Issue by moosichu** [huwb/crest-oceanrender#214]
Breakdown of tasks that need completing currently being contructed.

Being worked on in the `feature/compute-shaders` branch.

**Comment by huwb** [comment]
Just going through old issues seeing which i can close. as the conversation here has moved to the PR, would you be comfortable closing this, or do you want to keep it open?

**Comment by dizzy2003** [comment]
Just thought I'd mention here that theres a few issues with the current compute branch on ps4/switch (havent tested xbox)

**Comment by moosichu** [comment]
@huwb For me personally, I think it makes more sense to close issues when they've been resolved and the changes have been merged into the main branch. I've now linked the PR to this issue so that we have more visibility there. However, if you think it makes sense to close it now because it is already in progress, then do that for sure.

**Comment by moosichu** [comment]
Closing this for now but leaving #230 open for reference. We have decided not to move to compute shaders (for now) while we explore other options for reducing the number of draw calls.
