### ISSUE TITLE
Jitter on 16bit GPUs (inc mobile)

### ISSUE THREAD

**Issue by huwb** [huwb/crest-oceanrender#216]
One fix for this is in #215 - stopping time values growing large.

It looks like animated texture coordinates either need to be wrapped to keep them bounded, or moved to floats.

Big thanks to @minggoddess for help on this.

**Comment by minggoddess** [comment]
My honnor, huwb. ^_^

**Comment by huwb** [comment]
I'm sorry to say that I won't realistically have time to look at this any time soon. Mobile is not a priority for crest. I'm happy to help talk through the issue etc. If you have thoughts feel free to reply here and i will get a notification.
