### ISSUE TITLE
[Built-In RP] Unity does not use default unity reflection cube map

### ISSUE THREAD

**Issue by huwb** [huwb/crest-oceanrender#217]
This means that the cube map either needs to be assigned manually by hand or using a script, or the OceanPlanarReflection script is required which costs performance.

It would ideally use the default reflections that Unity should assign.

**Comment by huwb** [comment]
This might be the required code: https://forum.unity.com/threads/reflection-probes-in-custom-shader.322562/#post-2093052

**Comment by ForgeUser2018** [comment]
> This might be the required code: https://forum.unity.com/threads/reflection-probes-in-custom-shader.322562/#post-2093052

Yea I've seen `float4 val = UNITY_SAMPLE_TEXCUBE(unity_SpecCube0, coords); finalColor.xyz = DecodeHDR(val, unity_SpecCube0_HDR);` being used for this several times on the unity forums and stackoverflow. Looks like it's worth giving it a try.

**Comment by huwb** [comment]
Made a PR - #221 for testing

**Comment by huwb** [comment]
@holdingjason 's tests indicate it seems to work, but in some situations the reflections appear grainy and odd (examples in issues channel of discord). It might be a problem with normal map filtering or something along those lines. The issue may also be caused by dynamic reflection probes or exacerbated by them.

Repro is to apply the PR and turn off planar reflections on the ocean material, and put a dynamic reflection probe into the scene.

**Comment by huwb** [comment]
Fix found for graininess, PR merged in
