### ISSUE TITLE
[LWRP] Crest not updated to 2019 yet

### ISSUE THREAD

**Issue by huwb** [huwb/crest-oceanrender#218]
I was planning to wait for 2019 to be released (out of beta) but a couple of people have run into this now.

The fixup is not huge and i have some local changes for it.. I could probably do an early submission to fix up the current things. I looked at other assets and i dont see mention of 2019. If anyone has thoughts about this please jump in.

**Comment by huwb** [comment]
As a temporary hack fix, i was able to get past the build errors on LWRP 5.10.0 by commenting out the code that is not building - i commented out everything in SampleShadowsForCamera, and commented out the definition for the SampleShadowsPass, and then commented out the other 1 or 2 bits that give errors, and that gives me a version that seems to work (but with shadow data knocked out)

**Comment by huwb** [comment]
I have a first implementation where shadows are a LWRP renderer feature. Some issues to work through. Really like how they've set it up (thumbsup).

**Comment by huwb** [comment]
I have done the fixup now and will submit a new package which will work on 2019.

It will knock out the crest shadowing feature on 2018 because it was too messy to try to support the preview versions of LWRP for this feature, so its disable on pre-2019 versions.

Will close when the asset package is published.

**Comment by arturleao** [comment]
We are currently working on a large scale project (an island) with LWRP and 2019 (yes, doing production with beta versions :P) and we would be happy to test your 2019 package.

**Comment by huwb** [comment]
Thanks for that. The changes were small enough that I felt comfortable going straight to submitting a package. I will post back when it goes live and would appreciate if you guys could try it out.

Btw would love to see what you guys are working on if/when you are able to share!

**Comment by huwb** [comment]
The asset store package went up - crest should work with the latest version of unity and lwrp without any fixes or misc required. @arturleao if you get a chance to test let me know. thanks!
