### ISSUE TITLE
Motion Vectors TAA support

### ISSUE THREAD

**Issue by olavrv** [huwb/crest-oceanrender#223]
Is there support for motion vectors on ocean geometry using Unity's post processing stack temporal antialiasing?

**Comment by huwb** [comment]
There is not unfortunately. While it would be feasible to generate MVs from the water surface (and i might look into it in HDRP), the system supports generating arbitrary shape, so it would probably also need a way to render in

**Comment by huwb** [comment]
I'll close for now but will receive a notification if you reply. I'll also keep it in mind in the future and will post back here if something changes - maybe hdrp opens a door here.
