### ISSUE TITLE
[LWRP] Refraction appears incorrect at higher altitudes 

### ISSUE THREAD

**Issue by karearea** [huwb/crest-oceanrender#229]
Firstly, I'd like to say thank you for an excellent Ocean solution in LWRP. Very happy with both the appearance, and performance.

I have noticed that while the default refraction setting of 0.1 looks good around sea level, the effect appears to scale in view space, so the refraction pattern stays at the same size with relation to the screen when the camera is at high altitudes (say 5000 units above the water)

This obviously looks 'incorrect', and means it's impossible to achieve a nice tropical archipelago look.

**Comment by huwb** [comment]
Thanks yeah i had noticed it was off but hadnt understood how to fix it, i think you're right it needs to scale down with distance!

**Comment by huwb** [comment]
Yes it looks like that worked, thanks again for that pointer.

I have pushed it into the github in the commit referenced above. It will filter up into LWRP on the next release. It may be fairly easily to make the fix locally if you want to do this in the meantime?

**Comment by karearea** [comment]
Thanks for the quick response @huwb -Would those fixes work if I just add the snippets from the most recent commit to the appropriate parts of my LWRP project?

**Comment by huwb** [comment]
Yeah, they should do. I thought i'd mention that because it might save time if you want the fix sooner. I'll probably post a new version this weekend so it will go live next week.

**Comment by karearea** [comment]
Thanks Huw, I managed to copy the code into the LWRP with adaptations as needed. Looks great!

**Comment by huwb** [comment]
Submitted a new store version, will confirm when it goes up

**Comment by huwb** [comment]
Should be fixed in 1.5
