### ISSUE TITLE
Update Materials to LWRP does not work

### ISSUE THREAD

**Issue by klauskobald** [huwb/crest-oceanrender#231]
I tried to run the update to LWRP from the edit menu and get these errors:
..... material was not upgraded. There's no upgrader to convert Lightweight Render Pipeline/Terrain/Lit shader to selected pipeline
UnityEditor.Experimental.Rendering.LightweightPipeline.LightweightRenderPipelineMaterialUpgrader:UpgradeProjectMaterials()

Resulting in only purple shading.
Isn´t this the way to do?
Thanks,
Klaus

**Comment by klauskobald** [comment]
ahh - my mistake. I see there is an other version on the asset store.
But before buying: will it work on slower mobile devices as well with LWRP?
Will it work on Oculus Go?
I am  currently using community ocean shader which does it´s job pretty well. But I need the "flow" and the "less waves in shoal waters" features.

**Comment by huwb** [comment]
Right - yes.

I would not recommend it for slower mobile devices. As I wrote on the store its targeted towards PC and console. If you do decide to go with crest, it will likely take technical expertise and time/effort to find ways to make it work on mobile. Sorry i dont have better news for you!
