### ISSUE TITLE
[LWRP] Planar reflections broken

### ISSUE THREAD

**Issue by huwb** [huwb/crest-oceanrender#233]
The latest version of LWRP no longer calls OnPreRender() on camera scripts apparently which breaks planar reflections. I need to find an alternative hook for this.

**Comment by karearea** [comment]
https://github.com/Verasl/BoatAttack/ has an example of a scriptable render pass for planar reflections, which was up to date with the 5.* LWRP last time I checked.

**Comment by huwb** [comment]
Thanks good to know but I think i have what i need to sort this.

**Comment by VizzzU** [comment]
Any quick fix for this ?

**Comment by huwb** [comment]
New package submitted to asset store..

**Comment by huwb** [comment]
Will close when it goes up.

**Comment by huwb** [comment]
It should work on 1.5. Let me know if you still see issues
