### ISSUE TITLE
Underwater view not working with multiple cameras

### ISSUE THREAD

**Issue by Bartolomeus755** [huwb/crest-oceanrender#235]
Hi,

After loading the scene, I have a dropdown menu for the player boat selection. From this dropdown menu, I instantiate the player watercrafts and I have one camera for the player boat selection. During the watercraft selection and the first camera is active, the underwater view works fine. 

But if the user selected a boat, I disable the first camera and create a new one as the player cam. And now the underwater view is broken with the new created camera.

Any advice how I can get the underwater view working with multiple cameras?

Regards
Marko

**Comment by huwb** [comment]
Right, when changing cameras you also need to set the Viewpoint property on the OceanRenderer to whatever is the main camera. This ensures that the ocean will follow the camera around, and also coincidentally will make the underwater effect work.

**Comment by Bartolomeus755** [comment]
Ah, my bad. I have forgotten to update the camera. Now it works fine, thank you very much.
