### ISSUE TITLE
Water displacement not dependent to boat class.

### ISSUE THREAD

**Issue by Bartolomeus755** [huwb/crest-oceanrender#236]
Hi,

Any chance to get an alternative FeedVelocitytoExtrude script, which not depend on the boat class? In order to get the water displacement working with custom watercraft physics.

**Comment by huwb** [comment]
Took "a while" but got there in the end. Does this help? Feedback welcome!

https://github.com/huwb/crest-oceanrender/pull/269

**Comment by huwb** [comment]
Oops left this open. Closing!
