### ISSUE TITLE
[LWRP] Caustics visible in shadows .

### ISSUE THREAD

**Issue by VizzzU** [huwb/crest-oceanrender#240]
Just like the title says ; ) .

**Comment by huwb** [comment]
I could not reproduce this here - when i have shadowing enabled on the ocean then the caustics seem to be shadowed. Do you have this?

**Comment by VizzzU** [comment]
strange . I will try n a new project and have a look at the pipeline settings again

**Comment by huwb** [comment]
Haha thats ok, it is indeed a few steps to get it turned on, i'll keep an eye out if some of this can be automated in the future
