### ISSUE TITLE
Best way to scale down? (Not an issue)

### ISSUE THREAD

**Issue by jelmerS2** [huwb/crest-oceanrender#242]
I'm using crest for an AR app. In the app, content is scaled down about 100 times. What would be the best way to scale down the crest ocean, if possible at all?

**Comment by huwb** [comment]
The short answer is it isnt supported, but i decdied to experiment a bit and see how far i could get. What i did:

Ok just found a crazy bug in the ocean to do with scaling which you'll want to fix first:

Replace

            float camY = Mathf.Max(Mathf.Abs(_viewpoint.position.y) - maxDetailY, 0f);

With this:
            float camY = Mathf.Max(Mathf.Abs(_viewpoint.position.y - SeaLevel) - maxDetailY, 0f);


Then set the Min Scale on the OceanRenderer script to something very small like 0.25 (use powers of 2).

Then you may need to add a smaller wavelength(s) to the spectrum, set the low wavelength to something like:

        public static readonly float SMALLEST_WL_POW_2 = -4f;


Thats the stuff to get lower scales. Then some things are driven by physics, For example wave velocities are based on wavelength

                        float C = Mathf.Sqrt(wl * gravity * gravityScale * one_over_2pi);

Which you may need to mess with.

And there'll probably be other things.. I think it could be a lot of work to make it work well I'm afraid

**Comment by jelmerS2** [comment]
Thanks! I managed to get quite far by:
- applying your bug fix
- setting SMALLEST_WL_POW_2 to -4
-settings a very small oceanwavespectrum, and by setting the gravity scale to small, a lot of good stuff happened as well
- also changed the scale value for several textures of the ocean material

However, with the material I bumped into a small problem with the animation:
both the speed for normal mapping and the foam (see last part of the movie) go a bit too fast I think. 
Is there a way to change the speed of the texture anuimation? 
Otherwise I think it looks pretty good now! The object represents an oil platform. https://youtu.be/-UhvWi5gt8A

**Comment by moosichu** [comment]
You could look at `OceanNormalMapping.hlsl`, you will find this line:

`const float2 v0 = float2(0.94, 0.34), v1 = float2(-0.85, -0.53);`

Changing those numbers should have the desired effect.

**Comment by huwb** [comment]
Thanks Tom

(Btw this makes me realise these should really scroll at the rate that waves would physically move at a scale just below the current LOD0. i reckon theres also a task to scale normal strength based on the spectrum as well. Not critical but potential future stuff.)

**Comment by huwb** [comment]
Closing but if you reply we'll get notifications so feel free to let us know how it goes

**Comment by jelmerS2** [comment]
Long time no seen. As Unity physics are also hard to scale down, the better approach to scale content for mobile AR apps is to change the behaviour of the camera instead of actually scaling the content. So when the user moves his phone say one meter, the virtual camera in the scene will be moved 100 Unity units instead of 1. That is what I ended up going for.
