### ISSUE TITLE
[LWRP] Specularity vs Reflection

### ISSUE THREAD

**Issue by karearea** [huwb/crest-oceanrender#243]
I've just integrated the fixed planar reflection system in Crest v1.5 for LWRP. It's looking fantastic and performance is great.

I've had to reduce the specularity to around 0.1 to avoid the reflection vastly overpowering the surface. This appears about right, but I no longer have the nice specularity/sparkling  playing off the crests of waves. Would it be possible to decouple the reflection power from the sunlight specularity?

The screenshot demonstrates this a bit - the (lit) foam picks up nice specularity, but the ocean surface doesn't.

<img width="797" alt="Screen Shot 2019-05-07 at 13 12 28" src="https://user-images.githubusercontent.com/16930004/57265289-0bca7380-70cb-11e9-97d2-1fe71ed6bf4f.png">

**Comment by huwb** [comment]
I've just rewritten the reflection part of the code in the last few days after that release. do you want to take an early version of 1.6? are you on the crest discord?

**Comment by karearea** [comment]
Hi,

As mentioned on Discord, the forthcoming reflections on 1.6 look superb, thank you. I've just noticed a disparity in the build only, on Mac OSX Standalone, where it appears the sky isn't included in the reflection?

![CrestReflections](https://user-images.githubusercontent.com/16930004/57659805-c6142a80-7637-11e9-94e0-410792ac844e.png)

I've tried rebuilding the lighting, and going so far as to delete the library etc.

**Comment by karearea** [comment]
Aha, the issue here is the Clear Flags setting on Ocean Planar Reflections. With the default set to 'Color', it seems there is a difference between the colour in the editor (which looks correct) and the colour in the build (which goes to black). Setting the clear flag to Skybox is preferable anyway, and there isn't the disparity in the build.

**Comment by huwb** [comment]
That sounds like a unity bug to me - this really should be set to Color. I don't have an OSX kit avail to me for testing so using Skybox will have to be the workaround for the time being.

**Comment by karearea** [comment]
All of these issues are on Metal. Unity seem to have a lot of outstanding bugs to that end, I’m seriously considering dropping it as a target.
