### ISSUE TITLE
When the camera is inside the boat, it will see the water.

### ISSUE THREAD

**Issue by Zoranner** [huwb/crest-oceanrender#244]
Hi! When the camera is inside the boat, it will see the water. Is it possible to change the water inside the floats to be transparent or to cut off the surface mesh inside the floats? Thanks. 😀

**Comment by huwb** [comment]
Hi theres a bit of a history to this, its not for the faint hearted!

Mask out the water: https://github.com/huwb/crest-oceanrender/issues/77
Show the water through a window or such: https://github.com/huwb/crest-oceanrender/issues/163

Mostly speculation and unshipped i would guess!

I'll close this as i'm guessing any conversation belongs in one of those issues.

**Comment by Zoranner** [comment]
Thanks, my fault, I haven't noticed that before. 🤐
