### ISSUE TITLE
Ocean Turning White

### ISSUE THREAD

**Issue by Hydrolox** [huwb/crest-oceanrender#245]
Mentioned this on Discord, was asked to put it here, so here it is in this sort of archive if anyone else is having the issue:

> I noticed the water was changing visibly based on the camera location moving around. This gave it a really weird, unsettling feeling and would make foam disappear or reappear based on camera position, and it especially didn't interact well with dynamic waves the ships were making. So I decided to put the camera's target as the ocean renderer's "viewpoint" so nothing would change based on camera position. It worked great to make the water seem more solid, BUT...

It also caused this issue - for months I've had this issue where if you look at the ship from too high of an angle, its shaders would fail and it'd turn solid, unlit white. I also noticed recently that the entire ocean does this if the ship goes too far above/below water.

So it was certainly some effect caused by having something other than the camera set as the viewpoint, BUT, I'm not having the issue anymore now that I've 
1. set the camera to forward rendering, 
2. enabled planar reflections
3. enabled shadows cast on the water

So one of those 3 things fixed it.

// And then I was asked to re-create it, so here's what I said on that:

So water with Ocean Planar Reflections script disabled, No Sim Settings Shadow loaded, "Create shadow data" unchecked, and "Ocean Planar Reflections" turned off in the materials options.

![unknown (1)](https://user-images.githubusercontent.com/19767654/57576315-50834100-7422-11e9-92e3-4bae2fc84fe1.png)

Getting some stormy high seas, I was able to recreate it pretty quickly, so I'm pretty sure it's to do with the "Viewpoint" being below the water, since it's centered on the ship, not the camera.

Funny enough, though, this isn't the original issue. The original issue was the ship's material/shader turning solid white, but I guess the ocean wanted in on the fun, instead.

![unknown (2)](https://user-images.githubusercontent.com/19767654/57576318-6264e400-7422-11e9-8053-f3245e8e322c.png)
![unknown (3)](https://user-images.githubusercontent.com/19767654/57576319-65f86b00-7422-11e9-89e2-5bc24bdfcdb9.png)
But it looks like it normally does from underwater:
![unknown (4)](https://user-images.githubusercontent.com/19767654/57576321-6bee4c00-7422-11e9-85c9-89b2790823f1.png)
even while the glitch was happening.

Or, like it normally does with these settings.

If I just turn ocean planar reflections back on nothing happens. But if I stop it, turn ocean planar reflections on, and run it again, I can't get the issue to appear again even after 5 or 10 minutes when it happened in seconds with ocean planar reflections off.

Sorry I can't recreate the problem with the ship - but for reference, it happened whenever the camera was looking down from a pretty high angle, and it looked exactly, shader-wise, as the bugged ocean does. Solid white like that. But ever since I turned on the planar reflections the problem went away, and even turning them off I can't seem to recreate it.

**Comment by huwb** [comment]
Thanks for writing this up! Looks vaguely familiar.. hm..

Is this rendering in gamma space or linear?

**Comment by huwb** [comment]
I think i understood from the discord that you were using gamma. Unfortunately gamma is not a focus or priority for me and is not something I've tested in.

I'll close but if I've misunderstood let me now.
