### ISSUE TITLE
[LWRP] Ocean Depth Cache issue . 

### ISSUE THREAD

**Issue by VizzzU** [huwb/crest-oceanrender#248]
**Describe the bug**

The depth cache don't work . ( Terrain layer has no effect but no error thrown )

**Screenshots / video**

I will add a short vid when i will have time , ok . ^^

**Versions**

(Wait , there will be a HDRP version soon ? ... ^^)
[LWRP] reproducible in unity 2019.1.0f2 and 2019.1.1f1

**To Reproduce**

- Create a new LWRP project . 
- Import Crest 1.6.
- Add a LightWeightAsset (with following options : Depth Texture ON/ opaqueTexture ON , Hdr ON , cast shadow for principal light and additional lights ON , soft Shadows ON , mixed lighting ON . ) in the graphics settings .
- Create a Custom ForwardRender  with Crest's ShadowPass added and assign it to the previously mentionned LightWeightAsset ( in the tab : "Renderer type : custom" ) 
- Open Main scene , enable shadows , create Terrain layer , hope for it to work and be disapointed . 

**Platform**

 - Both editor and build 
 - Windows10 64 bit . 

**Additional context**

 I am flooded by my personnal work so i am maybe missing something evident .

**Comment by huwb** [comment]
Thanks a lot for writing that up.

I was able to repro this using your detailed steps and I spent some time trying to fix it, but wasnt able to. I tried a number of options but didnt have any luck so far. I need to think about what my next move is.

**Comment by huwb** [comment]
Surprisingly the "new project" part seems to be a key part of the repro - i cant reproduce this in my usual development project :/. i wonder why..

**Comment by huwb** [comment]
Ok after comparing the two it looks like "Dynamic Batching" specifically is breaking it. Could you please try with this option disabled?

![image](https://user-images.githubusercontent.com/939901/57982721-30b2d500-7a41-11e9-9b74-7bfc8e004980.png)

I'm not suggesting this is a great solution but its a good lead, and perhaps a temporary workaround.

**Comment by huwb** [comment]
Ok i think i've made a breakthrough. The version of LWRP seems to be key.

On 2019.1, with LWRP 5.13.0, I am unable to break the depth cache. I toggled all of the above options and i can't break it (even the Dynamic batching). Could you try on 5.13.0 (using the package manager). Thanks!

(I've updated the issue template to get the srp version specifically.)

**Comment by VizzzU** [comment]
Wow , you are even providing a sunday support ! Amazing .
will have a try when i m back at home . Thx a billion

**Comment by VizzzU** [comment]
It is working now . Just updating the SRP version seems to solve the problem . Are you Neo , the choosen one ? ; )
