### ISSUE TITLE
Shadows do not appear on Ocean Surface

### ISSUE THREAD

**Issue by TKDHayk** [huwb/crest-oceanrender#250]
Shadows are enabled on Ocean Script, Ocean material, and my light. I'm using Forward Rendering. No Errors in the Editor Log

**Screenshots / video**
![Desktop Screenshot 2019 05 16 - 14 32 08 79](https://user-images.githubusercontent.com/22510633/57880654-48921b00-77ed-11e9-9df6-45def15b6c11.png)
![Desktop Screenshot 2019 05 16 - 14 32 59 06](https://user-images.githubusercontent.com/22510633/57880661-4c25a200-77ed-11e9-9efc-f44ea7f4aba0.png)
![Desktop Screenshot 2019 05 16 - 14 34 01 20](https://user-images.githubusercontent.com/22510633/57880663-4def6580-77ed-11e9-8e40-40105bff1099.png)
![Desktop Screenshot 2019 05 16 - 14 41 33 70](https://user-images.githubusercontent.com/22510633/57880666-4fb92900-77ed-11e9-857c-d8ec9303234b.png)

**Versions**
I'm using unity 2018.3.8 and Crest release 7.0, built-in pipeline.

**Platform**
 - Editor + standalone?
 - Windows 10

**Comment by KellanHiggins** [comment]
Same here. I am using Unity 2019.1.2

**Comment by jjxtra** [comment]
Possibly related to #251

**Comment by jjxtra** [comment]
A more extreme example with latest master branch, all shadowing options enabled and shadow distance of 1K. There is a giant cube in the sky. Should be shadowing the entire ocean and definitely should be no specular or scattering.

![image](https://user-images.githubusercontent.com/1271832/57974342-ef082880-7973-11e9-84d1-815c9de6d479.png)

**Comment by jjxtra** [comment]
Doing further tests, if I make a cube and attach to the player camera I can see the cube shadow on the water, but specular and scattering is not reduced enough, handled in pull request #251

**Comment by huwb** [comment]
There is a setting to control how soft the scattered shadows are. I just made this case by setting the shadow colour to red and reducing the jitter on the soft shadows:

![image](https://user-images.githubusercontent.com/939901/58019080-94e69f00-7afc-11e9-8c22-8da37c0e38a1.png)

The hard shadowing also has a jitter amount which will affect the specular.

@jjxtra powered up the shadow values in one of his commits in #251 above which you guys could use if you like, but for crest i intend to use shadow values the way they are now, with the setting shown above to give control.

**Comment by huwb** [comment]
Added a note about this in the shadow section of the user guide in the above commit

**Comment by huwb** [comment]
Oops misclicked..

**Comment by TKDHayk** [comment]
The problem resolved for me. On my end, the issue was seemed to be that the lighting of the ocean was  be baked on the lightmap data. Deleting baked lighting data seemed to fix the issue. Although I also changed lots of other settings, so I can't be sure if that was the problem.
