### ISSUE TITLE
Directional Lighting and Shadows Issue

### ISSUE THREAD

**Issue by jjxtra** [huwb/crest-oceanrender#251]
I've only tested the github version with this problem. This is the specular bug that I mentioned in the discord.

The directional light calculations do not apply enough shadows. For example, in a even slightly shadowed area, there should be no specular. In a more shadowed area, there should be no directional light shadowing.

My fixes are this:

In OceanEmission.hlsl, use shadow to the 3rd power, i.e. shadow = pow(shadow, 3.0). Putting this in the _SUBSURFACESCATTERING_ON #if fixes scattering to look correct in shadows, i.e.:

```
#if _SUBSURFACESCATTERING_ON
	{
#if _SUBSURFACESHALLOWCOLOUR_ON
		float shallowness = pow(1. - saturate(depth / _SubSurfaceDepthMax), _SubSurfaceDepthPower);
		half3 shallowCol = _SubSurfaceShallowCol;
#if _SHADOWS_ON
		shallowCol = lerp(_SubSurfaceShallowColShadow, shallowCol, shadow * shadow * shadow);
#endif
		col = lerp(col, shallowCol, shallowness);
#endif

#if _SUBSURFACEHEIGHTLERP_ON
		col += pow(saturate(0.5 + 2.0 * waveHeight / _SubSurfaceHeightMax), _SubSurfaceHeightPower) * _SubSurfaceCrestColour.rgb;
#endif

		// light
		// use the constant term (0th order) of SH stuff - this is the average. it seems to give the right kind of colour
		col *= half3(unity_SHAr.w, unity_SHAg.w, unity_SHAb.w);

		// Approximate subsurface scattering - add light when surface faces viewer. Use geometry normal - don't need high freqs.
		half towardsSun = pow(max(0., dot(i_lightDir, -i_view)), _SubSurfaceSunFallOff);
		col += (_SubSurfaceBase + _SubSurfaceSun * towardsSun) * _SubSurfaceColour.rgb * _LightColor0 * shadow * shadow * shadow;
	}
#endif // _SUBSURFACESCATTERING_ON
```

In OceanReflection.hlsl, also use power of 3 in the _COMPUTEDIRECTIONALLIGHT_ON section, i.e.
```
#if _COMPUTEDIRECTIONALLIGHT_ON
	skyColour += (pow(max(0., dot(refl, i_lightDir)), _DirectionalLightFallOff) * _DirectionalLightBoost * _LightColor0 * i_shadow * i_shadow * i_shadow);
#endif
```

**Comment by jjxtra** [comment]
Sent a pull request with the changes

**Comment by VizzzU** [comment]
I wish i see the matrix like you guys . I will have a try to your fix this morning , thx !

**Comment by jjxtra** [comment]
Hi there! Do you have any idea why the water in the far distance is still bright even when in shadow?

**Comment by huwb** [comment]
hi guys, I think these are all covered in the PR #254? if so lets move the conversation there, i'll keep the PR open until we're happy with it.
