### ISSUE TITLE
Auto-Detect primary dir light

### ISSUE THREAD

**Issue by jjxtra** [huwb/crest-oceanrender#252]
If primary dir light is null, auto detect the brightest dir light. If the dir light no longer is the brightest dir light, switch to the current brightest dir light. Think sunset and moonrise.

**Comment by huwb** [comment]
Hi i think you were going to show me some example code. maybe i missed a link apologies if so.

I imagine you're doing a findobjectsoftype() to grab dir lights? I'm still slightly on the fence, theres a warning for it not being assigned, so its usually an easy bit of config. unless there are usage patterns where this is really annoying.

**Comment by jjxtra** [comment]
using System.Linq;

/ ...

// if primary dir light is null or some settings says auto-detect primary dir light, do this...
foreach (Light dirLight in Light.GetLights(LightType.Directional, 0).OrderByDescending(l => l.intensity))
{
    break;
}

**Comment by huwb** [comment]
Nice linq code :). i really need to learn to become a real c# programmer! Also didnt know about GetLights().

Closing for the reasons above - don't think i want to make this happen under the hood, will keep it explicit and see if i get feedback that its a problem to do it this way. But thanks for the proposal and good to have this to refer back to.
