### ISSUE TITLE
Ocean tiles sometimes missing a row of polys

### ISSUE THREAD

**Issue by strich** [huwb/crest-oceanrender#26]
There appears to be an edgecase based on camera location that can cause some tiles to be missing their border:

![image](https://user-images.githubusercontent.com/987896/41202141-ef399cf4-6cbc-11e8-91d1-89e5cf2777cd.png)
![image](https://user-images.githubusercontent.com/987896/41202168-20a6c47e-6cbd-11e8-99d3-9597212d12b9.png)

Setting 'uniform tiles' fixes it.

**Comment by huwb** [comment]
Thanks for reporting! I'm pretty sure this bug has been lurking some time but was rare enough to evade my focus until now. This fix should sort it. Let me know/reopen if not!
