### ISSUE TITLE
Underwater completely black

### ISSUE THREAD

**Issue by taylank** [huwb/crest-oceanrender#260]
Everything below the water level is black. Tested this with own scenes as well as the main demo scene that comes with Crest, in the editor (standalone). 

![image](https://user-images.githubusercontent.com/4481766/58374709-841c9b80-7ef7-11e9-96d2-a5c073154fbd.png)

![image](https://user-images.githubusercontent.com/4481766/58375052-373cc300-7eff-11e9-8e39-d7712f352d37.png)

Not getting any errors in the editor. This specifically became an issue after installing and later uninstalling lwrp. Pre-lwrp still had this happen every once in a while, but now it's happening 100% of the time. I'm using 2019.1.3

**Comment by taylank** [comment]
OK I think I solved the issue, In case anyone else finds themselves in the same predicament after trialing and uninstalling lwrp: quit Unity, delete your Library folder, and reopen the project

**Comment by huwb** [comment]
Yep often find myself having to do the same..
