### ISSUE TITLE
Underwater curtain obscures EnviroSky clouds above water

### ISSUE THREAD

**Issue by ibbybn** [huwb/crest-oceanrender#261]
EnviroSky is correctly rendered from underneath the water surface as you can see here:
![CrestWithEnviro_1](https://user-images.githubusercontent.com/35241291/58494064-8d666c00-8174-11e9-9cdf-d9e9c197101f.jpg)

When going above the water the clouds are not seen anymore:
![CrestWithEnviro_2](https://user-images.githubusercontent.com/35241291/58494084-935c4d00-8174-11e9-9a71-511d5d2e5c7b.jpg)

Only when changing "Max Height Above Water" to 0 will they show again but then the curtain doesn't render under the water either.

I updated to the latest master here ( has been a while ) and there were no changes on EnviroSkys side so something in the way the underwater curtain is rendered must've changed here?
Any idea where I could start poking in the code to find a cure? When I look straight up above the water I can see the clouds again btw.

Render pipeline: built-in
Unity 2019.1.4f1

**Comment by huwb** [comment]
Err ok that's odd! So in screenshot 2 above, if you disable the underwater prefabs under the camera, it goes away? 

While in screenshot 2 view, could you enable wireframe on the ocean debug gui if you have it handy?

**Comment by huwb** [comment]
I don't recall huge changes to the underwater stuff recently..

**Comment by ibbybn** [comment]
Ah, found the problem. No need for the wireframe pic anymore. 
I have the ocean transform.position.y under 0 in some levels. But the underwater curtain apparently only disappears when going with the camera above that.
I'll just set the ocean to y = 0 in all levels for now.
