### ISSUE TITLE
Boat probe use only one collider

### ISSUE THREAD

**Issue by CorneliusGoobles** [huwb/crest-oceanrender#266]
I'm trying to create a boat using the boat probe, and it all works fine as long as I only have a single capsule collider. I'm trying to use a non convex mesh collider for character collisions on top of the boat, but I don't want it to affect the boat probe. Is there a way to have the boat probe ignore my mesh collider and only use the capsule?

Right now as soon as I add the mesh collider the boat flips out (maybe because of the non convex shape) but I don't want the mesh collider to affect the simulation at all.

**Comment by huwb** [comment]
Hi, i think perhaps using Layers is the approach for this? I'm not an expert in these matters but I think putting two colliders in different layers means they won't interact.

**Comment by VizzzU** [comment]
Hi there ! Take a look at the Crest's discord channel , a guy nicknamed CritterCove is using Crest in this way (i mean characters on a big boat) , he is very friendly do not hesitate to ask him his pipeline i guess he would answer to you .

**Comment by huwb** [comment]
Closing for now, let me know if it should be reopened
