### ISSUE TITLE
KeyValuePair does not contain a definition for Append

### ISSUE THREAD

**Issue by hedgefield** [huwb/crest-oceanrender#270]
Hey there, I love the Crest system, but I'm having trouble working with the latest version from the repo (cloned today). Any thoughts?

**Describe the bug**
> Assets/Crest/Crest/Scripts/Reflection/OceanPlanarReflection.cs(61,18): error CS1061: Type `System.Collections.Generic.KeyValuePair<int,UnityEngine.RenderTexture>[]' does not contain a definition for `Append' and no extension method `Append' of type `System.Collections.Generic.KeyValuePair<int,UnityEngine.RenderTexture>[]' could be found. Are you missing an assembly reference?

**To Reproduce**
I moved the Crest folder from the Assets folder of this project to the Assets folder of my project.

**Versions**
Unity 2019.1.0f1, Built-in RP.

**Platform**
Editor on Windows 10.

**Additional context**
It doesn't happen if I open the repo clone directly in this Unity version, only when importing into an existing project. Some kind of conflict maybe?

**Comment by huwb** [comment]
Thanks, this might be the scripting runtime, i think its in the player
settings in unity. It needs to be 4.x.

https://docs.unity3d.com/Manual/ScriptingRuntimeUpgrade.html

**Comment by hedgefield** [comment]
Was just about to post this too - I went through all the project settings and first thought it might have to do with script execution order, but then I noticed the .NET setting being 3.5 still because it was an older project. Setting it to 4.x fixed it.

Thanks!
