### ISSUE TITLE
Realtime planar reflections?

### ISSUE THREAD

**Issue by Rbn3D** [huwb/crest-oceanrender#31]
Hi,

First of all, thanks for maintaining such a great project. 👍 

It is possible to use dynamic planar reflections on the ocean renderer instead of the static skybox? So dynamic/static objects in the scene can get reflected on the water. I think it can increase the realism of the simulation.

Any ideas on how to do this?

Thank you.

**Comment by huwb** [comment]
Thanks for getting in touch Rbn3D :)

There has been a bit of discussion about this. It's a bit of a long thread but if you're feeling game you could read this: https://github.com/huwb/crest-oceanrender/issues/4

I think the summary looks something like:

* Planar reflections is definitely possible, and might be a good path forwards. The Advanced Water in the unity standard assets is a good example of this - it sets up a camera with a clipping plane to render the reflected view of the scene each frame. It seems to be elegantly implemented. It can work well when the water is calm. When the water is very wavey it is more challenging as a varying surface height starts to violate the "planar" assumption! I believe with some fudging it may be possible to get a reasonable result this way, perhaps by setting the reflection plane height to the lowest expected wave height, or something like that. A disadvantage is the cost of rendering the world a second time each frame, but this extra pass is not unheard of in games though, and if perf is an issue one might selectively render LOD'd terrain only at a low res, etc. I have been interested in trying planar reflections in crest but havent got around to it. I'm interested in how much code it requires and how elegantly it fits into existing crest stuff.
* Screen space reflections - I believe these are included in the unity post processing stack. But i have no idea what is required to enable them to work, I have not got around to trying them yet. Once again, I'd be interested to hear any experiences here!

Does that make sense?

**Comment by Rbn3D** [comment]
Yes, I will take a look into Advanced Water from standard assets and see if I can port it to crest...

My simulation is a little wavey, so I don't know if it will really work well, but maybe taking the normal of the waves into account and distorting the RenderTexture accordingly could work, just like normal map does...

Thank you again!

**Comment by Rbn3D** [comment]
I managed to implement planar reflections by modifying the ocean shader and using a modified WaterAdvanced script!

However, the reflection shows some squares/seams on the water surface (looks like i'm applying the normals wrongly), most noticeable when the boat is stopped and the water mostly calm.

Also, looks like the reflection stutters, even updating the Render texture every frame. Looks like it skips the Render texture some frames. I have no idea why...

I modified the shader this way:

(Added ref to v2f, just like WaterAdvanced)
```
struct v2f
	{
		float4 vertex : SV_POSITION;
		float4 ref : TEXCOORD0;
		half3 n : TEXCOORD1;
		half4 foam_screenPos : TEXCOORD4;
		half3 lodAlpha_worldXZUndisplaced : TEXCOORD5;
		float3 worldPos : TEXCOORD7;
		#if _DEBUGVISUALISESHAPESAMPLE_ON
		half3 debugtint : TEXCOORD8;
		#endif
		half4 grabPos : TEXCOORD9;

		UNITY_FOG_COORDS( 3 )
	};
```

```
	v2f vert( appdata_t v )
	{
           // .....
           o.ref = ComputeNonStereoScreenPos(UnityObjectToClipPos(v.vertex));
           // .....
        }
```
The reflection is rendered like this:
```
	half3 frag(v2f i) : SV_Target
	{
           // .....

	  // Reflection
	  half3 refl = reflect(-view, n_pixel);
	  //half3 skyColor = texCUBE(_Skybox, refl);

	  float4 uvRefl = i.ref; 
	  uvRefl.xyz += n_pixel;

          half4 skyColor = tex2Dproj(_ReflectionTex, UNITY_PROJ_COORD(uvRefl));
          // .....
         }
```
I would appreciate any idea that could point me in the right direction.

Thank you.

**Comment by huwb** [comment]
Nice!

I do have a couple of ideas that come to mind for now:

Where did you insert that line that computes o.ref? I think it needs to be at the end of the vert shader, after the ocean verts have been processed. There is a similar line that packs the screenpos into o.foam_screenPos.yzw:

o.foam_screenPos.yzw = ComputeScreenPos(o.vertex).xyw;

I think your new line belongs in this area near the bottom of the vert shader. In fact, I'd be tempted to actually try using one of the existing values that is being computed - the reflection will look wrong but I'd be interested if you see the square artifacts or the glitching.


Is the glitching happening when the camera is moving around or is it stationary?

If you could attach a image of the result that could be useful as well, i might recognize an issue or it might give me a lead.

Besides that, I could jump in and take a look myself. An option could be to fork Crest and push a new feature branch which i can then pull and look at on my side.

**Comment by Rbn3D** [comment]
![imagen](https://user-images.githubusercontent.com/4525805/43474395-0a334880-94f3-11e8-89e7-e7fd6ffc7b21.png)

There is a quick screenshot of the scene.

You are right, o.ref it's done at the bottom of the vert shader.

The stuttering, (I'd call it low update rate of reflection or something like that), it's mostly noticeable when the camera or the boat itself moves around. The ocean runs pretty fast on my machine, but the reflection it's not updated the same, looks like it's skipping frames.

I'll try to prepare a pull request, but my project needs some cleanup (I'll push one as soon as I get it tidy and remove some off-topic stuff!)

**Comment by Rbn3D** [comment]
I've prepared a pull request showcasing this.

**Comment by Rbn3D** [comment]
I discovered the reason of the stutter:

The renderTexture is updating just fine. The problem is that the position (transform.position) of the ocean changes over frames. 

If I set a position constraint that locks the ocean position to some gameobject that don't moves, the reflection renders stops glitching (Altought other issues appears due to the constraint).

**Comment by huwb** [comment]
Hey there,

I finally had a chance to look at this. It's looking pretty cool! I know it falls over a bit for big waves, but I'm surprised how well it holds up so far. I think theres some interesting experiments to do with varying the reflection plane position based on camera subject to hide the worst of the issues..?

Anyway, I fixed a few of the issues. I split up the changes into commits with descriptions so you can browse them and let me know what you think. The result is close(r), but not jitter free yet. The remaining part is update order which im confident can be fixed.

It looks like I pushed the commits to YOUR fork/repos. I had no idea i could do that..! I hope you don't mind. I think i should have merged in your PR and then pushed to my repos. However this seems like a convenient way to iterate for now - maybe this is a feature of git? My git skills/knowledge are falling a bit short here.

So i'll let the stuff so far settle in my mind and will see if i can come back to this in the next days. Let me know if you have thoughts. Thanks for kicking this off!

**Comment by Rbn3D** [comment]
Cool! Can't wait to try this out! 

I don't mind about the commits being pushed to my fork (it's a feature of github, If someone open a pull request against your repo, the autor and you can share the pr branch). Is a good way to iterate, so no problem.

Hopefully tomorrow I can try this out and post something back.

Thanks again!

**Comment by Rbn3D** [comment]
Wow, this is working pretty well!

I've followed your suggestion with a minor change, please take a look at the comment:
https://github.com/Rbn3D/crest-oceanrender/blob/planar-reflection/src/unity/Assets/Crest/Shaders/OceanPlanarReflections.shader#L367

Does it make sense?

Looks like all the issues have been fixed, even the clip plane thing!

Only two things we might want to address:

* The reflection doesn't "follow" the game camera instantly when it is stopped but rotating quickly.
* The directional light specular highlight isn't occluded by reflected objects. (This one is harder to fix as it requires to distinguish between the skybox and the rest of the objects, by using a depth buffer or something like that)

I'm now trying to solve the first one, but still no clue about what causes it.

Many thanks for your help 👍

**Comment by huwb** [comment]
Sorry i have not managed to get back to this :( its very close to the top of my list!!

**Comment by Rbn3D** [comment]
It's fine!

Thanks for your help on this. 👍

**Comment by huwb** [comment]
I just worked on it a bit more. I changed the way the script works - it now should be attached to the camera its reflecting, and it takes the reflection plane from the ocean position. This has simplified the logic and cleaned a few things up.

I think its at a point where its working now - I'm not aware of any issues now except the case when waves deviate from the plane which breaks the reflection which is expected. I've experimented a little bit with offsetting the reflection based on water height to try to combat this issue, i have a couple more things to try here to see if i can address the problem.

Besides that with a bit more cleanup i think it could be in good shape to merge into master which is cool.

**Comment by huwb** [comment]
Ok that was a fun diversion - after experimenting i think it is possible to hack approximate reflections that work in wavy conditions, but im not confident yet that it will be good enough to use in production.

The idea is to use planar reflection, but warp the world around it to the shape of the ocean. A reflection proxy object is rendered, and is offset by the negated wave height, so that it is clipped at the right height (so if the object is above the plane but the wave is also above the plane, it will still cut the object at the right point). I added a reflection proxy shader which samples the wave heights and offsets the verts accordingly (just for the proxy).

Then a similar fudge is done in the ocean material - when it samples into the reflection texture it offsets a bit to compensate for the water surface not being flat. This part is quite hacky and is just a fudge at the moment, but i think it can be made principled and perhaps quality can be increased.

The result looks like this at the moment:

https://drive.google.com/open?id=1CIOmMmMY_kTGyuNEFPCSLQ-8cdeRVZN8

It requires reflection proxy objects to be created (which have the vertex offset described above), and to make this render I created a new layer for reflection proxies. I'm guessing this will cause issues for people due to layer scarcity and/or objects needing to be in existing layers, but this can be addressed down the line with tags etc i think.

I'm probably going to park this here and get back to getting planar reflections merged into mainline. Let me know if you have thoughts and if you might be interested in using this approximate reflection stuff.

**Comment by huwb** [comment]
Oh sorry i just read your question - yes i think we can integrate planar reflection into the ocean shader on a switch like the other features. The tradeoff is the ocean shader is quite long, but ill look at breaking out different parts of the ocean shader into separate files which should help with this.

**Comment by huwb** [comment]
I merged it all in! I tried to merge first from master into the branch but there were a LOT of changes which were tricky to go through - in the end i decided to just merge the branch into master by hand, which means I could not do it through the PR, apologies.

To turn it on, tick the Planar Reflections option on the ocean material, and add a OceanPlanarReflections script to the main camera.

Let me know if you get a chance to try it out and if you have thoughts about the above. Thanks for working with me on this!

**Comment by huwb** [comment]
On the fake reflections for wavy oceans, i've made and improvement in the commit referenced above (moved to a new branch called feature/wavy-planar-reflections2). Before the reflection only moved up and down which looked wrong when the waves were not flat. Now i've added a horizontal shift to the reflection proxy based on normal so the reflection moves around in a plausible way depending on waves.

Current capture: https://drive.google.com/open?id=1vSqHSpX7IyWxOsisyLFq6ZjQwLmjiQJU

It's still a bit hacked but I could clean it up if its something you think you will use, let me know.

**Comment by Rbn3D** [comment]
Hi,

Looks nice in the video! As soon as I can, I'll try this!  (Hopefully in a few days)


Thanks for working on this.

**Comment by Rbn3D** [comment]
I'm back! I'm going to test this later today and post something back!

**Comment by Rbn3D** [comment]
Finally tested this and it's looking pretty cool. I still have to merge it fully into my project but looks nice in the demo, even when the ocean is not so planar ;)

My only throught is that the reflection distort intensity is no related to the distance of the reflected pixel on the ocean surface, so it doesn't give proper "feeling of depth". Ideally, normal intensity would be multiplied by the distance of the reflected point on the water.

I know this it's probably out of the scope for this project, and requires some research and time. Also it could require render the depth of the scene, which may have a negative impact in performance... 

So for me, this issue can be closed. Maybe we can create another issue to try to address that, at some point.

Thanks for your work again.

**Comment by huwb** [comment]
Yeah its a good point. I messed around with making the normals influence stronger, but the reflected rays can easily go outside the reflection texture which is another problem. Could perhaps be addressed by over rendering / rendering with a wider FOV.

I think tracing the ray properly would basically amount to SSR which I'm interested in but it feels outside the scope of what i could take on myself. Also after doing a quick google now im reminded of the challenges with SSR and transparents. It would have to either render a gbuffer especially for the ocean surface, or do SSR in the ocean shader which could get very expensive.

As you suggest, I think i'll call it a day here and close this issue and leave it for future work, or see if anyone has anything new to add to the mix.
