### ISSUE TITLE
Nan's in dynamic sim textures (and a hacky fix) _SimDeltaTimePrev=0

### ISSUE THREAD

**Issue by dizzy2003** [huwb/crest-oceanrender#34]
The three boats demo scene worked fine for us, but when we tried the same dynamic sim in our game, the highest detail lods vanished.

After tracking things down it seems _SimDeltaTimePrev is 0 on the first game turn for us

I'm guessing some update order has our scene running a game turn with a zero value  

this line float v = (ft - ftm) / _SimDeltaTimePrev;

generate's  NAN's and because the sim is a feedback system Nan's propagate forever..

adding 
_SimDeltaTimePrev = max(_SimDeltaTimePrev, 0.0001f); 

before its used to ShapeSimWave.shader fixed it for us.

**Comment by huwb** [comment]
Oh man!! Ok.. thats a bit confounding.

I can't right now see how/why it would render before an update. CreateSim should create all the stuff during updates, and all updates should happen before render..

I'm also a little concerned that there's also a divide by 'dt', which is a shorthand for _SimDeltaTime, which may suffer from the same issue.

I pushed your fix for now. I'll leave this open for now to wait for any reoccurrences.

**Comment by huwb** [comment]
I added additional protection against the current dt being 0 and resolved this for now.
