### ISSUE TITLE
Dynamic Waves and time scale

### ISSUE THREAD

**Issue by Midda-C** [huwb/crest-oceanrender#38]
It appears as though the force applied to the ocean continues to accumulate if Unity's timescale is set to zero.  We use the numpad for setting the time scale for debug purposes (5 = %50, 1 = 10%, etc), and we noticed that if we're interacting with the water and pause the game by setting the speed to 0, the ocean will explode with tidal waves when we unpause.

A simple way to replicate this is in the threeboats scene, press play, and while running, open the Time Editor (Edit > Project Settings > Time) and set the time scale to 0.  Wait a few seconds, then set it back to 1.  You should see all the wake from the boats go a bit crazy.  The longer it's paused, the crazier it'll be.

On a related note, I have also noticed similar behaviour if there are hitches in the framerate while playing, where the dynamics will suddenly be very strong after a breif (e.g. 0.5 sec) hiccup.  I assume this is the same issue?

**Comment by Midda-C** [comment]
One of the coders on our team has found that this is still happening at very low time-scales (which he often uses for debugging).  I just repro'd the issue on my machine to.  We're seeing crazy dynamics at time-scales of 0.04x or less (but completely paused is fine).

Any ideas on what might be happening there?

**Comment by huwb** [comment]
Ah ok im seeing the same thing here. I changed the approach slightly, it should now go all the way down to 0 ok. However going back up seems to add loads of energy to the system. Maybe this behaviour ok-ish for debugging. I could not get to the bottom of why this is happening, the dts seem ok.

If the remaining issue is a blocker then lets reopen this issue - let me know.

**Comment by Midda-C** [comment]
I just grabbed latest data, and the issue is still present.  In fact, it seems to be back to occurring even when paused, though to to the degree it originally did.

We're not planning to set the speed this slow during our actual game (outside of pausing), so it's not a show-stopper, but one of our programmers does frequently set things this low when debugging things like player movement and such, and currently he just has to disable all of the dynamics.

If you're having trouble reproducing it, let me know if there's anything I can provide to help.
