### ISSUE TITLE
Wave speed or gap

### ISSUE THREAD

**Issue by holdingjason** [huwb/crest-oceanrender#41]
Is there away to control the speed of the waves or frequency between them?  Right now I can play with the equalizer but the wave frequency speed stays the same between them.  I am talking between generated waves at the same level.  I see that I can turn off or lower waves in the equalizer that would create gaps but that only works with larger waves following smaller waves which is not what I want.

Think a shore shot with lazy small waves drifting in slowly with large gaps between them.

**Comment by Midda-C** [comment]
Yeah, I've thought about this too.  The ocean is always moving in its set direction at a constant speed, as are the scrolling textures.  Having some extra control over the speed would be great.

**Comment by Midda-C** [comment]
Me too, I was mostly just talking about the speed that the wave moves.  Essentially just like the time-scale for a given octave.  Might need some way to control the speed of the textures too?

I hadn't considered driving the weight with animation curves before.  That could be interesting (should be easy to do as-is, Unity is pretty good about letting you animate pretty much any exposed value).

**Comment by huwb** [comment]
Yeah let me know about how animating goes, I want this to be well supported.

Ok that makes sense. I was hesitant to add per octave chop but if we're going to add per octave data it might make sense to add both.

**Comment by huwb** [comment]
I've added a per octave speed scale in the reference commit. I think its pretty cool actually. You can set it to 0 to freeze one or more octaves which is kinda fun. 

The new options are tucked away behind the Advanced Settings toggle on the ocean wave spectrum, on the *feature/per_octave_settings* branch for now. These changes will add a small extra expense so it would be good to confirm this is useful before committing to master.

**Comment by huwb** [comment]
In #18 @Midda-C asked about exposing a global wave speed control.

I've decided to tie everything to gravity (the wave speed is computed in part from gravity - more gravity means faster waves). Doing it this way ensures global consistency in the world, but I've also added overrides at multiple levels:

* The ocean system takes the gravity value from the physics settings
* It has a global gravity multiplier in the OceanRenderer script. This global setting will affect both dynamic wave sims and the gerstner waves.
* There is a gravity multiplier on the wave spectrum that will affect all wave octaves
* There is a per-octave gravity multiplier

So at the highest level you can override the gravity and you'll get consistent behaviour in both dynamic sims and the gerstner waves, but you can override at multiple levels, down to per-octave granulariy.

**Comment by huwb** [comment]
I believe this is resolved on master, in the commit referenced above. Let me know if you see issues!

**Comment by Midda-C** [comment]
> Yeah let me know about how animating goes, I want this to be well supported.

Just thought I'd let you know that I finally remembered to try this out, and as expected, it works fine.  All of the exposed parameters are available in the animation editor, and fading the weight in and out works perfectly. :)

**Comment by huwb** [comment]
@Midda-C are you able to animate the wave spectrum - like the power values for each wavelength?

I could not work out how to do it - i can animate params on the ShapeGerstnerBatch script, but not in the spectrum.
