### ISSUE TITLE
WIP Video - Underwater, Enhanced floating objects, boat, swimming.

### ISSUE THREAD

**Issue by holdingjason** [huwb/crest-oceanrender#45]
Since we are always asking for stuff I figured it would be nice to show you what we are doing with your fantastic system.

You can make the ocean shader work underwater by simply adding 			

Cull Off

The floating objects use physics force projections based around water density.  The boat uses a modified version of https://assetstore.unity.com/packages/tools/physics/dynamic-water-physics-89928

Video
https://drive.google.com/open?id=13MiePsUzK98vzDywiVFXvuXGYZ_jXxOg

**Comment by huwb** [comment]
Thats super cool, thanks so much for sharing!!

It's got an awesome feel and the underwater works really well! I've never attempted underwater before, I'm impressed with what you guys have done there.

In perf critical situations, if you had lots of overlapping waves, Cull Off might be a concern, as it would could mean both fronts and backs of waves were drawn. It would be possible to have two variants (one cull back and one cull front) and switch between them. However for your case i dont think it would be worth the complexity. Just mentioning it though!

Thanks again, I feel honored that Crest is finding practical use and helping to create awesome experiences like the video you posted!

**Comment by huwb** [comment]
I will close this as I'm trying to minimize open issues, and you probably don't want WIP footage being pinned in the top issues forever! Oh I see the link is a 404 now anyway so definitely makes sense to close.

At some point I should make a "projects using crest section" to showcase work like yours. Let me know if this is something you and your team would be interested in at some point.

**Comment by holdingjason** [comment]
@huwb Yes I think that would be great to setup a projects using area.  We would definitely like to post so stuff and see what others our doing.  Might be a good place to see how Crest is being used in different ways so we can share information among the community, how we did certain things etc.

BTW been out of town etc so sorry have not been replying much to the various threads but I have been following them and your doing a great job which our team is very appreciative of.
