### ISSUE TITLE
Skybox in shader vs in lighting.

### ISSUE THREAD

**Issue by holdingjason** [huwb/crest-oceanrender#46]
Right now we are setting the skybox in the shader.  This works fine for static skyboxes but curious how this would work with something more dynamic like AzureSky (which we use) that is set and adjust on the fly in the skybox material under lighting.  Since the skybox is updates constantly, ie sun moving across the sky, clouds etc would be interesting to have this effect the ocean as well.  I will try and do some research into this as I have seen this same type of question pop up in other ocean packages.

**Comment by holdingjason** [comment]
Thanks that helps @Midda-C .  Will give that a go on Azure and see how it looks.

BTW what project are you working on, if your letting the public view it yet that is.  Just curious always interested to see how other as using the same tools.

Thanks

**Comment by Midda-C** [comment]
I'm glad that my rambling is helpful in some way!

I'd love to show a bit of our project, but we're currently in talks with a publishing partner, so we're unfortunately not really able to share much publicly just yet.

I'll be sure to share when I can, though! :D

**Comment by holdingjason** [comment]
No problem.  Please do and good luck.

**Comment by huwb** [comment]
That's disappointing that the skybox is causing you so much trouble @Midda-C . Now that we've won a bunch of battles with other crest issues/features over the last weeks i think i'll have some headspace to ponder this and I'll post back with thoughts later. perhaps we can discuss here.

**Comment by Midda-C** [comment]
No worries.  I believe it's a pretty common sticking point with most ocean solutions, given the age-old problem of anything with reflections in realtime.

Perhaps an easy workaround could be the option to choose between either the current skybox texture, or a couple colours (one for the horizon, and one for the sky, making a gradient) which can be driven by the user?

**Comment by holdingjason** [comment]
That gradient idea is not bad.  Would not pick up any of the clouds etc but would probably be a decent work around.  Right now messing with outputting a cube map from the sky system ie AzureSky and then assigning that on the fly to Crest via the shader ala your method @Midda-C.

That might work but the ocean does seem very sensitive to darker skyboxes.  So not sure that works great.

**Comment by Midda-C** [comment]
Cool, I hope you get some usable results from that.

Yeah, a gradient isn't a very robust solution, it came to mind because I remember playing with Suimono water, and it had the option to just pick a reflection colour, which works okay if you don't have a lot of detail in the sky.  If you wanted to see the clouds, you'd still need something like screen-space reflections on top of that.

**Comment by holdingjason** [comment]
Well at least with a gradient you can get the nice sun to dark effect that will at least approximate what is going on in the scene.  Also lets you control the look without being totally dependent on the sky as I said it sometimes makes the water look to washed out etc.

**Comment by huwb** [comment]
Thanks guys. I'm not sure whether to go to code with the gradient idea - the alternative would be to just author a low res env map texture with the desired gradient in it which would work with the existing code and not require special code. It might be trickier to animate though if its baked into a texture.

Is that the idea - so you get three or four colours and you'll drive them with an animation that is keyed on the time of day? With the idea being that this is much more efficient than rendering a dynamic reflection probe?

**Comment by holdingjason** [comment]
Yes that is the idea at least for me anyway.  May allow for more direct control vs being dependent on the actual scene/skybox etc.  Sometimes that is to bright or to dark so you don't always want it to completely match what is going on in the sky but more of a approximation or suggestion of what is going on in the sky.  When I have tried doing either the reflection probes or creating a cubemap from the sky on the fly the water always looks washed out and loses a lot of its definition, right now I still use the standard skybox you provide because that is the only one that looks decent.  Need to do more research into that in case its more of an issue of how we are applying that cubemap/lighting to the ocean.  So honestly not sure gradient is the way to go because maybe there is other things at play that are the problem.

**Comment by Midda-C** [comment]
Sorry, completely missed the new responses in this thread.

> Is that the idea - so you get three or four colours and you'll drive them with an animation that is keyed on the time of day? With the idea being that this is much more efficient than rendering a dynamic reflection probe?

More or less, yeah.  We'd be fine with our current reflection probe hack if it didn't completely fail at night time (not because of Crest, just because the probe misses all of our screen effects and just returns black).  The gradient concept was just the first thing that popped into my head, so I'm not pushing it as a well-researched solution. :P

But, i _think_ it'd do the job?  Unity does have some built-in gradient stuff, but I've never seen it used directly on a material before, so I don't know if it can.

**Comment by huwb** [comment]
I think it would be pretty easy to try a simple gradient, even if it's a little hacky at first.

I wonder though if it will need some kind of heading/yaw/azimuth component as well, not just the altitude component. Without that you would get the same colour no matter what direction you face and where the sun/moon are.

I guess the logical extreme here is we are generating procedural sky colour, similar to the procedural sky in out of the box unity.

That feels like a rabbit hole though - if we have a specific idea of something to try then lets give it a shot. I start to doubt there is a one size fits all solution that works for everyone but we might get something that works for a good set of cases.

**Comment by huwb** [comment]
Hi guys, I've thrown in a simple gradient test to get the ball rolling - see the above commit and the new toggle and options on the ocean material shown in the screenshot below. The branch is feature/sky_gradient .

![image](https://user-images.githubusercontent.com/939901/44897389-65d09900-acf3-11e8-99a4-1c212f2472cc.png)

**Comment by Midda-C** [comment]
I just had a look, and it's definitely giving better results at night, it's just a matter of feeding in good colours.

You're right about the azimuth idea, though. I managed to pretty easily match the colours, but we get a nicer result during the day because the skybox isn't a constant value in every direction.  Here's an example (Open them each in new tabs to easily compare):

[Gradient Sky](https://user-images.githubusercontent.com/37893722/44899279-a9072800-ad44-11e8-8c55-5758dcb8951a.png)
[Probe Sky](https://user-images.githubusercontent.com/37893722/44899283-ac9aaf00-ad44-11e8-8ecb-2f57fca905ed.png)

Not that the gradient doesn't look good, but the reflection probe does achieve a more natural result.  But again, it does work better for us at night, so it's an improvement for us—especially if we can manage some way to seamlessly transition from the texture map to the gradient.

As an aside, I also noticed while testing this that the foam bubbles seem to be emissive?  Or they're not taking the light into account.  It's all glowing for us during the night.

**Comment by huwb** [comment]
Ahh thats actually pretty cool!! I think i "get it" now.

I know what this needs - ANOTHER GRADIENT :) . This is hacked in but i duped the gradient and added another one which is driven by the azimuth (so the handles are 0-1 values which are rotation around the y axis).

Its all super hacked in and i dont know if this will be manageable for you etc but thought i'd throw it over to you.

![image](https://user-images.githubusercontent.com/939901/44945283-bb817000-addd-11e8-864b-017a3b31ed23.png)

**Comment by Midda-C** [comment]
It's gradients all the way down!!!

I was able to get a pretty nice result with this.  It wasn't identical to the probe, but it looked just as nice—with the advantage of being more customisable.  However, it was pretty fiddly to configure.  I expect trying to manage it over a dynamic time of day, and under different weather conditions/biomes might be a bit of a nightmare.

Now, I'll preface this with a statement that I have no idea how simple or difficult this is from a mathematics viewpoint—but could the vertical/horizontal position of the azimuth be determined programmatically from the light direction?  The way I'm thinking about using the gradient would be something like:

- Vertical gradient essentially as it currently is.  Pick a few colours (maybe choose how many colours you want to use, between 2 and 4?), and adjust their respective altitudes.  

- Replace the Horizontal gradient with an azimuth colour, and a value to determine its falloff.

- Magic maths to blend it all together.

How does that sound?  Does that seem feasible, or is that just madness?  It feel like that'd be much easier to drive, as you could potentially have as few as three colours to pick.

Again, I'm just stating this from a user perspective, I don't know if I'm requesting something that's much more complicated than it seems. :P

**Comment by huwb** [comment]
Oh haha yeah I completely blanked taking the sun direction into account!! Actually this inspired me to try a different model that has less colours and should be much simpler to tweak - it sets the colour based on angle compared to the sun.

Also i made the colours HDR for it so you can give them any oompth they might need.

I just pushed a commit that has the "gradient sky" disabled and a new "dot prod sky" enabled, it should be fairly simple to tweak:

![image](https://user-images.githubusercontent.com/939901/44972029-a7f61680-af4f-11e8-81c4-2324225046cf.png)

**Comment by Midda-C** [comment]
Yeah, that's muuuch easier to manage!  It's pretty easy to—if I want to—very closely match the output from our reflection probe, plus then it's easy to take some creative license with it.

Of course, I can't speak for all use-cases, but I think this will suit our needs nicely, and will plug into our dynamic day/night system really easily.  It's certainly more robust than things I've seen in other Ocean packages.

Nicely done! :D

**Comment by huwb** [comment]
Alright! Seeing that seems to have gone down really well, i cleaned it up and merged it into master. It is a material option that is disabled by default. Let me know how you get on it with it.
