### ISSUE TITLE
is waveparticle working for shape generating?

### ISSUE THREAD

**Issue by kojiyijian** [huwb/crest-oceanrender#5]
when i change wave share to WaveParticle, the surface won't wave. it doesn't working right now?

**Comment by huwb** [comment]
hi there, I'm sorry I haven't replied until now. 

The wave particle should just generate a "bump" of water. This can be used to influence the shape locally, as an additive layer on top of the normal waves. It might be broken right now though.

I need to jump in and have a look. I'm very busy at work at the moment but should have time to look at it during the week or next weekend. I'll post back when I do and let you know what you should expect to see in detail.
