### ISSUE TITLE
Explore more control over light scattering through waves

### ISSUE THREAD

**Issue by huwb** [huwb/crest-oceanrender#52]
Potentially add scattered light based on wave height, or some smarter scheme.

Originated from discussion in #33

**Comment by huwb** [comment]
@Midda-C @holdingjason

Added a height based scattering in the commit referenced above.

Best way to experiment with it is to set the *Crest Colour* to bright red! You can can experiment with the height range and and exponent/power and have some fun making alien planet ocean waves :).

I've used a similar term in previous projects and its worked pretty well. I thought of more complicated schemes but simplest might be best here. Its not very scientific - a good direction for RnD would be to offline render what the scattering looks like and actually try to approximate it..

Anyway let me know what you think. I'm pretty happy with the results im getting from this in the main scene (example content) on this branch..

**Comment by huwb** [comment]
Put it in a box :)

![image](https://user-images.githubusercontent.com/939901/44448014-d567c980-a60b-11e8-85ce-d1ca55256791.png)

**Comment by huwb** [comment]
Bonus feature time.. im looking at adding an optional term for shallow water, in real life the ocean floor has a dramatic effect on the ocean colour due to all the multi-scattered light, and this attempts to approximate this effect:

![image](https://user-images.githubusercontent.com/939901/44450149-fdf2c200-a611-11e8-8165-ecd716d07908.png)

Together these additions should give a much nicer range of colours from the water.

**Comment by Midda-C** [comment]
Oh cool, I'd been thinking about making an issue for shallow water colour.  Just tried it in our scene, it looks awesome!

I couldn't get the height lerp to do anything at first, but it turned out that Unity needed me to toggle it off and on again (it defaulted to on), which it kicked into gear.  I assume that wouldn't be an issue on a new material.  I think something similar happened a while back when you added a toggle to something else.  Problem-Solving 101—try turning it off and on again.

**Comment by Midda-C** [comment]
Oh, and it might be a good idea to clamp the Height max and depth power parameters, since they seem to break if they're set to zero.

**Comment by huwb** [comment]
Yeah i've had to do the same turn off and on again myself :/ i'll consider adding a note in the readme.

I've tweaked the ranges and merged it into master now. If you have any feedback or issues with it let me know and i'll reopen. Nice one!
