### ISSUE TITLE
Pause bug is back

### ISSUE THREAD

**Issue by holdingjason** [huwb/crest-oceanrender#55]
Pause  the game, wait awhile, ocean goes nuts when unpausing (that is not a word).  Settles down after a few.

**Comment by Midda-C** [comment]
Is this the same thing as mentioned in #38?  Because yeah, we're still seeing this at very low timescales (and I believe sometimes when paused).

**Comment by huwb** [comment]
Thanks guys... Issues with the sim timestep seem to be resilient super bugs :/. I'll post back when I've had a new attempt.

**Comment by huwb** [comment]
See my last comment on issue #44

**Comment by huwb** [comment]
Should be fixed on 9756b495ad33daee0b1bfd2720425e9aed6fecbe . I tried different patterns of pausing/unpausing, including tabbing away from the editor. Simulation substep counts and dts are now carefully controlled so the above behaviour should not be possible anymore.
