### ISSUE TITLE
Transparancy bug?

### ISSUE THREAD

**Issue by Midda-C** [huwb/crest-oceanrender#6]
I've just grabbed the latest data, and I'm seeing something strange with the transparency.  It sort of looks like the depth mask is inverted or something?  I've recorded a [clip of the issue here](https://drive.google.com/open?id=1jYuSN6YkzhT9PoUjFmHn2hnE_X8Pv885).  I've seen this in the scene view in the past, but this is happening in the Game window.

I'm using Unity 2017.3.1p4.  I've just downloaded the project from GitHub and opened the Unity folder as a project.

Any ideas what this could be?

**Comment by GeorgeDziov** [comment]
+1 Same issue in versions 5.6.5, 2017.3 & 2018.1, unchecking "Allow HDR" helps, no reflection though.

**Comment by huwb** [comment]
This was me being sloppy and not learning how to Unity properly. Sorry guys. I'm now using the right macros to make sure the texture coordinates are correct, and tested both views and with/without the HDR flag.

GeorgeDziov - reflections are a separate topic, this will only fix refraction. There is some discussion about how best to reflect the environment/respond to lighting in issue #4

**Comment by huwb** [comment]
Oh - this is fixed on 372da8e31f77c7070bb3ad2adc2596c7a0e83b82 . Please reopen if you find issues. Thanks!

**Comment by Midda-C** [comment]
Yep, confirmed fixed on this end.  Thanks! :D
