### ISSUE TITLE
Build vs Editor Fog Issue

### ISSUE THREAD

**Issue by holdingjason** [huwb/crest-oceanrender#69]
Ok not sure what this could be but the Ocean applies the standard fog from lighting without issue (Expo Squared 0.05) while running the project via editor.  The editor is running in standard default Fantastic Quality.  Doing a build and running (again fantastic) the fog is no longer applied to the ocean.

Any thoughts?  Trying to track it down myself right now but so far no luck.  Will grab latest and do a stripped down version outside of my project.

**Comment by huwb** [comment]
Ah ok, no immediate thoughts but I'll get back to you once I've had a chance to try it in the next day or two, hopefully I can repro it here. Let me know if you find anything. Thanks!

**Comment by holdingjason** [comment]
Ok just pulling the latest build and applying fogging at the settings I mentioned and then building an exe does not replicate the issue.  So something else is going on that I need to examine.  My guess something to do with deferred rendering since the default would be forward and my bad build used deferred.  Trying that next.

**Comment by holdingjason** [comment]
Ok have an update @huwb .  Fog works fine if its on by default but does not work if its on via script at some other point at run time.  So taking the default project and adding the following script to the camera will show the issue.  Fog should be set to expo sqrd and then disabled.  I am running in deferred but not sure that matters at all.  Cull mode is off so you can see it underwater.

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class UnderWater : MonoBehaviour {

	// Use this for initialization
	void Start () {
		
	}
	
	// Update is called once per frame
	void Update ()
    {
        if (transform.position.y <= 5)
        {
            RenderSettings.fogDensity = 0.05f;
            RenderSettings.fog = true;
        }
	}
}

**Comment by holdingjason** [comment]
Hmmm maybe never mind.  It looks like the issue is at runtime the fog is not getting turned on so I think the issue is with rendersettings and not crest.  Confirming that.

**Comment by holdingjason** [comment]
Ok sometimes I want to punch unity in the face.  Ok here is the issue.  Unity by default strips out the fog shaders if you have not set them up by default.  Might want to make a note of this somewhere in the manual stuff and kill this thread.  Sorry for jumping to an assumption this was crest and not something in Unity.

https://stackoverflow.com/questions/23541146/no-fog-after-build

**Comment by huwb** [comment]
Ah thanks for diagnosing and reporting back, its valuable to have record of it here. I'll close this for now but will refer back to it if someone else runs into this.
