### ISSUE TITLE
Unity LWRP demo source available

### ISSUE THREAD

**Issue by Midda-C** [huwb/crest-oceanrender#71]
Hey!  I know you were waiting for this, not sure if you've seen that it's been released.

https://github.com/Verasl/BoatAttack

Hopefully there are some tasty morsels that can help with Crest :)

**Comment by huwb** [comment]
Thanks, good stuff! I'll go through it in a bit.

**Comment by huwb** [comment]
It looks good and useful, especially when thinking about going to LWRP. Also really good to see a modern demo of how things should be made in unity, has given me a few ideas to freshen some stuff up in crest.

The C# job stuff is also really useful to see and is something i really need to dive into at some point. All of the chunky work in crest is done on the GPU anyway so its less relevant for us, at the moment anyway.

Thanks for pinging that through!
