### ISSUE TITLE
Wave frequency

### ISSUE THREAD

**Issue by gamemachine** [huwb/crest-oceanrender#74]
Maybe I missed it, but I didn't see any knobs for controlling the spacing between waves?

**Comment by huwb** [comment]
Hi there,

Could you expand on what you mean by spacing between waves?

The ocean surface is formed by adding lots of waves together. It's surprisingly hard to find a good image of this online but i guess this will do:

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQytEpO2BbXDljlGiVThDSi_hcoa9P83CuduL6TqgXEl6hjZ1r94w

There is not a direct concept of spacing between waves, but you can control the contribution of each wavelength using the equaliser interface in Crest.

It would also be possible to vary wave conditions over time or have different waves in different areas of the world (or, thinking about it, we could even have a set of wave conditions that is animated to move through the world - that would be cool to try actually). Oh and finally if you can bake out the waves you want as a displacement texture (from Blender or Houdini or wherever) then these could be sampled these to create the ocean shape in teh game. This is a fairly memory intensive route though i guess, and i think these will have the same issue as described above in achieving 'spacing between waves').

**Comment by gamemachine** [comment]
I mean the spacing between waves that are in a specific point on the spectrum.  So at each slot on the spectrum, the waves are all equal distance from each other.  

Real ocean water the larger the waves the more space between them.   So unless you make the water super noisy it starts to look noticeably awkward if you bump up the power on the larger waves.  64-128 I think are the most noticeable,   Not a big deal I can get pretty close by tweaking just the right amount of noise.

**Comment by huwb** [comment]
Ah ok I get it.

What requirements are driving what you need, if I can ask? Were you looking to make it less repetitive, or was it something for gameplay..?

Would be useful to understand your situation. I think we can improve this.

**Comment by gamemachine** [comment]
My use case is gameplay, different sized waves for different types of challenges for various ships.

**Comment by gamemachine** [comment]
Ya increasing the wavelength per range is what I meant, but not a big deal if it's too much work.

**Comment by huwb** [comment]
Ok I'll close then. A change like this would go against the design of the system. Thanks for the note.
