### ISSUE TITLE
Glowing subsurface bubble foam

### ISSUE THREAD

**Issue by Midda-C** [huwb/crest-oceanrender#78]
During our day/night cycle, we're seeing that the subsurface bubble foam looks a bit glowy/emissive during the night.  I suspect it's maybe not being multiplied by the light colour?  A "Light Scale" slider like what the regular foam has would probably be a good option.

**Comment by huwb** [comment]
Thanks Midda. I just remembered you mentioned this on another issue and i forgot, apologies!!

I'll report back after i look into it.

**Comment by Midda-C** [comment]
Yep, added this locally, and it seems to do the trick.  Nice and easy! :D

**Comment by huwb** [comment]
Good stuff, merged!
