### ISSUE TITLE
Surface noise

### ISSUE THREAD

**Issue by gamemachine** [huwb/crest-oceanrender#85]
Just something I was thinking about so thought I'd put it out there.

One of the nice things about crest is the ability to have fine grained control over the wave spectrum.  Which for gameplay water is often desired.

But another layer would really take it to the next level IMO.  Something like an FFT layer that basically just adds some realistic surface noise.

For example if you look at what is IMO the best water you can find in a game, Sea of Thieves, they do something similar.  They have configurable wave ranges to some extent like crest with what I'm guessing is FFT layered in.  

FFT would be a huge chunk of work, so I was thinking maybe a good poor man's approach would be adding support for a bump map?

**Comment by huwb** [comment]
@HyroVitalyProtago contributed a relevant link in #86, referenced above.

**Comment by huwb** [comment]
You can add high frequency waves that do not affect the physics. This is being discussed in #64 .

A bump map is an alternate form of a normal map which we're using. A displacement texture is the other way to add surface shape - we're already using displacement textures too :).

However, this line of thought did make me think about the apparent detail, and I think i've been a bit too gentle with the shading in the example content. In the branch https://github.com/huwb/crest-oceanrender/tree/feature/ocean-retweaking , I have added control for refraction strength and boosted the normals.

This video shows those changes, and attempts to get a noisy/detailed ocean shape:

https://drive.google.com/open?id=1x2ZZldd-3ZGyc_evrYyZRp-cDph8jq1U

What do you guys think?

If we want to hone it further it would help to identify visual target with images/video, there are a lot of subtleties and text descriptions are not very actionable. I attempted to identify one while working on this stuff, but this is not my area of expertise and I ran out of steam and decided to post the above.

Btw, @moosichu is experimenting with wave particles (in a similar vein to that uncharted presentation), I'll let him report any findings.

**Comment by huwb** [comment]
I merged in the changes so far, see referenced PR above.

**Comment by huwb** [comment]
I'll close this as I don't have further plans to work on this. We'll post if there's any update with wave particles
