### ISSUE TITLE
Planar reflection delay

### ISSUE THREAD

**Issue by Midda-C** [huwb/crest-oceanrender#87]
We've been doing some tests with another scene in our game.  This scene is separate from the rest of the game, and is rather empty, so we're thinking we can probably get away with using the new planar reflections here.  We turned it on and it looks great, but we're noticing a delay of a frame or two in the reflection.  Because the water is fairly still, the reflections are very clearly seen, making the lag quite easy to spot.

Is this something that can be easily avoided?  Or is it a known limitation?

**Comment by huwb** [comment]
Hey! Thats interesting, good stuff.

This is definitely solvable. I've seen this lag in the past but testing now it seems to be working frame perfect for me. I believe the only requirement is that the reflection camera renders before the main camera. What Depth is your camera set to? I tried both -1 and 0 and I did not get lag.

It could be interesting to know if the main scene from the crest example stuff also exhibits lag for you.

**Comment by Midda-C** [comment]
Okay, so it looks like it might be something on our end.  When we fly around our scene using our free-cam, it's fine.  However, our regular game camera is using Unity's Cinemachine system, so it's probably something going on in there.  Will let you know if we find anything.

**Comment by huwb** [comment]
Oh :/. It might be that cinemachine is updating after the reflection script. The reflection updates in LateUpdate. It needs cinemachine to have done its stuff before then. I believe unity animation should complete before LateUpdate - but it's possible cinemachine is doing stuff during lateupdate or even later..

**Comment by huwb** [comment]
Did a bit of googling, didnt understand everything but it seems cinemachine has a brain and you can configure whether it runs in fixed update or late update? https://forum.unity.com/threads/cinemachine-crazy-jitter.465865/ . i dont know why it doesnt have an option for normal update :/. i think setting it to run in fixedupdate should sort the issue, but camera/animation logic is not supposed to run on higher frequency updates :/.

I'm guessing cinemachine must be in lateupdate by default. Another test would be to set the execution order value for OceanPlanarReflection to a large number (it should be set to 800 currently). This may help bump it past cinemachine in the queue so the reflection gets a final position.

A last ditch attempt at a solution might be to hook the reflection update to cinemachine (sigh) - there seems to be a way to do this https://forum.unity.com/threads/cinemachine-update-methods.502339/

Its a shame cinemachine does not run during animation update, between Update and LateUpdate.

**Comment by huwb** [comment]
Ok after all that complaining, I think i found a way to safeguard the crest reflection script against these kinds of issues - i moved the reflection update to OnPreRender. I had forgotten about this hook, i havent used it before but it seems to work for me here. Could you guys try it out? #92

**Comment by Midda-C** [comment]
Oh, nice!  Yeah, that did the trick.  We had moved the Cinemachine Brain to execute fairly late, because we were having some other issues a while back.

This change has sorted it out nicely though.  Thanks again! :D

**Comment by huwb** [comment]
Ahhh ok. I'm happy to hear its working!

It occurs to me now theres a pretty big assumption that animation has completed before lateupdate in Crest. The ocean is placed in LateUpdate, and then all the ocean data is updated using the placed transform. I would expect that you get jitter on the ocean surface as well, this might be masked sometimes because the ocean snaps to a regular grid, but might get worse with faster motion. If you have the debug GUI then it would be interesting to know if you ever see pops in wireframe rendering mode. If not then maybe it's fine.

**Comment by huwb** [comment]
I'll close this but we can reopen as necessary. Thanks for working this through with me.
