### ISSUE TITLE
Get Height of only certain spectrums

### ISSUE THREAD

**Issue by holdingjason** [huwb/crest-oceanrender#91]
Was wondering if it would be possible to get the sample height at a point in space but only for certain wave spectrums? 

The issue I am working on for us is trying to filter out the smaller chop for buoyancy.  With a lot of chop from the smaller waves the boat will tend to dance around a bit more then we like.  Basically just want the boat to react to the large wave cycles and ride those and ignore the smaller stuff.

Now maybe there is a better way to do this so happy to field any ideas anyone has.  Idea is similar to if you look a sea of thieves you will notice they are ignoring most of the crazy water they have going on and not reacting to it, only to the large cycles (at least that is what it appears to us).  Probably not super realistic but it feels better for what we are doing.

Other approaches we have tried would be to increase the mass of the ship as that will effect the reaction to the force being applied upward as the boat goes deeper into the water, however what this really means is the boat reacts slower to changes in water height.  This again is realistic boat now you need a much bigger boat to avoid the bow dipping into the water and having the water go up over the top of the deck.  This is obviously not desirable.  Granted that is a solution that would work though it can be a bit tough to get the balance right on reaction time vs chop movement.  That takes us back to basically just ignoring the stuff we don't want to react to which seems less complex and error prone.  Realizing of course whatever your ignoring the boat would have to be higher then to keep those waves from flowing over the top.

 Sorry for the rambling discourse.  Need more coffee.

**Comment by huwb** [comment]
Hey!

There is a mechanism to do this - there is a discussion over at #64 - its the boat width param on the script, which will set a minimum wavelength to use for the sample. Perhaps give that a read and let me know if it makes sense?

**Comment by holdingjason** [comment]
Oh great sorry I missed that will take a look.

**Comment by huwb** [comment]
Sweet!
