### ISSUE TITLE
Shallow color.  Foam.  Showing up in weird places.

### ISSUE THREAD

**Issue by holdingjason** [huwb/crest-oceanrender#96]
UPDATE: ABORT.  Someone updated that colliders and they are way deeper then on the test box.  Ok I do not think this is an issue.  My bad sorry about that.  

Update #2.  However its still slightly off.  Fixed the collider but the shift is still there just not as bad.  Will post a new shot below.

OK so just to continue driving you nuts, guessing you did not miss me.  I was being force into actually game play work for the last few weeks but now back on this.

So can only really explain this with a screen shot.  I believe this has to do with the Ocean Depth Cache.

So a couple of things.  

1.  We have a box collider around the top of deck but it does not extend down, simply covers around a 0.2 y so does not come near the water.  Is there away to only pick this stuff up at a certain height?  Do not really want the deck to be being picked up at all just the pillars.  Granted I think that maybe is what the exclude layer is for so probably can work around that.

2.  I would have expected the foam etc to be rendered under the collider not off the to side like this so that is strange.  

![image](https://user-images.githubusercontent.com/42001313/46702642-b7b0ec80-cbd8-11e8-9e2a-93bd760fcf01.png)

Looks like everything is shifted.  Even the beach is rendering weird.

![image](https://user-images.githubusercontent.com/42001313/46702787-576e7a80-cbd9-11e8-96c8-e50d20e6c5c3.png)

**Comment by holdingjason** [comment]
Great so far cannot replicate in the crest example demo.  Putting a simple cube above the water works fine.  Do not see any offset. Hmmm.

**Comment by holdingjason** [comment]
![image](https://user-images.githubusercontent.com/42001313/46704288-33ae3300-cbdf-11e8-9dac-73ec8af60ec7.png)

**Comment by holdingjason** [comment]
This might be more of an issue with me understanding how the depth cache works and figuring out the shallows and foam around objects.  

It appears based on my testing so far that once an object, like a block is placed, on startup we figure out at the point in the water height where to place the foam etc?  So if we had really choppy water then where it picks might be off from the actual object.  That is what it appears.  So looking at adding a cube to the demo the foam does not really correspond well with the edges of the cube.  Again it is a bit off center guessing based around when it does the calculation and the water height.  Guessing here.  So I can probably prove this by using very flat water with little motion vs choppy water and see how things line up.

**Comment by holdingjason** [comment]
I have no bloody idea what is going on :)  Zooming out with the camera more foam shows up but at an angle to the object.

![image](https://user-images.githubusercontent.com/42001313/46705453-70305d80-cbe4-11e8-8890-1f4e5f0f76b5.png)

**Comment by huwb** [comment]
Hm a dumb suggestion to start with - it's not just the resolution being low is it? I.e. try setting the depth cache resolution to a high value and see if it helps?

What is your sea level (y value)? Just wondering if precision might be an issue.

I can't think of any reason for a shift. The depth cache populated by rendering default layer geometry now instead of a terrain layer - at least that's the default behaviour. You guys might have it set up different. Thought I'd mention it.

Oh dizzy added a debug option to populate the cache every frame, try that to see if it is stale data or if it is a persistent error?

**Comment by holdingjason** [comment]
Ocean y value is 2.

So I created a solid block and put it in the water, lower the terrain a bit and just wanted to know if what I see here in this video is what you would expect?

https://drive.google.com/open?id=14ghZfclP9dloMQhBrMU1-VhVK8DuBJrR

**Comment by holdingjason** [comment]
Here is another shot using your demo scene.  Lowered the terrain so that would not interfere and its a transparent cube going into the water like a pylon.

https://drive.google.com/open?id=1quMwhxtsfn9lPDYy4mb0EjkOEHekPz-w

**Comment by holdingjason** [comment]
Here is another shot with the resolution pushed up to 10000 it appears more or less the same from a motion standpoint as the others just retains the original shape of the object better which is not necessarily what we are looking for.

https://drive.google.com/open?id=1whAKoB--Mclw4bWBLlKEI3-p1assu0LQ

**Comment by holdingjason** [comment]
So I take it the data used to determine where to change the shallow color and apply "shore" foam is generated on startup based on the geometry of items, on certain layers, inside the boundaries of the depth cache.  This mask then is fixed and moves around based on the motion of the water and has little to do with the actually object at that point.  Though I do notice turning off the object the foam etc disappears so it does know about it.  

So the issue is that this looks pretty strange.  The foam and shallow are not really "around" the object but just kind of mask it and then move according to the wave pattern which creates some odd visuals as we see here.  Its more like I want the mask to be fixed to a spot and not move (it appears it moves around with the waves right now) and applies itself to an area around that fixed spot based on the generated mask.

Sorry I am using terms I understand but I am sure have no bearing on how this is actually implemented so hopefully I am at least crudely getting my idea across.

**Comment by holdingjason** [comment]
Cause you can never have enough video.  

https://drive.google.com/open?id=1miwU2VVpTB17duCbNByFm002y0J9YjWY

**Comment by huwb** [comment]
One thing i've been meaning to do is start another documentation pass. I've started building documentation here: https://github.com/huwb/crest-oceanrender/blob/master/TECHNOLOGY.md . Let me know what does/doesnt make sense.

> We have a box collider around the top of deck but it does not extend down, simply covers around a 0.2 y so does not come near the water

Worth noting that Crest does not use colliders to give the height, it uses the render geometry.


> Is there away to only pick this stuff up at a certain height? 

Yes, the *Camera Max Terrain Height* property should do this, on the Ocean Depth Cache script.


From your videos it does appear that the wave displacement is carrying foam away from its intended position. This is slightly tricky to solve. One option we could discuss is to scale down displacement in select areas. Another option might be to, in ShapeSimFoam.shader, invert the displacement before generating foam. I'll think about if this is possible/easy/efficient to do.

**Comment by holdingjason** [comment]
Understood on the geo vs collider.  Thought that was what the max terrain height did but when I messed with it could never get it to work properly so need to delve into that more.  If I moved it up then the depth calming action on the waves stopped working.

>>>From your videos it does appear that the wave displacement is carrying foam away from its intended position. If this is true you should see oscillation around the correct position, given enough time

Yes this is exactly what I see and shows up in the various videos.  The foam pattern kind of moves around the geometry that created the pattern based on the waves.  Not sure I followed what you were purposing.  When you say scaling down the displacement are you talking about wave displacement around the intended position, i.e waves would be calmed down around an object.  Not sure what inverting the displacement would mean for your second approach.  What you really want is to generate the foam around a fixed point that has no displacement.  

In either case the other issue is that the area of foam coverage is to small as well.  So in the examples here you can see that the foam is INSIDE the cube.  The only reason we ever see it is because it moves around on the waves and pops out occasionally on one side or another.  Again would want it to generate foam from the original position out from there a certain distance based on the various foam settings but right now no foam setting will push this out far enough to show if it stayed where I want it to at least I think that is true.

**Comment by huwb** [comment]
There are a lot of issues on the go here so i'll start labelling them:


A. Scaling down the displacement meant - I fleshed out the documentation a bit more, it now covers what is required in more detail to manipulate the ocean shape - see the Animated Waves section: https://github.com/huwb/crest-oceanrender/blob/master/TECHNOLOGY.md . As hinted here, you can use any type of blending. What I had in mind in this case was a smooth fall off, multiplicative blend that would multiply the X and Z channels down to 0. This would mean the ocean would not be moving horizontally under the pier. I'm not sure how this would look in practice.


B. Inverting the displacements. I updated the documentation with a note about this issue:

> When rendering the ocean, the various LOD data are sample for each vert and the vert is displaced. This means that the data is carried with the waves away from its rest position. For some data like wave foam this is fine and desirable. For other data such as the depth to the ocean floor, this is not a quantity that should move around with the waves and this can currently cause issues, such as shallow water appearing to move with the waves as in issue 96.

'Inverting the displacement' would mean something like making sure the foam sim is sampling the correct water depth at the *displaced* water position. Actually maybe nothing needs to be inverted, the following changes to *ShapeSimFoam.shader* may work:

1. Pass world position through to fragment shader 
2. Add displacement (variable *s*) to the world position
3. Compute a new displacedUV at this new position: displacedUV = LD_1_WorldToUV(i.worldPos);
4. Sample shallow water from the displaced location: float signedOceanDepth = DEPTH_BASELINE - tex2Dlod(_LD_Sampler_SeaFloorDepth_1, uv).x + disp.y;


C. Regarding fade rates, I think it would be possible to make the foam texture a 2 channel target and modify ShapeSimFoam shader to output one value for each type, and then sum them later in the ocean shader. The shadowing data also does something along these lines.

We had our foamy megathread #33 which discussed this at some length. Currently I hope to have just one fade rate for all foam and not break this out, in core Crest. I don't use the kinds of high foam rates that you guys use, and it works fine for the example content IMO, so I don't want to add the extra computation for a second channel. However i'd be curious to hear how it works out.


D. Foam outside pylon - this is a fairly fundamental issue - i render the height of the terrain from a top down orthographic camera, and the pylon is indistuingishable from this angle from a cube floating above the surface. You could add a fake/invisible geometry that makes a smooth ramp under the water, which would then generate shoreline foam. It would also ramp down the waves too, which would be somewhat similar to A above, but would ramp down all three channels of the waves (height too) which would probably look even weirder. For cases like this, i'd recommend adding your own foam by rendering some foam values into the sim. Starting with the Animated Waves section i ahve written some words about rendering your own stuff into sims: https://github.com/huwb/crest-oceanrender/blob/master/TECHNOLOGY.md , with examples. For the foam case, @moosichu actually made a foam-depositor while messing around with flow and whirlpools - see the *DepositFoam* gameobject in the whirlpool.unity scene. It should be a copy paste job to use this in your own scenes.

**Comment by holdingjason** [comment]
@huwb Not totally related to this thread but similar.  I am working on foam around objects for instance a splash particle effect or as the boat is moving around.  One thing I notice is the foam around objects is related to  Ocean Depth Cache ie I think you need this in order to have the foam show up and it needs to be set to force update continuously so the foam goes away.

I think I need a bit of a refresher or more info on what the  Ocean Depth Cache is doing and if I am right or wrong on how foam shows up around moving objects.  So perhaps a bit of detail on what this does and how?  So I was using the  Ocean Depth Cache basically as a way to smooth out the ocean around landmasses but perhaps this is a very incorrect way of thinking about it since it also effects how foam is applied.

I was able to solve my above issue of the foam showing up under piers by setting the camera max terrain height like you said to a correct value where it covers the ocean around the shore but not high enough to include the top of the pier.  That cleaned that up (not the displacement issue obviously).  

Will look more into the boat movement examples but just want to know what causes or how to cause dynamic foam to show up around things (and have it go away after the object moves off etc).

I can also image other ways to do effects like this using the transparent logo example for instance, ie rendering imagery onto the water and fading it over time which would probably look pretty nice.  Also projecting particles at water height and angling them overtime to match the water normals.  Those would probably both give nice results but if we also wanted to include your internal foam as well that is kind of what I am trying to understand.

Thanks.

**Comment by huwb** [comment]
The sea floor depth data is used for a few different things. It is documented here in the Sea Floor Depth section:

https://github.com/huwb/crest-oceanrender/blob/master/TECHNOLOGY.md

Let me know what is clear/unclear and so i can update the docs.

**Comment by huwb** [comment]
Regarding disassociated/disconnected foam and shallow water, each has a separate fix.

The fix for the foam was low impact and I've pushed it to master: da8df6a3369766b5a810f2dd9ca9221aadcd3918

The fix for the shallow water was a bit more intrusive and i was not 100% comfortable pushing to master so i put in a branch: 3be5683bfc22264243191bd02cd7e3ffff3b2741 . We should verify perf isn't affected before taking this.

https://drive.google.com/open?id=1jcQbimuogN91zj-O05btY4dmkFOpngxG

**Comment by holdingjason** [comment]
Ok will take a look at this branch and the particle one.  Merged your master changes into out build and worked like a dream this time.  Not seeing any GC Allocs at all right now so that shaved off 1-2ms on our floating objects + no more random 6ms spikes for GC.   Also seeing a big jump FPS because of the command buffer stuff so nice nice job.

**Comment by huwb** [comment]
Giving another old issue a bump. Any news on this one?

Not really sure what I'm asking for here - i guess if you were to try it and reported back that it solved a big problem for you, or that it did not adversely affect perf, or ideally both, then id feel more comfortable merging into master. Otherwise I may close this one and see how many people run into this in the future and reassess at that time.

**Comment by holdingjason** [comment]
Ok not really doing anything with this right now.  Basically set the depth stuff to a point where it does not effect the docks.  What we would really want is that the pylons have a little foam around them similar to the shore but not pick up the top of the docks (which was what was happening before).  Right now we are just not having them interact with the water at all.   

So looking at your documentation it would appear perhaps that each pylon would have to be a separate object from the top of the dock otherwise my guess is the whole thing would foam up again (top down geometry is what the docs said).  So I guess I am also not sure where I stand on this.  I guess let me know what you think about these two issues the pylons and boat wake and we can go from there.

Here is a shot.  

![image](https://user-images.githubusercontent.com/42001313/50363744-e07f2780-0521-11e9-817a-21666dcbb63d.png)

Also one way we solved the boat foam wake issue was to just render transparent wake behind, side of the ships ie the crest logo.

![image](https://user-images.githubusercontent.com/42001313/50363790-1ae8c480-0522-11e9-83a7-a1fb0c610377.png)

**Comment by huwb** [comment]
I'd recommend adding foam emitters. See *DepositFoamTex* in *whirlpool.unity*. You might have to jack up the strength a lot as you are using a high fade rate IIRC.
